### ISSUE TITLE
Overriding `name` and `namespace`

### ISSUE THREAD

**Issue by nightscape** [sksamuel/avro4s#104]
Hi @sksamuel,

we're currently evaluating using avro4s in a mixed service landscape with some Ruby and some Scala services. As the naming schemas between Ruby and Scala don't line up nicely I'm wondering if it would make sense to allow different ways to generate the `name` and `namespace`.
One way I could imagine is via something like
```scala
package com.github.acme
@Avro(name = "my_event", namespace = "acme")
case class MyEvent(i: Int)
```
Another way would be to allow specifying naming schemas similar to how e.g. Quill does it (see the section about `Naming strategy` [here](http://getquill.io/#contexts-sql-contexts)).

If you think this would be useful and feasible, we can try to create a PR.

**Comment by sksamuel** [comment]
I think adding an implicit naming strategy might be the best way to do it.

**Comment by YuvalItzchakov** [comment]
@nightscape I didn't notice this issue, I partially addressed the namespacing issue with https://github.com/sksamuel/avro4s/pull/122. I'll give the naming strategy approach a shot as well, it may be a better fit and we'll be able to also address types which we don't have the source for.

**Comment by sksamuel** [comment]
I'ved added support for this in 2.0. You can try 2.0.0-M3 and let me know if it works for you. You just need to bring an implicit `NamingStrategy` into scope before you call `AvroSchema[T]`. The limitation at the moment is that it only works when generating schemas and encoding data, not reading back in, but I can add that if there's demand.

**Comment by sksamuel** [comment]
2.0.0 is now released with this supported, so closing this ticket.
