### ISSUE TITLE
JSON deserializing of default parameter values

### ISSUE THREAD

**Issue by rzats** [sksamuel/avro4s#106]
avro4s currently has partial support for default parameter values (added in 1.4.1 / #24) - however, while defaults in case classes are correctly represented in generated schema instances, JSON that doesn't contain a specific field cannot be parsed as a case class with the field set to its' default value.

REPL-based example:
```
import java.io._
import com.sksamuel.avro4s._

scala> case class Foo (bar: String = "")
defined class Foo

scala> AvroSchema[Foo]
res0: org.apache.avro.Schema = {"type":"record","name":"Foo","namespace":"$iw","fields":[{"name":"bar","type":"string","default":""}]}

scala> val json1 = "{\"bar\": \"baz\"}"
json1: String = {"bar": "baz"}

scala> val in1 = new ByteArrayInputStream(json1.getBytes("UTF-8"))
in1: java.io.ByteArrayInputStream = java.io.ByteArrayInputStream@280bc753

scala> AvroInputStream.json[Foo](in1).singleEntity                    ^
res1: scala.util.Try[Foo] = Success(Foo(baz))

scala> val json2 = "{}"
json2: String = {}

scala> val in2 = new ByteArrayInputStream(json2.getBytes("UTF-8"))
in2: java.io.ByteArrayInputStream = java.io.ByteArrayInputStream@14034746

scala> AvroInputStream.json[Foo](in2).singleEntity
res2: scala.util.Try[Foo] = Failure(org.apache.avro.AvroTypeException: Expected string. Got END_OBJECT)
```

**Comment by sksamuel** [comment]
turns out the issue is that the default values are just ignored by the java implementations. I've added a workaround which will catch the exception and then look for a default value.

**Comment by rishiraushan91** [comment]
Hi,
Same problem I am facing in Java.
I have below schema.
org.apache.avro.Schema = {"type":"record","name":"Foo","namespace":"$iw","fields":[{"name":"bar","type":{"type": "string", "avro.java.string": "String"},"default": null}]}
If I am providing the coreect value the it's ran successfuly
String json1 = {"bar": "baz"}
GenericDatumReader<GenericRecord> reader = new GenericDatumReader<>(STREAM_VALUE_SCHEMA);
        Decoder jsonDecoder = DecoderFactory.get().jsonDecoder(Schema, json2.toString());
        GenericRecord record = reader.read(null, jsonDecoder);
When I provided below string
String json2 = "{}";
GenericDatumReader<GenericRecord> reader = new GenericDatumReader<>(STREAM_VALUE_SCHEMA);
Decoder jsonDecoder = DecoderFactory.get().jsonDecoder(Schema, json2.toString());
GenericRecord record = reader.read(null, jsonDecoder);
I am getting below exception :-
Expected string. Got END_OBJECT
org.apache.avro.AvroTypeException: Expected string. Got END_OBJECT
	at org.apache.avro.io.JsonDecoder.error(JsonDecoder.java:698)
	at org.apache.avro.io.JsonDecoder.readString(JsonDecoder.java:227)


Help Indeed!
