### ISSUE TITLE
Avro schema embedded along with binary

### ISSUE THREAD

**Issue by arsenaid** [sksamuel/avro4s#11]
Hi,
I was trying to use your library for publishing Kafka messages with Avro. The problem I ran into is the consumer side cannot parse the message because schema is embedded with binary content. It looks like an object container file. Is there a way around it?

Thank you,
Arsen

**Comment by sksamuel** [comment]
Hi,

Not sure what you mean exactly. Avro files always contain the schema. Can you explain a bit more?

**Comment by arsenaid** [comment]
I am looking for schema-less serialization capabilities by directly operating on its own Datum Reader and Writer classes. That allows for more efficient communication especially when schema becomes large.

Here is an example: https://github.com/hailpam/avro-benchmark

**Comment by arsenaid** [comment]
Here is a quick example. The stream doesn't include schema in it:
`
val ingredients = new java.util.ArrayList[Ingredient]()
val schema = new org.apache.avro.Schema.Parser().parse(getClass.getResourceAsStream("/avro/Pizza.avsc"))
val pizza: GenericRecord = new GenericData.Record(schema)
pizza.put("name", "pepperoni")
pizza.put("ingredients", ingredients)
pizza.put("calories", 98)
pizza.put("vegetarian", false)
pizza.put("vegan", false)

val stream = new ByteArrayOutputStream
val encoder = EncoderFactory.get().binaryEncoder(stream, null)
val writer = new GenericDatumWriter[GenericRecord](schema)
writer.write(pizza, encoder)
encoder.flush
stream.close
stream.toByteArray.length
`

**Comment by sksamuel** [comment]
I think the easiest thing to do is add an option for that when you create
the output stream, what do you think?

**Comment by sksamuel** [comment]
Or maybe create an AvroBinaryOuputStream[Type], hmmm

**Comment by arsenaid** [comment]
I think optional output mode should do. Default can be embedded schema as now. Btw, thanks for coming with this awesome library. I'd love to use it for general purpose.

**Comment by sksamuel** [comment]
I've added this in 1.3.0.

So you can do AvroOutputStream[T](out, false) and you'll get a Binary version of the stream.
