### ISSUE TITLE
Feature Request: Support Compression codecs

### ISSUE THREAD

**Issue by FurcyPin** [sksamuel/avro4s#111]
Hi, first I would like to thank you for this lib, it works great!
I could serialize a bunch of data and read it with spark-sql in no time!

I was investigating further how I can enable compression on avro files.
As I understand, the Avro library has a few built-in compression codecs (Snappy, Deflate, bzip2, xz)
It would be great if this library could provide support for them as well.

From what I have seen, this can probably be done by using the method 
DataFileWriter.setCodec(codec) and the CodecFactory

**Comment by sksamuel** [comment]
Merged.
