### ISSUE TITLE
Binary reader API does't support schema evolution.

### ISSUE THREAD

**Issue by NetanelRabinowitz** [sksamuel/avro4s#113]
Avro has a GenericData.createDatumReader(Schema writer, Schema reader) API
Avro4s abstract over this API but if we want to read a record via the binary API `AvroInputStream.binary[newClass](in)`
we lost the ability of schema evolution because currently there is no way to pass the writer schema.
I think I't would be super beneficial to add support for this kind of API and enable schema evolution.

**Comment by OmriManor** [comment]
+1
A very valid use case, for example, when having multiple binary records in kafka, one should be able to deserialize the old/new records with a readers and writers schema.

I considered using avro4s and this was the feature that was missing.

Are there future plans on adding this support?
