### ISSUE TITLE
How to use avro4s to create generic serializer/deserializer/serde for kafka messages/streams serialization

### ISSUE THREAD

**Issue by Qantas** [sksamuel/avro4s#115]
I always got the following error messages:
serializer:
Could not find implicit SchemaFor[T]   val os = AvroOutputStream.binary[T](out)
not enough arguments for method binary: (implicit evidence$17: com.sksamuel.avro4s.SchemaFor[T], implicit evidence$18: com.sksamuel.avro4s.ToRecord[T])com.sksamuel.avro4s.AvroBinaryOutputStream[T].
Unspecified value parameters evidence$17, evidence$18.
    val os = AvroOutputStream.binary[T](out
Deserializer:
Could not find implicit SchemaFor[T]  val is = AvroInputStream.binary[T](in)
not enough arguments for method binary: (implicit evidence$11: com.sksamuel.avro4s.SchemaFor[T], implicit evidence$12: com.sksamuel.avro4s.FromRecord[T])com.sksamuel.avro4s.AvroBinaryInputStream[T].
Unspecified value parameters evidence$11, evidence$12.
    val is = AvroInputStream.binary[T](in)

**Comment by NetanelRabinowitz** [comment]
@Qantas seems like you are trying to serialize some type that doesn't implements SchemaFor and FromRecord.
in this case you can take a look at [this](https://github.com/sksamuel/avro4s#custom-type-mappings) 
can you share the type you are trying to serialize ?

**Comment by Qantas** [comment]
Thanks for the response.
There are Kafka messages and can be in any formats. 
I want to implement three interfaces under Package org.apache.kafka.common.serialization
Here is a Confluent implementation with a schema registry. 
https://github.com/confluentinc/schema-registry

**Comment by NetanelRabinowitz** [comment]
I'm not sure I follow, do you want to share the code that generate this error for you ?
