### ISSUE TITLE
Could not find implicit SchemaFor

### ISSUE THREAD

**Issue by CMeuris** [sksamuel/avro4s#116]
I'm new to Scala and to this library. 

I've got the error "Could not find implicit SchemaFor" when I try this:
case class Ingredient1(name: String, sugar: Double, fat: Double)
val schema1 = AvroSchema[Ingredient1]

And the error :
<console>:31: error: exception during macro expansion:
java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)[Ljava/lang/Object;
	at com.sksamuel.avro4s.SchemaFor$.applyImpl(SchemaFor.scala:306)
       implicit val schemaFor = SchemaFor[Ingredient]
when I try this:
case class Ingredient(name: String, sugar: Double, fat: Double)
implicit val schemaFor = SchemaFor[Ingredient]
val schema = AvroSchema[Ingredient]

What am I doing wrong?

Thanks for the help in advance.

**Comment by YuvalItzchakov** [comment]
I can't reproduce your issue:

```scala
object Avro {
  def main(args: Array[String]): Unit = {
    case class Ingredient1(name: String, sugar: Double, fat: Double)
    val schema1 = SchemaFor[Ingredient1]()
    println(schema1.toString(true))
  }
}
```

Yields:
```
{
  "type" : "record",
  "name" : "Ingredient1",
  "namespace" : "tests",
  "fields" : [ {
    "name" : "name",
    "type" : "string"
  }, {
    "name" : "sugar",
    "type" : "double"
  }, {
    "name" : "fat",
    "type" : "double"
  } ]
}
```

**Comment by sksamuel** [comment]
I can't re-produce it either.

**Comment by Maiakov** [comment]
still reproducing scala 2.12.8
avro4s 2.0.4 and 2.0.3

**Comment by codersky** [comment]
what's the scala, spark, avro4s version you use? 

> I can't re-produce it either.
