### ISSUE TITLE
Could not find implicit value for parameter builder: Shapeless.Lazy

### ISSUE THREAD

**Issue by abhitechdojo** [sksamuel/avro4s#12]
Hello,

I wrote the following code

    val schema = AvroSchema[SalesRecord]
    val output = AvroOutputStream[SalesRecord](new File(outputLocation))
    output.write(salesList)
    output.flush
    output.close

But this throws a compile time error

could not find implicit value for parameter builder: shapeless.Laxy[com.sksamuel.avro4s.AvroSchema[...]]

not enough arguments for method apply: ....
Unspecified value parameter builder.

**Comment by sksamuel** [comment]
Can you give me the definition for sales record.

**Comment by abhitechdojo** [comment]
Here is the definition. I am masking the properties names a little


import com.github.nscala_time.time.Imports._
import org.joda.time.DateTime

/**
  * Created by abhishek.srivastava on 2/5/16.
  */
class SalesRecord (
    val saleId: Int,
    val sellerId: Int,
    private val createDateStr: String,
    val vin: String,
    val make: String,
    val model: String,
    val year: Double,
    val tL: String,
    val clr: String,
    val tr: String,
    val eg: String,
    val iT: String,
    val tML: Option[String],
    val dO: Double,
    val sP: Double,
    val tG: Double,
    val fEG: Double,
    val bEG: Double,
    val cT: Option[String],
    val sT: Option[String],
    private val cDStr: String,
    private val dDStr: String,
    private val rDStr: String,
    private val pBID: String,
    val fN: Option[String],
    val mN: Option[String],
    val lN: Option[String],
    val fuN: Option[String],
    val ad: Option[String],
    val ct: Option[String],
    val st: Option[String],
    private val pCStr: String,
    val hPN: Option[String],
    val bPN: Option[String],
    val cPN: Option[String],
    val eA: Option[String],
    val eT: Option[String],
    val cN: Option[String],
    val sBID: Option[String],
    val sFN: Option[String],
    val sMN: Option[String],
    val sLN: Option[String],
    val sFuMN: Option[String],
    val sAd: Option[String],
    val sC: Option[String],
    val sS: Option[String],
    val sPC: Option[String],
    val sHPN: Option[String],
    val sBPN: Option[String],
    val sCPN: Option[String],
    val sEA: Option[String],
    val sET: Option[String],
    val sCN: Option[String])
{
  val createdUTCDate = read[String, DateTime](createDateStr, toDate)
  val contractDate = read(cDStr, toDate)
  val deliveryDate = read(dDStr, toDate)
  val reversalDate = read(rDStr, toDate)
  val primaryBuyerID = read(pBID, toInt)
  val postalCode = read(pCStr, toInt)

  private def read[T1, T2](x : T1, f : T1 => T2) : Option[T2] = {
    if (x == null) Option.empty[T2] else Some(f(x))
  }
  private def toDate(x : String) : DateTime = new DateTime(x)
  private def toInt(x: String) : Int = x.toInt
}



On Feb 5, 2016, at 6:55 PM, Stephen Samuel <notifications@github.com<mailto:notifications@github.com>> wrote:

Can you give me the definition for sales record.

**Comment by sksamuel** [comment]
It might only work on case classes. I'm not sure if shapeless can find a
Generic for a non case class. If you're on scala 2.11 can you try making it
a case class.

**Comment by abhitechdojo** [comment]
don’t the case classes have a 22 field limitation? My sales record is much wider than that.

I would try to convert this into a case class and break down the sales record into smaller entities.

On Feb 6, 2016, at 8:17 AM, Stephen Samuel <notifications@github.com<mailto:notifications@github.com>> wrote:

It might only work on case classes. I'm not sure if shapeless can find a
Generic for a non case class. If you're on scala 2.11 can you try making it
a case class.

**Comment by sksamuel** [comment]
In 2.11 they can have any size, but > 22 won't have unapply method.

**Comment by abhitechdojo** [comment]
converted my class to a case class … but still the same problem


On Feb 6, 2016, at 10:49 AM, Stephen Samuel <notifications@github.com<mailto:notifications@github.com>> wrote:

In 2.11 they can have any size, but > 22 won't have unapply method.

**Comment by sksamuel** [comment]
Ok I'll figure it out once I'm back tomorrow.

**Comment by sksamuel** [comment]
Looks like the private fields are throwing shapeless off.

**Comment by sksamuel** [comment]
This is fixed in release 1.3.0 if you want to try it.
