### ISSUE TITLE
Unused vals in macros

### ISSUE THREAD

**Issue by larochef** [sksamuel/avro4s#125]
I have the "warn unused variables" compiler flag enabled, and would like to use "fatal warnings".

But avro4s is giving me quite a few warnings I didn't manage to remove.

For instance:

```
local val in value x$10 is never used
```

I use mostly the ShemaFor[MyClass] and RecordFormat[MyClass]

I dug on this to find out that x$10 and other ones are tuples, used to initialize two variables at a time.

If I store the tuple in a variable I see the x$.* change to the variable name. As far as I found the trouble is with the following macro in SchemaFor:

```scala
 case None =>
          c.Expr[SchemaFor[T]](
            q"""
            new com.sksamuel.avro4s.SchemaFor[$tType] {
              val (incompleteSchema: org.apache.avro.Schema, completeSchema: shapeless.Lazy[org.apache.avro.Schema]) = {
                com.sksamuel.avro4s.SchemaFor.recordBuilder[$tType](
                  $name,
                  $pack,
                  shapeless.Lazy {
                    val selfSchema = incompleteSchema
                    implicit val selfToSchema: com.sksamuel.avro4s.ToSchema[$tType] = new com.sksamuel.avro4s.ToSchema[$tType] {
                      val schema: org.apache.avro.Schema = selfSchema
                    }
                    Seq(..$fieldSchemaPartTrees)
                  },
                  Seq(..$annos)
                )
              }

              def apply(): org.apache.avro.Schema = completeSchema.value
            }
          """
          )
```
where the tuple is created at line

```
val (incompleteSchema: org.apache.avro.Schema, completeSchema: shapeless.Lazy[org.apache.avro.Schema]) = {
  .....
```

I had to use scalap to see the variables and see it is a tuple.

The warning message states that a val used in the creation block is unused.

Can you have a look at it ?

**Comment by danielkman** [comment]
👍

**Comment by Lazu13** [comment]
I have the same problem having "warn if a local definition is unused" compiler flag enabled. 

Warning I am getting:
```
local val selfToSchema in value x$1 is never used
```

I'm using SchemaFor[MyClass] and ToRecord[MyClass], FromRecord[MyClass]

The warning is raised from the same part of macro code as @larochef mentioned on May 26. 
Warnings says that this value seems to be unused:
```
 implicit val selfToSchema: com.sksamuel.avro4s.ToSchema[$tType] = new com.sksamuel.avro4s.ToSchema[$tType] {
                      val schema: org.apache.avro.Schema = selfSchema
                    }
```

Is there any solution to get rid of the warning? Or any work-around the problem?
My desire is to have this compiler option enabled but getting no warnings from avr4s.

I'm using avro4s version 1.7.0
