### ISSUE TITLE
How to generate case classes from a schema

### ISSUE THREAD

**Issue by bixbyr** [sksamuel/avro4s#128]
This is probably a bit of a bone headed question, but does this package itself provide any methods for generating case classes from an existing schema or is that logic part of the sbt plugin? I'm trying to build a quick and dirty gradle wrapper to go around avro4s for generating case classes at compile time. The documentation covers just about every other use of avro4s except this. 

Thanks for writing such an awesome tool.

**Comment by MuhammadShaker** [comment]
Hello, 
Any update about this issue.
Thanks.

**Comment by sksamuel** [comment]
That's what the [sbt-plugin](https://github.com/sksamuel/sbt-avro4s) does yes.

**Comment by KamalKang** [comment]
Hi,
I am using sbt-plugin to generate case classes but looks like case classes are loosing default values from schema. Is it not supported? 
Thanks.

**Comment by tunesmith** [comment]
I've also noticed the sbt-avro4s plugin does not specify default parameter values for case classes. I'm not sure if that would be considered a bug for this repo or that one.

**Comment by sksamuel** [comment]
I'd say the other one.
