### ISSUE TITLE
NPE when writing Option of sealed trait hierarchy of case objects

### ISSUE THREAD

**Issue by jangoolie** [sksamuel/avro4s#135]
This test demonstrates the issue:
```scala

sealed trait EnumThing
case object Thing extends EnumThing
case object Thang extends EnumThing
case class MaybeEnumThing(eo: Option[EnumThing])

...

"be able to write a non-null union of an enum and null" in {
  val fmt = RecordFormat[MaybeEnumThing]

  val met0 = MaybeEnumThing(Some(Thing))
  val baos = new ByteArrayOutputStream()
  val output = AvroOutputStream.binary[MaybeEnumThing](baos)
  output.write(met0) //<------ Throws a NullPointerException
  output.close()

  val is = AvroInputStream.binary[MaybeEnumThing](baos.toByteArray)
  val met1 = is.iterator.toList.head
  is.close()

  met0 shouldEqual met1
}   
```
Causes a NPE to be thrown (stack trace below).

Note that 
```scala
val met0 = MaybeEnumThing(None)
``` 
Works fine. So this bug only manifests when writing a non-null value to a union of null and Enum.

[info] - should be able to write a non-null union of an enum and null *** FAILED ***
[info]   java.lang.NullPointerException: null of union in field eo of com.sksamuel.avro4s.MaybeEnumThing
[info]   at org.apache.avro.generic.GenericDatumWriter.npe(GenericDatumWriter.java:132)
[info]   at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:126)
[info]   at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73)
[info]   at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:60)
[info]   at com.sksamuel.avro4s.AvroBinaryOutputStream.write(AvroOutputStream.scala:32)
[info]   at com.sksamuel.avro4s.AvroBinaryTest.$anonfun$new$5(AvroBinaryTest.scala:72)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
[info]   Cause: java.lang.NullPointerException:
[info]   at org.apache.avro.generic.GenericData.getSchemaName(GenericData.java:720)
[info]   at org.apache.avro.generic.GenericData.resolveUnion(GenericData.java:706)
[info]   at org.apache.avro.generic.GenericDatumWriter.resolveUnion(GenericDatumWriter.java:192)
[info]   at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:110)
[info]   at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73)
[info]   at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:153)
[info]   at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:143)
[info]   at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:105)
[info]   at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73)
[info]   at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:60)

**Comment by aspic** [comment]
I'm hitting a similar issue when generating a schema of Option[Enum], for example:
```
{
  "type": "record",
  "name": "UnionEnum",
  "namespace": "com.sksamuel.avro4s",
  "fields": [
    {
      "name": "wine",
      "type": [
        "null",
        {
          "type": "enum",
          "name": "Wine",
          "symbols": [ "Malbec", "Shiraz", "CabSav", "Merlot" ]
        }
      ]
    }
  ]
}
```

**Comment by phderome** [comment]
I think any Scala type that nests a type that ultimately maps via Avro4s to a Avro union (see avro4s type mappings) does not work. I'd guess Option[Option[T]] does not work, nor Option[Sealed Trait], Option[Enum] as mentioned by jangoolie and aspic.

**Comment by svroonland** [comment]
I'm running into the same issue. I saw that although there is a `ToValue` and `FromValue` for scala enumerations, there is no `ToSchema`. It looks like they are only supported as fields of case classes. Is this intended or perhaps an oversight?

I gave it a try to write my own `ToSchema` for scala enumerations, but cannot get the type signature quite right unfortunately.

**Comment by svroonland** [comment]
I'm running into the same issue. I saw that although there is a `ToValue` and `FromValue` for scala enumerations, there is no `ToSchema`. It looks like they are only supported as fields of case classes. Is this intended or perhaps an oversight?

I gave it a try to write my own `ToSchema` for scala enumerations, but cannot get the type signature quite right unfortunately.

**Comment by svroonland** [comment]
Managed to get it to work eventually. I submitted a PR two weeks ago. Can someone pick it up for the next release?

**Comment by sksamuel** [comment]
In release 1.8.2
