### ISSUE TITLE
Schema evolution 

### ISSUE THREAD

**Issue by MansurAshraf** [sksamuel/avro4s#138]
Hello,

I have a quick question on Schema evolution using Avro4s. Lets say I have a `Case Class` that I am serializing to Binary Avro (without Schema) and saving to a DB. Lets say in future I add a new field to the case class, would I still be able to deserialize the old data from DB?

**Comment by ogirardot** [comment]
Usually (avro4s or not) you'd need to some kind of identifier, the way the schema-registry of Confluent works is that they add a few bytes to an Avro payload to identify the "writer's schema" and then define the "reader's schema" to handle the schema evolution.
It is the way avro handles its schema evolution, Avro4s will not do "better" on this as you need the  writer's schema anyway.

c.f. https://github.com/sksamuel/avro4s/issues/70

**Comment by tunesmith** [comment]
PR #131 added a way to specify both the writer schema and the reader schema when deserializing, using a builder pattern (assuming the payload has the schema identifier for the writer). It's probably worth adding this to the top-level documentation.

**Comment by sksamuel** [comment]
You would need to include the reader schema, and that would have to define a default value for the new field.
