### ISSUE TITLE
Order by context level avro schemas

### ISSUE THREAD

**Issue by Antwnis** [sksamuel/avro4s#14]
Currently when transforming a JSON into Avro i.e. using https://www.landoop.com/tools/avro-scala-generator the order is type -> name -> namespace

    {
      "type" : "record",
      "name" : "MyClass",
      "namespace" : "com.test.avro",

It would be more formal and give you a top down understanding if avro4s ordered avro schemas in contextual order i.e.

    {
      "namespace" : "com.test.avro",
      "name" : "MyClass",
      "type" : "record",

**Comment by sksamuel** [comment]
I agree but this is the way avro itself generates the output, so short of writing my own schema marshaller, we're stuck.
