### ISSUE TITLE
Schema Evolution Proposal

### ISSUE THREAD

**Issue by briantopping** [sksamuel/avro4s#149]
Hi all, I am looking at Avro for schema evolution so of course I am looking at avro4s. In looking through tickets on this subject, I see various related issues and one statement from @sksamuel that it's not supported.

From what I understand of Avro, #130 would resolve the issue in that the API can now accept a reader and writer schema but that the application would have to manage these. 

It seems like it wouldn't be a stretch to have the classes that are generated by sbt-avro4s include the schema that they were generated from. This makes the reader schema available. The writer schema would be available from the serialized data being read. 

I played around a little bit with the module generator and was able to get about this far:

```
package com.example.avro

//auto generated code by avro4s
case class Event(
  id: shapeless.:+:[Long, shapeless.CNil],
  ...
) extends com.sksamuel.avro4s.SchemaBinding {
  override def schema: Option[org.apache.avro.Schema] = ???
}
```

In my concept, this `com.sksamuel.avro4s.SchemaBinding` is just a trait that would be checked on deserialization using a `ClassTag`. If the implementation existed and returned a `Schema`, that would be used as the reader schema. The missing implementation would lazily generate the `Schema` from the `.avsc` on the classpath.

As I got into it on the SBT side, the `File` object is lost pretty early in the process and pushing it down to the generator had a lot of code smell. 

As for the library side, I didn't bother with any implementation after getting in the weeds with the generator.

Thoughts?

**Comment by phderome** [comment]
If you are still active on this, I'd love to hear more about it.

**Comment by briantopping** [comment]
I haven't been, but I do need to get active on a permanent serialization format. Part of this ticket was a share a brain dump in case I didn't get very far, part because I don't know if it's damaged goods or a realistic approach.

**Comment by tunesmith** [comment]
Just to add clarity (since finding this issue confused me), PR #131 did add schema evolution support to avro4s (by allowing the user to use a builder pattern to specify both writer schema and reader schema while deserializing). This proposal appears to be about optionally adding support to include the writer schema into the avro4s-generated classes.
