### ISSUE TITLE
Add capability for scala ~> avro schema  

### ISSUE THREAD

**Issue by Antwnis** [sksamuel/avro4s#15]
Let's say i have a scala case class

    package mypackge
    case class MyClass(
      foo: Seq[Boolean]
    )

And i want to quickly generate the appropriate Avro schema for the class above, and perform that in `run-time` so that an external UI can be build around it to allow easy (scala case) ~> (avro-schema) conversions

**Comment by sksamuel** [comment]
Do you want to be able to do this in Scala itself. Like
SchemaGenerator.fromClass("code here")

**Comment by Antwnis** [comment]
Excactly

**Comment by Antwnis** [comment]
+1

**Comment by sksamuel** [comment]
This is very hard :)

**Comment by Antwnis** [comment]
Give me an alternative :-)

java -jar xxxxx FileWithScala.scala -o FileWithScala_{UID}.avro

**Comment by sksamuel** [comment]
Put your scala code into a scala project file and do

val schema = AvroSchema[MyType]

**Comment by Antwnis** [comment]
So i can prob use sbt ?

Build a tiny project with an sbt and just >> the scala file into a file and
`sbt something` ?

**Comment by sksamuel** [comment]
sbt run

**Comment by referentiallytransparent** [comment]
Hey @sksamuel will this generate AVDL or the JSON variant?

**Comment by sksamuel** [comment]
Jso

**Comment by Daenyth** [comment]
Is there an example project showing how to do this? It's not clear to me exactly what to put where, or what project you'd `sbt run` in
