### ISSUE TITLE
Array[Byte] does not properly deserialize in Either or Coproduct

### ISSUE THREAD

**Issue by atokarev-cleverdata** [sksamuel/avro4s#157]
Suppose, we have the following code:

```
case class Sample(key: String, value: Int Either Array[Byte])

val sample = Sample("key", Right("value".getBytes))

val baos = new ByteArrayOutputStream()
val os = AvroOutputStream.binary[Sample](baos)
os.write(sample)
os.close()

val bytes = baos.toByteArray

val is = AvroInputStream.binary[Sample](bytes)
val deserializedSample = is.iterator().next()
```

This gives us a RuntimeException on the last line:

`java.lang.RuntimeException: Value java.nio.HeapByteBuffer[pos=0 lim=5 cap=5] of type class java.nio.HeapByteBuffer is not compatible with [value]`

The same exception is risen when we use shapeless Coproduct instead of Either.

**Comment by sksamuel** [comment]
Fixed in 1.8.2
