### ISSUE TITLE
How to map avro field to a class field with different name

### ISSUE THREAD

**Issue by jrom93** [sksamuel/avro4s#159]
Hello,

I have an avro field called "type". However I can't use the same field name in my class because it is a reserved word. Is there a way to map it to a different field in my class (e.g "_type").

In Apache Avro™ 1.8.2, there is an annotation called "AvroName" that could accomplish this. Is there something similar I can use?

**Comment by sksamuel** [comment]
We could add an AvroName annotation.

**Comment by sksamuel** [comment]
Added in master.
