### ISSUE TITLE
Default values are not created for structures

### ISSUE THREAD

**Issue by bashan** [sksamuel/avro4s#163]
It seems like when creating AVRO scheme, the default values are not created under certain cases.

**Scenario:**
1. Create a case class with few properties and add another cases class with few properties to it.
2. Add to both main case class and inner case class some default values.
3. Generate AVRO scheme.
4. Scheme is generated properly with default values.
5. Add a Seq of string to the inner case class.
6. Generate AVRO scheme.
7. Scheme is generated without default values for the inner case class. the main case class has proper default values.

**Comment by YuvalItzchakov** [comment]
@bashan Can you post a minimal, compiling reproduce of the problem? I can't seem to reproduce it.

For example:

```scala
case class Inner(d: Double = 2.0, str: String = "Foo", seq: List[String])
case class Out(i: Int = 42, inner: Inner)
```

Yields:

```json
{
  "type" : "record",
  "name" : "Out",
  "namespace" : "com.sksamuel.avro4s",
  "fields" : [ {
    "name" : "i",
    "type" : "int",
    "default" : 42
  }, {
    "name" : "inner",
    "type" : {
      "type" : "record",
      "name" : "Inner",
      "fields" : [ {
        "name" : "d",
        "type" : "double",
        "default" : 2.0
      }, {
        "name" : "str",
        "type" : "string",
        "default" : "Foo"
      }, {
        "name" : "seq",
        "type" : {
          "type" : "array",
          "items" : "string"
        }
      } ]
    }
  } ]
}
```

**Comment by sksamuel** [comment]
I think we can consider this closed unless a failing example is provided.
