### ISSUE TITLE
Read only part of the avro message ?

### ISSUE THREAD

**Issue by flavianh** [sksamuel/avro4s#164]
I have a data structure similar to this one:

```scala
case class Metadata(mdContent1: String, mdContent2: Long);
case class Data(md: Metadata, data: String)
```

and I serialize Data in avro.

Is is possible to deserialize only the Metadata part?

**Comment by sksamuel** [comment]
Can you just call serialize on the md field?

**Comment by sksamuel** [comment]
At the moment no, you would need to deserialize all and then just select the field you wanted.

**Comment by flavianh** [comment]
@sksamuel Thanks, would be a nice feature IMO
