### ISSUE TITLE
could not find implicit value for evidence parameter of type com.sksamuel.avro4s.FromRecord

### ISSUE THREAD

**Issue by krullgit** [sksamuel/avro4s#165]
Hi,
I'm sure to just beeing stupid but I get the following error with that simple code example.
(I read about others here having missing implicit values, but nothing fits for me :( )

`case class coocMap(map: Map[String, Int])`
`//implicit val fromRecord = FromRecord[coocMap]`
`val schema = AvroSchema[coocMap]`
`val is = AvroInputStream.data[coocMap](new File("pizzas.avro"))`
`val pizzas = is.iterator.toSet`
`is.close()`

`Error:(291, 43) not enough arguments for method data: (implicit evidence$32: com.sksamuel.avro4s.FromRecord[coocMap])com.sksamuel.avro4s.AvroDataInputStream[coocMap].`
`Unspecified value parameter evidence$32.
    val is = AvroInputStream.data[coocMap](new File("pizzas.avro"))`

When I try 
`implicit val fromRecord = FromRecord[coocMap]`
the error canges to 
`Error:(289, 41) not found: value <none>
    implicit val fromRecord = FromRecord[coocMap]`

Could anybody help please ?

**Comment by ShardPhoenix** [comment]
Apparently the case class needs to be defined outside the class doing the serializing.

**Comment by sksamuel** [comment]
Yes, don't put case classes inside methods or blocks. They can be nested inside other classes through but there must be a static path to them.
