### ISSUE TITLE
Use with Akka streams and Kafka

### ISSUE THREAD

**Issue by darrenleeweber** [sksamuel/avro4s#166]
The README example includes various serializer examples.  Do you have additional examples, esp. any examples of serializing in the context of other frameworks that work with avro?  Understood if this is considered out of scope for documentation here in this project.
- in an Akka actor system?
  - e.g. https://github.com/hopped/akka-avro-serializer/
- for a Kafka producer/consumer
  - https://dzone.com/articles/kafka-avro-scala-example
    - uses an `Array[Byte]` for a producer
    - like https://github.com/sksamuel/avro4s#binary-serializing
- in a Spark context

**Comment by tunesmith** [comment]
I wrote an example of using Avro schema evolution (with avro4s) using Akka Persistence:

https://github.com/Keenworks/akka-avro-evolution

**Comment by sksamuel** [comment]
I'm going to close this because I don't want to get involved in kafka or spark in this repo. I will be writing a project shortly that will combine this and kafka.
