### ISSUE TITLE
Evolution for binary and json

### ISSUE THREAD

**Issue by IntelligyScience** [sksamuel/avro4s#172]
Hi, 
I also tried to get help on StackOverflow (https://stackoverflow.com/questions/48507094/how-to-add-evoltion-to-avro4s-in-binary-serialized-data)

Their is still no solution. :(

I changed all from binary to json, but still the same issue. In the moment I change the old class and add a new field (of course with default value) the deserialize process failed!

Is their now a solution, is this a bug or a missing feature? I don´t know.
Thanks for any help

**Comment by IntelligyScience** [comment]
Not for the SurveyTemplate class. Fot the chapter (because it is recursive) I created an implicit schema with SchemaFor. What should I do to test it?

**Comment by sksamuel** [comment]
Without a reader schema it won't evolve. I suppose it is undefined what should happen if you have a scala default value instead of an avro one. Should the decoder take the default from the constructor, or should it throw an error.

**Comment by sksamuel** [comment]
Let's track this in #202.
