### ISSUE TITLE
Can't deserialize Optional AvroFixed types

### ISSUE THREAD

**Issue by ShardPhoenix** [sksamuel/avro4s#174]
Found a possible bug (using 1.8.2). When a class includes an AvroFixed type which is Optional, it can't be deserialized.

Example:

in my .avdl: 

    fixed Bytes16(16);

in sbt-avro4s generated classes:

    @com.sksamuel.avro4s.AvroFixed(16)
    case class Bytes16(bytes: scala.collection.mutable.WrappedArray.ofByte) extends AnyVal

my class (simplified example):

    case class RequestStructV1(sessionId: Option[Bytes16])

Deserialize method:
```
  def deserialize[T: SchemaFor: FromRecord](bytes: Array[Byte]): Option[T] = {
    val in = new ByteArrayInputStream(bytes)
    val input = AvroInputStream.binary[T](in)
    input.iterator.toSeq.headOption
  }
```

When attempting to compile a call like `val deserialized = serializer.deserialize[RequestStructV1](bytes)`, I get an error like `could not find implicit value for evidence parameter of type com.sksamuel.avro4s.FromRecord[RequestStructV1]`. However, it works fine if the Bytes16 is not an Option, and Option works fine for other values like Strings.

**Comment by YuvalItzchakov** [comment]
@sksamuel The problem here stems from the fact `WrappedArray.ofXXX` aren't supported, meaning they have no `FromRecord` and `ToRecord` instances. I have been working on a fix for this, but I've thought about it and I'm not sure whether this should or should not be supported?

@ShardPhoenix As a wordaround, changing `WrappedArray.ofByte` to `Array[Byte]` fixes the problem.

**Comment by ShardPhoenix** [comment]
@YuvalItzchakov Ideally, whatever sbt-avro4s generates should work with this lib.

**Comment by YuvalItzchakov** [comment]
@ShardPhoenix I agree. Question is, should this be changed in sbt-avro4s or here?

**Comment by ShardPhoenix** [comment]
I don't know what is correct, getting bitten by this again though :(

**Comment by sksamuel** [comment]
I think we should change sbt-avro4s.
