### ISSUE TITLE
Can't serialize Optional Enums

### ISSUE THREAD

**Issue by ShardPhoenix** [sksamuel/avro4s#175]
In my .avdl I have the following:

```
  enum SalaryTypeEnum {
    ANNUAL,
    MONTHLY,
    HOURLY
  }
```
```
record MyRecord {
    union {null, SalaryTypeEnum} salaryType = null;
  }
```

with sbt-avro4s this generates:
```
case class MyRecord(salaryType: Option[SalaryTypeEnum])
```
plus the Java enum for SalaryTypeEnum.

Serialization method:
```
 def serialize[T: SchemaFor : ToRecord](avroValue: T): Array[Byte] = {
    val baos = new ByteArrayOutputStream()
    val avroOutput = AvroOutputStream.binary[T](baos)
    avroOutput.write(avroValue)
    avroOutput.close()
    baos.toByteArray
  }
```

The following call is attempted:
```
val avro = MyRecord(Some(SalaryTypeEnum.ANNUAL))
val bytes = serializer.serialize[MyRecord](avro)
```

The results in the error `java.lang.NullPointerException: null of union in field enum of MyRecord  at org.apache.avro.generic.GenericDatumWriter.npe(GenericDatumWriter.java:145)`

If the enum is not optional, it works fine.

**Comment by ShardPhoenix** [comment]
Note: This issue was said to be fixed in https://github.com/sksamuel/avro4s/issues/135, for version 1.8.2, but I'm using 1.8.2 and still running into it.

**Comment by sksamuel** [comment]
Fixed in 1.8.3 which I'm releasing now.

**Comment by sksamuel** [comment]
Here is the fix if you're interested.
https://github.com/sksamuel/avro4s/commit/61fbfe80dfa82e0788b76adb49002fae70508491

**Comment by ShardPhoenix** [comment]
Thanks for the quick fix!
