### ISSUE TITLE
Support aliases for named types

### ISSUE THREAD

**Issue by TJSomething** [sksamuel/avro4s#177]
According to the spec, all named types support aliases. In order to accommodate this, it would make sense if the `AvroAlias` annotation worked on case classes, Java enums, and sealed traits with only case objects. This would allow me to have a migration path if I need to refactor a type to have a different name or namespace.

**Comment by sksamuel** [comment]
Lets track this in #202

**Comment by sergey-kalin** [comment]
Hey @sksamuel,

Could it be please reopened. Ticket https://github.com/sksamuel/avro4s/issues/202 mainly about fields renamed aspect of schema evolution. 
As per current state `aliases` seem only works for case classes, but not for sealed traits (scala enumeration)

Small snippet to reproduce based on `com.sksamuel.avro4s.schema.AvroAliasSchemaTest`

```
@AvroAlias("aliasDoesntWork")
sealed trait MyScalaEnum

object MyScalaEnum {
  @AvroDoc("Some desc")
  case object CaseObjectOne extends MyScalaEnum
}

@AvroAlias("aliasThatWorks")
case class Annotated(str: MyScalaEnum)

val schema = AvroSchema[Annotated]
println(schema.toString(true))
```

would render `enum` type without `aliases` declaration

```
{
  "type" : "record",
  "name" : "Annotated",
  "namespace" : "com.sksamuel.avro4s.schema.AvroAliasSchemaTest",
  "fields" : [ {
    "name" : "str",
    "type" : {
      "type" : "enum",
      "name" : "MyScalaEnum",
      "namespace" : "com.sksamuel.avro4s.schema",
      "symbols" : [ "CaseObjectOne" ]
      // <---- no aliases for enumeration named type here!!!
    }
  } ],
  "aliases" : [ "aliasThatWorks" ]
}
```

**Comment by sergey-kalin** [comment]
Moreover, neither `@AvroDoc` nor `@AvroProp` works for sealed traits, as per codebase there seem no annotation processing except of default value
