### ISSUE TITLE
Support Maps with Keys other than String

### ISSUE THREAD

**Issue by bellemare** [sksamuel/avro4s#181]
It seems to me that I can only get Maps working when the Key is a String.

These don't work:
`case class UserData(map: Map[Long, Long])`
`case class UserData(map: Map[Int, Long])`
`case class UserData(map: Map[Boolean, Long])`
`case class UserData(map: Map[Double, Long])`
`case class UserData(map: Map[Float, Long])`

The error:
`could not find implicit value for evidence parameter of type com.sksamuel.avro4s.FromRecord[my.namespace.to.UserData]`

This does work:
`case class UserData(map: Map[String, Long])`

I have some use cases where it would be great to use just an Int or a Long as the Key, as my maps will be large enough (hundreds of entries * millions of users). It would save a lot of the network IO as the data is written back and forth from Kafka.

I poked around in the code and found this in FromRecord.scala
`
  implicit def MapFromValue[T](implicit fromvalue: FromValue[T]): FromValue[Map[String, T]] = new FromValue[Map[String, T]] {
    override def apply(value: Any, field: Field): Map[String, T] = value match {
      case map: java.util.Map[_, _] => map.asScala.toMap.map { case (k, v) => k.toString -> fromvalue(v) }
      case other => sys.error("Unsupported map " + other)
    }
  }
`
And ToRecord.scala
`  implicit def MapToValue[T](implicit tovalue: ToValue[T]) = new ToValue[Map[String, T]] {
    override def apply(value: Map[String, T]): java.util.Map[String, T] = {
      value.mapValues(tovalue.apply).asInstanceOf[Map[String, T]].asJava
    }
}`
It indeed looks like it is hardwired just for Strings. Is there a technical reason why we can't support different values for Keys, or was it just a design simplification?

**Comment by sksamuel** [comment]
Unfortunately Avro only supports maps where the keys are strings.
https://avro.apache.org/docs/1.8.2/spec.html#Maps

**Comment by bellemare** [comment]
Huh, well, TIL . Thanks @sksamuel
