### ISSUE TITLE
AvroDoc annotation for value classes

### ISSUE THREAD

**Issue by maxkorolev** [sksamuel/avro4s#182]
Hi, thank you for this project.
I didn't get how I can make doc annotation for value class.
This works good

```
case class Meter(value: Int) extends AnyVal
case class House(@AvroDoc("This is a length") length: Meter)
```

But this doesn't

```
@AvroDoc("This is a length")
case class Meter(value: Int) extends AnyVal
case class House(length: Meter)
```

**Comment by maxkorolev** [comment]
Is it possible to make it somehow with help of typeclasses?
That would be great if It was possible to write something like this

```
case class Meter(value: Int) extends AnyVal
case class House(length: Meter)
object Meter {
    implicit val meterDoc = new AvroDoc[Meter]("This is a length")
}
```

**Comment by YuvalItzchakov** [comment]
According to the [Avro specification for primitive types](http://avro.apache.org/docs/current/spec.html#schema_primitive): 

> Primitive types have no specified attributes.

By that definition, and by the fact that `Meter` is actually an `Int` in the generated byte code, I think the case of generating a doc for it may be invalid.

**Comment by sksamuel** [comment]
We could possibly pick up the annotations and add them to fields when the value type is used inside a record type, but as @YuvalItzchakov says, you can't use them if the value type is top level.

**Comment by sksamuel** [comment]
In 2.0 you can now define annotations on value classes and they will be used as if they were defined on fields.
