### ISSUE TITLE
RecordFormat.to(): SpecificRecord???

### ISSUE THREAD

**Issue by MarkRBM** [sksamuel/avro4s#183]
So I can see how to use `RecordFormat` to create a `org.apache.avro.generic.GenericRecord`

and I can see how to create a T from a GenericRecord with `RecordFormat`

Can this library turn a T in a `org.apache.avro.generic.SpecificRecord` and vice versa? If not is there some technical challenge stopping that from being a feature of this library?

**Comment by sksamuel** [comment]
I suppose we can make our own container object which implements both `SpecificRecord` and `GenericRecord` rather than using the `GenericData.Record` class. Unless you were referring to the `SpecificRecordBase` class?

**Comment by sksamuel** [comment]
In 2.0.0-M3 `RecordFormat` now generates an instance of `ImmutableRecord` which is both a `GenericRecord` and a `SpecificRecord` since they are both just interfaces. Do you want to give it a go and report back if it works for you.

**Comment by sksamuel** [comment]
2.0.0 is now released with this supported, so closing this ticket.
