### ISSUE TITLE
Can't import the naming strategy object into Java

### ISSUE THREAD

**Issue by keerthivasan-r** [sksamuel/avro4s#186]
Hi, I'm trying to make of this library in Java application. I got the maven dependency 
```
	<dependency>
			<groupId>com.sksamuel.avro4s</groupId>
			<artifactId>avro4s-json_2.12</artifactId>
			<version>1.8.3</version>
		</dependency>
```
I'm not able to figure out creating an instance of 

`JsonToAvroConverter converter = new JsonToAvroConverter("com.test.schema", false, <namingstrategy_instance>);`

I have to pass the `NamingStrategy` instance as a third argument to the constructor. Can someone guide me here? BTW, I'm a newbie to scala. Thanks for the help

**Comment by sksamuel** [comment]
Do you have real code, what are you using for the third argument?
