### ISSUE TITLE
private val converters in <$anon: com.sksamuel.avro4s.ToRecord[Foo]> is never used

### ISSUE THREAD

**Issue by david-mcgillicuddy-ovo** [sksamuel/avro4s#189]
When running with fatal warnings and unused-privates I get the following error:
```
[error] /Users/davidmcgillicuddy/work/evse-simple-scheduler/src/main/scala/com/ovoenergy/evse/scheduler/DeviceSink.scala:38:54: private val converters in <$anon: com.sksamuel.avro4s.ToRecord[com.ovoenergy.evse.schedule.v1.Idle]> is never used
[error]         avroBinarySchemaIdSerializer[ScheduleMessage](schemaRegistryClient, isKey = false, includesFormatByte = true)
[error]                                                      ^
```
which seems to be caused by the fact that not all cases in the if statement in `puts` actually use the `converters`: https://github.com/sksamuel/avro4s/blob/a04baa577086cdba49921ec494e583da35325c21/avro4s-macros/src/main/scala/com/sksamuel/avro4s/ToRecord.scala#L214

`Foo` in this case is just: `case class Foo()`.

It's quite similar to https://github.com/sksamuel/avro4s/issues/125 in the issues that it causes.
The fix seems to be to only generate the `converters` val if it's required, if I get a chance I'll give it a go.

**Comment by sksamuel** [comment]
Fixed in the 2.0 build.
