### ISSUE TITLE
How to use Avro4s to create generic KafkaDecoder for Spark streaming

### ISSUE THREAD

**Issue by vladap** [sksamuel/avro4s#19]
I would like to use your great work but I'm stuck with my limited knowledge of Scala to solve the following problem. I know you possible don't know Kafka and Spark but it is more about reflection and context bounds.

RecordFormat[T] requires fromRecord and toRecord implicit values. Spark KafkaDirectStream takes Kafka Decoder type and creates instance of it via reflection looking for a single argument constructor. When fromRecord and toRecord are provided in decoder implementation via context bounds or as implicit values in separate parameter list compiler add them to constructor as additional arguments breaking the required contract.

Does anybody know how to provide these implicits in KafkaAvroGenericDecoder shown below so that RecordFormat is satisfied without breaking Spark code?

Goal is to let avro4s generate decoding from Avro GenericRecord to case class using Confluent Schema Registry.

Spark code to satisfy, VD is Decoder type and V is resulting case class, Decoder is interface defined by Kafka:
```scala
val valueDecoder = classTag[VD].runtimeClass.getConstructor(classOf[VerifiableProperties])
  .newInstance(props)
  .asInstanceOf[Decoder[V]]
```

The code I currently have, context bounds removed:

```scala
class KafkaAvroGenericDecoder[T]
  extends AbstractKafkaAvroDeserializer
  with Decoder[T] {

  def this(schemaRegistry: SchemaRegistryClient) = {
    this()
    this.schemaRegistry = schemaRegistry
  }

  def this(schemaRegistry: SchemaRegistryClient, props: VerifiableProperties) = {
    this(schemaRegistry)
    configure(deserializerConfig(props))
  }

  /** Constructor used by Kafka consumer */
  def this(props: VerifiableProperties) = {
    this()
    configure(new KafkaAvroDeserializerConfig(props.props))
  }

  override def fromBytes(bytes: Array[Byte]): T = {
    val record = deserialize(bytes).asInstanceOf[GenericRecord]
    val format = RecordFormat[T]
    format.from(record)
  }
}

object Kafka {
  def createStream[V : ClassTag](topics: Set[String])
    (implicit ssc: StreamingContext): InputDStream[(Array[Byte], V)] = {
  
    KafkaUtils.createDirectStream[Array[Byte], V, DefaultDecoder, KafkaAvroGenericDecoder[V]](
      ssc, session.kafkaConf, topics)

    // Or this one for test. Change return type to InputDStream[Array[Byte]]
    // createTestStream[V, KafkaAvroGenericDecoder[V]](ssc):
  }

  // just to print out list of constructors for decoder and try to create its instance
  private def createTestStream[V, VD : ClassTag](ssc: StreamingContext): InputDStream[Array[Byte]] = {
     val props = new Properties()
     props.put("bootstrap.servers", "localhost:9092")
     props.put("group.id", "test")
     props.put("schema.registry.url", "http://localhost:8989")
     props.put("partition.assignment.strategy", "range")
   
     classTag[VD].runtimeClass.getConstructors.foreach { x =>
       println("CONSTRUCTOR INFO: " + x)
     }

     val valueDecoder = classTag[VD].runtimeClass.getConstructor(classOf[VerifiableProperties])
       .newInstance(new VerifiableProperties(props))
       .asInstanceOf[Decoder[V]]

     val seq = Seq("k1".getBytes, "k2".getBytes, "k3".getBytes)
     val rdd = ssc.sparkContext.makeRDD(seq)

     new ConstantInputDStream(ssc, rdd)
    }
  }
}

// user code
object Streamz {
  def run()(implicit ssc: StreamingContext): Unit = {
    val topics = Set("test")
    val stream = Kafka.createStream[MyFancyEvent](topics)
    val result = stream.count()
    result.print()
  }
}
```
With context bounds:
```scala
class KafkaAvroGenericDecoder[T : FromRecord : ToRecord]
  extends AbstractKafkaAvroDeserializer
  with Decoder[T] { ... }

object Kafka {
  def createStream[V : FromRecord : ToRecord : ClassTag](topics: Set[String]) { ... }
}
```

Many thanks for any advice,
Vladimir

**Comment by sksamuel** [comment]
This is a great question. If my answer is acceptable would you mind creating a PR to add a "how to use avro4s with kafka schema registry" so that others can benefit ?

**Comment by sksamuel** [comment]
So, your basic requirement is you need a constructor that matches what kafka expects, which is the single arg `VerifiableProperties`. Avro4s needs two parameters, `SchemaFor` and `ToRecord`, both of which are generated by the compiler at compile time, so runtime reflection is out. Ideally we could do this:

```scala
class Decoder[V: SchemaFor: ToRecord](props: VerifiableProperties)
```

But we can't because that ends up generating a constructor like:

`public com.sksamuel.avro4s.Decoder(VerifiableProperties,com.sksamuel.avro4s.SchemaFor,com.sksamuel.avro4s.ToRecord)`

Ie, the implicit parameters are added to the constructor so that it works on the JVM. As far as I am aware there is no way to do what you want directly via constructors. So the best I could come up with was having the implicit values set explicitly via a method, which we can invoke in turn from a factory method. It looks a bit noddy with the vars, but it works.

```scala
case class Foo(name: String, count: Int)

object TestMe extends App {
  val decoder = Decoder[Foo]
  val record = decoder.decode(Foo("sammy", 1234))
  println(record)
}

class Decoder[V] {

  implicit var schemaFor: SchemaFor[V] = null
  implicit var toRecord: ToRecord[V] = null

  def populate(schemaFor: SchemaFor[V], toRecord: ToRecord[V]): Unit = {
    this.schemaFor = schemaFor
    this.toRecord = toRecord
  }

  // change this to match kafka
  def this(moo: String) {
    this()
  }

  def decode(v: V): Unit = {
    println(toRecord(v))
  }
}

// the factory method here will set up the class properly
object Decoder {
  def apply[V](implicit schemaFor: SchemaFor[V], toRecord: ToRecord[V]): Decoder[V] = {
    val decoder = new Decoder[V]
    decoder.populate(schemaFor, toRecord)
    decoder
  }
}
```

**Comment by vladap** [comment]
Yeah, there is no way how to do it via constructors, implicits have to be set manually. Your approach seems reasonable. I will try it with SchemaRegistry and once I end up with a working solution I will do the PR.

**Comment by vladap** [comment]
The other approach could be to update Spark Kafka streaming code so that it would support Scala Kafka decoders with arbitrary context bounds so that avro4s would supported out of the box. Though I don't have many experience with Scala reflection to achieve it at this point in my learning curve. But it would interesting to find out if Scala is capable of it.

This is the block of code which would have to be changed, probably if it wouldn't succeed to find single arg constructor try some Scala magic:)

https://github.com/apache/spark/blob/master/external/kafka/src/main/scala/org/apache/spark/streaming/kafka/KafkaRDD.scala#L150

**Comment by vladap** [comment]
BTW. Thanks a lot for your suggestion. I missed that in my previous answer.

**Comment by vladap** [comment]
I have reviewed your suggestion again and I don't understand how it is going to work because I don't send decoder instance to the underlying framework (Spark) but just the type. Spark never call my Decoder.apply[T], hence if I understand correctly they will end-up with an instance with shemaFor and toRecord still nulls. Or do I miss something?

Because Spark creates decoder instance than it seems Kafka has a method how to pass decoder instance instead of let it Kafka consumer to create it. I haven't used it yet, I was sending classes to its consumer/producer. It might require to change Spark interface so that I could pass down factory method which should be used to create decoder or whatever.

After this decoder has to be properly set. I never get its instance to my hands. Maybe there is Kafka API to get it and update it, I don't know but it would be hacky anyway.
```scala
val valueDecoder = classTag[VD].runtimeClass.getConstructor(classOf[VerifiableProperties])
  .newInstance(props)
  .asInstanceOf[Decoder[V]]
```

I could always use Kafka DefaultDecoder which returns bytes and do my own decoding in Spark Kafka stream messageHandler but I want to avoid this step and fully push down avro4s decoder to Spark in a way that user code doesn't have to create decoders and anything - just define what type (case class) the stream is and get stream of case classes back.

**Comment by vladap** [comment]
Your factory approach is still very useful I will try to come up with something even just for Kafka consumer /producer with SchemaRegistry.

**Comment by vladap** [comment]
> Avro4s needs two parameters, SchemaFor and ToRecord, both of which are generated by the compiler at compile time, so runtime reflection is out.

I assume you have meant and implied that Spark is out with its current implementation to instantiate decoders.

**Comment by sksamuel** [comment]
I don't know anything about spark and kafka. I mean I know spark, and I
know kafka, but I don't know what you're doing with them.

**Comment by vladap** [comment]
Nothing fancy, just to use avro4s to deserialize Avro based Kafka streams in Spark streaming and avoid having to write GenericRecord to case class mapping manually. As well as avoiding to define speacialized decoder for every custom case class - rather provide a typed factory method which can construct required decoder based on type. The API something like this (and its other variants):
```
createStream[K, V](topics, kafkaParams): InputDStream[(K, V)]
```
Where K is case class for Key and V is case class for Value in Kafka message.

Initially I wanted to write custom Kafka decoder so that it would be deserialized in one shot from bytes to my case class within Kafka decoder fromBytes method. But I give it up for now due to context bounds.

The second approach is to use existing KafkaAvroDecoder which returns Avro GenericRecord. Then  use avro4s to do the mapping from GenericRecord to case class in messageHandler function in createDirectStream in Spark Streaming:
https://github.com/apache/spark/blob/master/external/kafka/src/main/scala/org/apache/spark/streaming/kafka/KafkaUtils.scala#L407

The problem here is that avro4s FromRecord trait is not serializable. If I update avro4s library and make it to extend Serializable it works. But I don't think it is the right solution. Why should avro4s know about Spark requirements.

Kryo doesn't seem to help either because if I understand correctly it is a closure serialization in Spark and Spark only supports Java serialization for it.

Still trying to find the way how to avoid serialization.

**Comment by sksamuel** [comment]
Making something serializable is fine I think, it's a common enough
requireemnt.

**Comment by vladap** [comment]
While it is not a good idea to blindly spill Serialization everywhere I agree it is fine in this case.

**Comment by sksamuel** [comment]
1.4.1 will have ToRecord and FromRecord serializable.

**Comment by Antwnis** [comment]
That is a cool capability. 

Could you add some documentation / example of using it with spark-streaming ?

**Comment by wzorgdrager** [comment]
@sksamuel Are ToRecord and FromRecord already serializable? I'm currently struggling with this, since I am also working on a generic serializer for Flink & Kafka. However this serializer class needs to be serializable as well (since Flink sends it serialized to its workers), however ToRecord/FromRecord don't seem serializable.  

I get this (serialization) error: `Caused by: java.io.NotSerializableException: com.sksamuel.avro4s.FromValue$StringFromValue`

Using this code:
```scala
 def createKafkaSource[IN : ClassTag : SchemaFor : FromRecord]() : RichParallelSourceFunction[IN] = {
    //set some properties
    val properties = new Properties()
    properties.put("bootstrap.servers", "127.0.0.01:9092")
    properties.put("zookeeper.connect", "127.0.0.1:2181")

    new FlinkKafkaConsumer011[IN]("persons", AvroDeserializationSchema[IN], properties)
  }
```
