### ISSUE TITLE
Sealed trait schema generation don't work

### ISSUE THREAD

**Issue by tayvs** [sksamuel/avro4s#190]
Schema generation on sealed trait occur compilation error 
> Error:(9, 32) Could not find implicit SchemaFor[CustomerAction]
> val schema = AvroSchema[CustomerAction]

My code:
````
import com.sksamuel.avro4s.AvroSchema
import org.apache.avro.Schema

sealed trait CustomerAction
case class Click(link: String, customer: String = "avatar", time: Long = Long.MaxValue) extends CustomerAction
case class ShowImg(link: String, customer: String = "avatar") extends CustomerAction
case class DownloadFile(fileSource: String, customer: String = "avatar") extends CustomerAction

val schema = AvroSchema[CustomerAction]
schema.toString(true)
````

creating schema using "Schema .createUnion" work properly

code with Schema.createUnion:
```
Schema
  .createUnion(AvroSchema[Click], AvroSchema[DownloadFile], AvroSchema[ShowImg])
```

and schema generated by this code:

> [ {
>   "type" : "record",
>   "name" : "Click",
>   "namespace" : "namespace",
>   "fields" : [ {
>     "name" : "link",
>     "type" : "string"
>   }, {
>     "name" : "customer",
>     "type" : "string",
>     "default" : "avatar"
>   }, {
>     "name" : "time",
>     "type" : "long",
>     "default" : 9223372036854775807
>   } ]
> }, {
>   "type" : "record",
>   "name" : "DownloadFile",
>   "namespace" : "namespace",
>   "fields" : [ {
>     "name" : "fileSource",
>     "type" : "string"
>   }, {
>     "name" : "customer",
>     "type" : "string",
>     "default" : "avatar"
>   } ]
> }, {
>   "type" : "record",
>   "name" : "ShowImg",
>   "namespace" : "namespace",
>   "fields" : [ {
>     "name" : "link",
>     "type" : "string"
>   }, {
>     "name" : "customer",
>     "type" : "string",
>     "default" : "avatar"
>   } ]
> } ]

**Comment by 2chilled** [comment]
Should be fixed for Scala 2.12 in https://github.com/2chilled/avro4s

**Comment by RayRoestenburg** [comment]
I've seen the same issue, 'top-level' sealed trait ADT does not work, but a case class that has a property of a sealed trait does work:

So this does not work:
```
object MyMessages {
  sealed trait Foo
  case class Bar(id: String) extends Foo
  case class Baz(value: Int) extends Foo
}
```

And this does:
```
object MyMessages {
  case class MyFoo(foo: Foo)
  sealed trait Foo
  case class Bar(id: String) extends Foo
  case class Baz(value: Int) extends Foo
}
```

**Comment by sksamuel** [comment]
Top level sealed traits are now supported in 2.0.0+.
