### ISSUE TITLE
Converting data with an optional fixed type field to GenericRecord fails

### ISSUE THREAD

**Issue by ylabi** [sksamuel/avro4s#193]
I have a data structure with the following type:
```
case class Data(uuid: Option[UUID])

@com.sksamuel.avro4s.AvroFixed(16)
case class UUID(bytes: Array[Byte])
```

When converting an instance of my data structure to a GenericRecord, I get the following error:
```
18/04/27 11:03:00 ERROR Utils: Aborting task
org.apache.avro.AvroRuntimeException: Not a record schema: {"type":"fixed","name":"UUID","namespace":"com.company.ns","size":16}
	at org.apache.avro.generic.GenericData$Record.<init>(GenericData.java:181)
	.
	.
        at com.sksamuel.avro4s.LowPriorityToValue$$anon$2.apply(ToRecord.scala:30)
	at com.sksamuel.avro4s.LowPriorityToValue$$anon$2.apply(ToRecord.scala:29)
	at com.sksamuel.avro4s.ToValue$$anon$8$$anonfun$apply$5.apply(ToRecord.scala:109)
        at scala.Option.map(Option.scala:146)
	at com.sksamuel.avro4s.ToValue$$anon$8.apply(ToRecord.scala:109)
	at com.sksamuel.avro4s.ToValue$$anon$8.apply(ToRecord.scala:108)
```

Not sure how much this issue does overlap with [issue 174](https://github.com/sksamuel/avro4s/issues/174)

**Comment by ylabi** [comment]
@sksamuel any chance you can help troubleshooting this ?

**Comment by amanjpro** [comment]
I am not sure if it is about `Option` only, I think  any parameterized type if they have the annotation on the type-parameter itself, will fail, most likely due to this:

https://github.com/sksamuel/avro4s/blob/master/avro4s-macros/src/main/scala/com/sksamuel/avro4s/ToRecord.scala#L200

I believe we shouldn't only check for the presence of the annotation on the type itself, but on its type-parameter too.

Or maybe somehow turn the macro to recursively look for the annotation on each field

**Comment by sksamuel** [comment]
You could get rid of the UUID class and just have an Option of Array[Byte]. What's the extra wrapper giving here? Then you could annotate the field

case class Data(@AvroFixed(16) bytes: Array[Byte])

**Comment by amanjpro** [comment]
Imagine the case when you have multiple fields in Data, and one of them is optional and fixed. You will still face the same problem

**Comment by sksamuel** [comment]
Like,

```
case class Data(@AvroFixed(16) bytes1: Array[Byte], bytes2: Array[Byte]))
```

or something else ?

**Comment by ylabi** [comment]
@sksamuel it's not an option to get rid of the UUID class. The thing is we're operating on a legacy system and one of the constraints: the resulting schemas must not change.

**Comment by sksamuel** [comment]
@ylabi ok.

What about

```
case class Data(uuid: Option[UUID])
case class UUID(@com.sksamuel.avro4s.AvroFixed(16) bytes: Array[Byte])
```

**Comment by ylabi** [comment]
I run into these errors when doing that:

```
Error:(43, 45) could not find implicit value for evidence parameter of type com.sksamuel.avro4s.ToRecord[Data]
    val output = AvroOutputStream.data[Data](new File("data.avro"))
	
Error:(43, 45) not enough arguments for method data: (implicit evidence$13: com.sksamuel.avro4s.SchemaFor[Data], implicit evidence$14: com.sksamuel.avro4s.ToRecord[Data])com.sksamuel.avro4s.AvroDataOutputStream[Data].
Unspecified value parameter evidence$14.
    val output = AvroOutputStream.data[Data](new File("data.avro"))
```

For reference here's the code I ran:

```
import java.io.File
import com.sksamuel.avro4s._

case class Data(uuid: Option[UUID])
case class UUID(@AvroFixed(8) bytes: Array[Byte])

object Test extends App {
   val output = AvroOutputStream.data[Data](new File("data.avro"))
   output.write(Data(Some(UUID(Array(0, 1, 2, 3, 4, 5, 6, 7).map(_.toByte)))))
}

```

**Comment by sksamuel** [comment]
This works for me now in 2.0.0-M3. If you want to try and feed back to me that would be great.

**Comment by sksamuel** [comment]
I've added a test here to show your sample working:

https://github.com/sksamuel/avro4s/blob/master/avro4s-core/src/test/scala/com/sksamuel/avro4s/github/GithubIssue193.scala

**Comment by sksamuel** [comment]
2.0.0 is now released with this fixd, so closing this ticket.
