### ISSUE TITLE
Support for java.util.UUID?

### ISSUE THREAD

**Issue by tunesmith** [sksamuel/avro4s#198]
I see in https://github.com/sksamuel/avro4s/issues/22 that support for UUIDs was apparently added, but do I have to do anything special to take advantage of it? I have case class with a java.util.UUID field, but when I generate schema for it, it recognizes it as a String, and the class that the Schema generates defines the field as a String.

**Comment by tunesmith** [comment]
Thank you, I was confused on tooling. I can confirm it works great for me from avro4s. 

It's sbt-avro4s that was causing my problem. It creates a class where the field is String, not UUID. 

I stopped using sbt-avro4s in favor of using the programmer-maintained models. Should I create an sbt-avro4s bug for this or is that considered by design?

**Comment by sksamuel** [comment]
Yes I'd say this is an sbt-avro4s bug.

**Comment by sksamuel** [comment]
I've released 1.9.0 of avro4s which uses the UUID logical type. I'm making the appropriate changes in sbt-avro4s now.
