### ISSUE TITLE
10x slower than java serialization if avro4s is used as per the Readme.md

### ISSUE THREAD

**Issue by kostaskougios** [sksamuel/avro4s#199]
First of all I want to say that this is a very useful library, thanks!

I've noticed an easy performance trap if the library is used as per the examples. Say I create this utility function:

object AvroSerialization
{
	def serializeSingleBinary[T: SchemaFor : ToRecord](t: T): Array[Byte] = {
		val bos = new ByteArrayOutputStream
		val bos = new ByteArrayOutputStream(512)
		val aos = AvroOutputStream.binary[T](bos)
		try aos.write(t) finally aos.close()
		bos.close()
		bos.toByteArray
	}
}

Now if I repeatedly call this 100000 and compare it with the equivalent calls in java serialization, avro4s is 10x slower (900 ms for java serialization, 9 secs for avro4s). My guess is that the implicit instances SchemaFor and ToRecord are created over and over again for each call.

This code too suffers from the same slowdown:

	for (i <- 1 to 100000) {
		val bos = new ByteArrayOutputStream(512)
		val aos = AvroOutputStream.binary[Page](bos)
		try aos.write(pg) finally aos.close()
		bos.close()
		bos.toByteArray
	}

If I change the above code to java serialization, it is 10x faster. My guess again is that AvroOutputStream.binary[Page](bos)(... this creates a new instance of implicits for each call).

I believe most people will use it just like the code above which means their code will be quite slower than the equivalent java serialization.

Is there a fix for the above? My work around is to create the class below, which means the implicit instances will be passed on once only by the compiler:

package com.aktit.avro

import java.io.{ByteArrayInputStream, ByteArrayOutputStream}
import com.sksamuel.avro4s._

class AvroSerializer[T: SchemaFor : ToRecord : FromRecord]
{
	def serializeSingleBinary(t: T): Array[Byte] = {
		val bos = new ByteArrayOutputStream(512)
		val aos = AvroOutputStream.binary[T](bos)
		try aos.write(t) finally aos.close()
		bos.close()
		bos.toByteArray
	}

	def deserializeSingleBinary(a: Array[Byte]): T = {
		val ais = AvroInputStream.binary(new ByteArrayInputStream(a))
		try ais.iterator.next finally ais.close()
	}
}

Then use the same instance always: 
object DTOSerializers
{
	// One instance is the more performance efficient due to the reuse of avro4s implicit instances.
	val pageSerializer = new AvroSerializer[Page]
}

Now avro4s is 2x faster than the java serializer.

**Comment by sksamuel** [comment]
You're right, that it will be slower if you keep generating the schemas.
This is common to most scala librarys that use implicits in this way.

The simplest thing to do is just pull out the schema generation into a variable.

```
implicit val schema = SchemaFor[Page]
implicit val toRecord = ToRecord[Page]
implicit val fromRecord = FromRecord[Page]

for (i <- 1 to 100000) {
	val bos = new ByteArrayOutputStream(512)
	val aos = AvroOutputStream.binary[Page](bos)
	try aos.write(pg) finally aos.close()
	bos.close()
	bos.toByteArray
}
```

**Comment by s4nk** [comment]
Not really the same issue, but I've also noticed that the data format is around 10 times slower than binary. @sksamuel would you know off the top of your head where that time is spent? Would serializing the schema take so long?

**Comment by sksamuel** [comment]
Slowness is caused if it's calling apply on the implicit every time.
The solution is to move the implicits out of the loop (which the original poster did so unsure on his issue).

**Comment by sksamuel** [comment]
That line is only when the stream is created not on every write so can't be that. But it's got to be that the schema is invoked everytime.

**Comment by s4nk** [comment]
but in the samples above the stream is created in every iteration, right? in my experiment I did the same new stream in every iteration, both with data and binary, for some reason data is much much slower. Here's the snippet just to clarify:
```
import com.sksamuel.avro4s.{AvroOutputStream, FromRecord, SchemaFor, ToRecord}

case class Event(id: String)

val event = Event("123")
implicit val schema: SchemaFor[Event] = SchemaFor[Event]
implicit val toRecord: ToRecord[Event] = ToRecord[Event]
implicit val fromRecord: FromRecord[Event] = FromRecord[Event]

val t2 = System.currentTimeMillis()
for (_ <- 1 to 100000) {
  val outputStream = new ByteArrayOutputStream
  val avroOutputStream = AvroOutputStream.binary[Event](outputStream)
  avroOutputStream.write(event)
  avroOutputStream.flush()
  avroOutputStream.close()
  outputStream.toByteArray
}
val t3 = System.currentTimeMillis()

println(s"Avro binary: ${t3 - t2}ms")

val t4 = System.currentTimeMillis()
for (_ <- 1 to 100000) {
  val outputStream = new ByteArrayOutputStream
  val avroOutputStream = AvroOutputStream.data[Event](outputStream)
  avroOutputStream.write(event)
  avroOutputStream.flush()
  avroOutputStream.close()
  outputStream.toByteArray
}
val t5 = System.currentTimeMillis()

println(s"Avro data: ${t5 - t4}ms")
```

**Comment by sksamuel** [comment]
Yep you're right. I think we should add a variant that takes a schema, rather than a SchemaFor.

**Comment by s4nk** [comment]
I was thinking about that... strange thing is that `AvroBinaryOutputStream` also calls apply on `SchemaFor`:
```
 val dataWriter = new GenericDatumWriter[GenericRecord](schemaFor())
```
I was wondering if it could be the `org.apache.avro.file.DataFileWriter#create(org.apache.avro.Schema, java.io.OutputStream, byte[])` call that's expensive, because the actual data is written the same way `AvroBinaryOutputStream` writes it. I didn't try profiling it yet though

**Comment by sksamuel** [comment]
For 2.0 lets change the signature to accept a schema.

**Comment by sksamuel** [comment]
In 2.0.0-M3 onwards, all data output streams require the schema to be explicitly created. It can of course be generated by the `AvroStream` macro, or by hand, but it won't take an implicit `SchemaFor` and it therefore won't create thousands of invocations.
