### ISSUE TITLE
Avro4s should support Scala Enumerations

### ISSUE THREAD

**Issue by annovi** [sksamuel/avro4s#20]
Hello,

I wrote the following code

val is = AvroInputStream[MyType](body)

"body" is value that i got from a callback, and the type is array of byte (body: Array[Byte])

But this throws a compile time error

could not find implicit value for parameter builder: 
Error:(48, 60) could not find implicit value for evidence parameter of type com.sksamuel.avro4s.FromRecord[MyType]
          implicit val is = AvroInputStream[MyType](body)
                                                           ^
not enough arguments for method apply: (implicit evidence$1: com.sksamuel.avro4s.SchemaFor[MyType], implicit evidence$2: com.sksamuel.avro4s.FromRecord[MyType])com.sksamuel.avro4s.AvroInputStream[MyType] in object AvroInputStream.
Unspecified value parameter evidence$2.
          implicit val is = AvroInputStream[MyType](body)

**Comment by sksamuel** [comment]
Is MyType a case class?

**Comment by annovi** [comment]
Yes MyType  it is a case class.
The problem seems to be with my schema. 

I have a case class made in this way:

**Comment by sksamuel** [comment]
Yes scala enums are not supported. I will turn this issue into a feature request for those.

**Comment by annovi** [comment]
Thank you so much. When do you think you will be able to add this feature to the library?

**Comment by sksamuel** [comment]
1.4.0 now released supports this
