### ISSUE TITLE
org.apache.avro.SchemaParseException when multiple values of same generic user defined class are contained inside a case class

### ISSUE THREAD

**Issue by tmnd1991** [sksamuel/avro4s#200]
If I define two case classes like these:

```scala
case class Generic[T](a: T)
case class MyClass(a: Generic[Int], b: Generic[String])
```

And I try to generate an AvroOutputStream.data[Generic] like this:
```scala
val bos = new ByteArrayOutputStream()
val oos = AvroOutputStream.data[MyClass](bos).write(MyClass(Generic(3), Generic("")))    
```

I get a 
```org.apache.avro.SchemaParseException Can't redefine: Generic```

I think this is happening since the name of Generic[T] record type is always the classname both in the Int and String cases.

Probably this is fixable generating different type names for generic classes depending on the actual type(s).

Something like `Generic_Int` or `Generic_String` should work, right?

**Comment by tmnd1991** [comment]
I opened PR #201

**Comment by sksamuel** [comment]
Thanks for the PR. I think we'll have to release this as part of 2.0.0 release because this will break every single generated class that uses type parameters.

**Comment by tmnd1991** [comment]
Thank you for the reply.
Do you have any plan on the 2.0.0 release?

**Comment by sksamuel** [comment]
It shouldn't take longer than a month.

**Comment by tmnd1991** [comment]
I was thinking about an annotation to switch on/off functionality but if you plan to release 2.0.0 in a month I don’t think it is worthwhile working on it. If you like the idea of making it optional I can work on it anyway!

**Comment by sksamuel** [comment]
Let's do that, then I can release it as 1.9.1 immediately.

**Comment by tmnd1991** [comment]
Wednesday and on friday I’ll have a 4 hour train connection I will give it a shot during that time and update the PR

**Comment by tmnd1991** [comment]
I called the annotation `AvroSpecificGeneric`, I think it kinda fits ;)
I could not get rid of the `(enabled = true)` but does not look that bad.
If the implementation/interface looks nice to you I can write some docs in the README.md and then you can merge the PR to release 1.9.1.

**Comment by tmnd1991** [comment]
We should close this I think ;)
