### ISSUE TITLE
AvroOutputStream closes already closed OutputStream 

### ISSUE THREAD

**Issue by azolotko** [sksamuel/avro4s#203]
`AvroOutputStream` tries to close `os` here:
https://github.com/sksamuel/avro4s/blob/master/avro4s-core/src/main/scala/com/sksamuel/avro4s/AvroOutputStream.scala#L62

But the call to `writer.close()` in the preceding line has already closed that stream:

https://github.com/apache/avro/blob/master/lang/java/avro/src/main/java/org/apache/avro/file/DataFileWriter.java#L457

Some `OutputStream` implementations don't like to be asked to `close` more than once. For example, Akka Stream has this one:

https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala#L166

**Comment by sksamuel** [comment]
I think if you create an avro-output-stream on an existing stream, and then call close on the AOS, I think it's reasonable it should close the underlying stream too. Perhaps an overloaded version that gives you the option will suffice.

**Comment by sksamuel** [comment]
In 1.9.0 there is now an overloaded method which will not shut down the underlying stream.
