### ISSUE TITLE
SchemaFor fails in some cases when using default values

### ISSUE THREAD

**Issue by JesusMtnez** [sksamuel/avro4s#205]
Working with new version `1.9.0`, we have encountered a problem regarding code generation with macros. To reproduce the error, we've been working in https://github.com/Banno/avro4s/commit/7d002542094e34a6329025d46bdfd5df5f2ab17e .

```scala
package com.sksamuel.avro4s

import org.scalatest.{Matchers, WordSpec}

class SchemaForSpec extends WordSpec with Matchers {

  "SchemaFor" should {
    "work for case classes with complete path and no default value" in {
      """
         SchemaFor[com.sksamuel.avro4s.TestModel.Clazz1]
      """ should compile
    }

    "work for case classes with complete path and default value" in {
      """
         SchemaFor[com.sksamuel.avro4s.TestModel.Clazz2]
      """ should compile
    }

    "work for case classes with import and no default value" in {
      """
         import com.sksamuel.avro4s.TestModel._
         SchemaFor[Clazz1]
      """ should compile
    }

    "work for case classes with import and default value" in {
      """
         import com.sksamuel.avro4s.TestModel._
         SchemaFor[Clazz2]
      """ should compile
    }
  }

}

object TestModel {
  case class Clazz1(str: String)
  case class Clazz2(str: String = "test")
}
```

The result is:
```
[info] SchemaForSpec:
[info] SchemaFor
[info] - should work for case classes with complete path and no default value
[info] - should work for case classes with complete path and default value *** FAILED ***
[info]   Expected no compiler error, but got the following type error: "not found: value Clazz2", for code: 
[info]            SchemaFor[com.sksamuel.avro4s.TestModel.Clazz2]() (SchemaForSpec.scala:17)
[info] - should work for case classes with import and no default value
[info] - should work for case classes with import and default value
[info] Run completed in 172 milliseconds.
[info] Total number of tests run: 4
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 3, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	com.sksamuel.avro4s.SchemaForSpec
[error] (avro4s-core / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 3 s, completed May 30, 2018 5:01:46 PM

```

The problem we found is that when the `SchemaFor` is given a type with its complete path and a default value, the code generated by `val fieldSchemaPartTrees: Seq[Tree]` is the same as in the version using the import statement that it is:

```
List(_root_.com.sksamuel.avro4s.SchemaFor.fieldBuilder[String]("str", Seq(), Clazz2.<init>$default$1, "com.sksamuel.avro4s"))
```

I point to `fieldSchemaPartTrees` since it's the only macro related change in version 1.9.0 changes. 

My thoughts are that the macro is losing the complete path reference in the first case, making the scenario `work for case classes with complete path and default value` failed since `Clazz2.<init>$default$1` is not the object defined with default values. This is just my suggestion about what is happening since I don't know a lot about ScalaMeta.

**Comment by JesusMtnez** [comment]
I've added more test cases regarding the error, to discard that is not about full path types. In this commit https://github.com/Banno/avro4s/commit/8564845de41f7d52157f7a5cba2588cb635365a1 the error is reproduced in more scenarios.

I have no more clues about what is causing the error, though.

**Comment by sksamuel** [comment]
For clarity, did this work in 1.8 ?

**Comment by JesusMtnez** [comment]
All tests working in 1.8.3

**Comment by sksamuel** [comment]
Then it will be my change to make it work on nested case classes that I added in 1.9.0.
I can add an if/else if that's broken it.

**Comment by JesusMtnez** [comment]
Do you mean https://github.com/sksamuel/avro4s/commit/d9e9c009486a232a443188c89ad0a851a5eb81e8 ?

**Comment by sksamuel** [comment]
Yep, the $ownerTermName can be stripped out if it's a top level class. So
just need some if else around it after detecting what the owner is I
suppose.

**Comment by sksamuel** [comment]
I can do it, but won't be tonight I'm home tonight.

**Comment by JesusMtnez** [comment]
No problem, I'll wait. Feel free to ping me

**Comment by JesusMtnez** [comment]
@sksamuel sorry to bother you. Could you take it a look any time? Or how could I help you? Some guidance will be very appreciated. :smile_cat:

**Comment by sksamuel** [comment]
This is working in the 2.0 branch.
