### ISSUE TITLE
java.time.Instant & friends support

### ISSUE THREAD

**Issue by muradm** [sksamuel/avro4s#207]
Seems like support is there, but `Instant` field didn't work out of the box, only after adding below implicit:
```
  implicit object InstantToSchema extends ToSchema[Instant] {
    override val schema: Schema = Schema.create(Schema.Type.LONG)
  }
```

**Comment by diesalbla** [comment]
[This PR in the Avro](https://github.com/apache/avro/pull/309/files) repository improves the support in the Avro codebase itself for the `java.time` types.

**Comment by sksamuel** [comment]
Looks like the last release of avro was 1.8.2 which predates this commit.

**Comment by sksamuel** [comment]
This is now added in the 2.0 development branch and will be supported in that version (Instant, LocalDate, LocalTime etc)

**Comment by edmondo1984** [comment]
This used to work in previous versions, as we migrated from 1.8.3 2.11 to 1.9.0 of 2.12 in avro4s it breaks:

```
[info] Compiling 3 Scala sources to /Users/edmondoporcu1/Development/credimi/user-preferences/user-preferences-salesforce-api/target/scala-2.12/classes ...
[error] /Users/edmondoporcu1/Development/credimi/user-preferences/user-preferences-salesforce-api/src/main/scala/com/credimi/userpreferences/salesforce/SalesforceGDPRPreferencesService.scala:49:65: could not find implicit value for parameter toRecord: com.sksamuel.avro4s.ToRecord[com.credimi.userpreferences.salesforce.ContactGDPRPreferences]


case class ContactGDPRPreferences(gdpr_profiling_consensus__c: Option[String] = None, gdpr_marketing_consensus__c: Option[String] = None, gdpr_service_consensus__c: Option[String] = None, gdpr_third_party_consensus__c: Option[String] = None, gdpr_consensus_source__c: Option[String] = None, gdpr_consensus_expressed_at__c: Option[java.time.Instant] = None, email: Option[String] = None, salesforceid: Option[String] = None, lastmodifieddate: Option[java.time.Instant] = None)

```

The only thing I see here is the instant that might cause issues, but again it was working in 1.8.0

**Comment by edmondo1984** [comment]
Apologies, I think we have not fully understood the problem. There was no Instant support in 1.8.x whatsoever, but we were using it with 2.11 and sbt-avro4s which would turn timestamps into long.

Instead, as we switched to 2.12, we used sbt-avrohugger as suggested on sbt-avro4s documentation, and this new plugin converts in a Instant

**Comment by sksamuel** [comment]
So if you're using sbt-avrohugger, you're getting Instants.
And 2.0 supports instants (all java.time classes actually).
So you should be good now ?
