### ISSUE TITLE
Compatibility issue Serializing/Deserializing messages generated with avro4s and other languages

### ISSUE THREAD

**Issue by annovi** [sksamuel/avro4s#21]
I have two separate applications that  interact using a queue in the middle, and they communicate sending messages to each other, using Avro (Serialize and Deserialize).
The queue in the middle is managed by a message broker (RabbitMq)

The scenario is really simple: 
- one application create a message (based of a schema), serialize the message and put the message in the queue.
- on the other side there is an other program that pick this message, deserialize the avro message and read the content.

This is my schema (really simple)
```
{
	"type": "record",
	"name": "Surface",
	"fields": [
	{
		"name": "surfaceId",
		"type": "string"
	}]
}
```
`case class Surface(surfaceId: String)`

I serialize the message using avro4s library and I send this message to  message broker.
I use this code to serialized the message:

**First scenario**: two applications made in **Scala**
```
    val surface = Surface(surfaceId = "5423g343423")
    val stream = new ByteArrayOutputStream()
    val os = AvroOutputStream[Surface](stream, true)
    os.write(surface)
    os.flush()
```
On the other side there is an other application that grab the message from the queue, and deserialize the message with the avro4s library. Body is Array[Byte]

```
        val is = AvroInputStream[Surface](body)
        val result = is.iterator.toSet
        println(result.mkString("\n"))
        is.close()
```

This configuration works perfectly.

**Second scenario**: One application made in **Scala** serialize the message and on the other side an other application made in **Java**,  deserialize the message and read the content.
I try to deserialize the message using the official Java module Apache Avro (https://avro.apache.org/docs/1.7.7/gettingstartedjava.html) I got an error and I am not able to deserialize the content of the message.

**Third scenario**: One application made in **Scala** serialize the message and on the other side an other application made in **Python**,  deserialize the message and read the content.
I got an error when I tried to deserialized the message (same as with Java)

**Forth scenario**: One application made in **Python** serialize the message and on the other side an other application made in **Scala**,  deserialize the message and read the content.
When I tried to deserialize the message using the avro4s module I got an error.

**Fifth scenario**: One application made in **Python** serialize the message and on the other side an other application made in **Java**,  deserialize the message and read the content.
It works perfectly!

**Sixth scenario**: One application made in **Python** serialize the message and on the other side an other application made in **JavaScript**,  deserialize the message and read the content.
It works perfectly!

I suspect there is a compatibility issue in Serializing and Deserializing messages using the avro4s and other library.

Or I'm doing something wrong ...

**Comment by sksamuel** [comment]
Can you show me the java code you are using on the other side to deserialize?

**Comment by annovi** [comment]
Serialization in Java:
```
ByteArrayOutputStream bout = new ByteArrayOutputStream();
SpecificDatumWriter<Surface> writer = new SpecificDatumWriter<Surface> Surface.getClassSchema());
BinaryEncoder binEncoder = new BinaryEncoder(bout);
writer.write(v, binEncoder);   // v is the message that i want to serialize
binEncoder.flush();
```

Deserialization in Java:
```
SpecificDatumReader<Surface> reader = new SpecificDatumReader<Surface> Surface.getClassSchema());
Decoder decoder = DecoderFactory.get().binaryDecoder(new ByteArrayInputStream(out.toByteArray()), null);
reader.read(null, decoder);
```

**Comment by annovi** [comment]
I found the problem in your library, you are not handling the deserialization of binary stream. I only works with file, as  documented in a nice way in your example.

Indeed the AvroInputStream handle only file.
The AvroOutputStream is able also to handle the binary stream, but only using the second parameter to false, in this way `val os = AvroOutputStream[Surface](stream, false)`.

Is possible for you to extend the library to support also BinaryOuputStream and not only file?
If you want I can wrote myself this code and contribute to this library?

**Comment by sksamuel** [comment]
Yes, if you would like to add that and raise a PR I will merge it.

**Comment by sksamuel** [comment]
I added the first draft for binary inputs. Take a look at the branch feature/binaryinput and see if you can complete it? The issue I have is that the hasNext method doesn't work because the binary decoder doesn't seem to keep track of previously read records (it just keeps returning the first one all the time).

**Comment by annovi** [comment]
Hi Samuel, 
I already a working solution for the binary serialization/deserialization, but I will show you Tuesday morning! Tomorrow unfortunately I cannot work on that. I tried Friday to create a branch with this solution but I didn't have enough right to upload code in your repository. Can you please me give the right to create a branch?
Talk to you later
Regards,
Andrea
On May 15, 2016 22:43, Stephen Samuel <notifications@github.com> wrote:I added the first draft for binary inputs. Take a look at the branch feature/binaryinput and see if you can complete it? The issue I have is that the hasNext method doesn't work because the binary decoder doesn't seem to keep track of previously read records (it just keeps returning the first one all the time).

**Comment by sksamuel** [comment]
Great, if you already have a solution that's great. 

On github you can just fork the repo, and then link me to your fork.

**Comment by annovi** [comment]
Ok, thank you!
On May 15, 2016 22:53, Stephen Samuel <notifications@github.com> wrote:Great, if you already have a solution that's great. 

On github you can just fork the repo, and then link me to your fork.

**Comment by annovi** [comment]
I made  PR for this issue.
