### ISSUE TITLE
AvroDataOutputStream close outputStream twice

### ISSUE THREAD

**Issue by ikryvorotenko** [sksamuel/avro4s#211]
AvroDataOutputStream has a method `close` which looks following:
```
  override def close(): Unit = {
    writer.close()
    os.close()
  }
```
And writer close looks following
```
  @Override
  public void close() throws IOException {
    if (isOpen) {
      flush();
      out.close();
      isOpen = false;
    }
  }
```
where `out` is the same outputStream passed into writer before. So that the outputStream is being closed twice, which may lead to exceptions if outputStream handle second `close` call accordingly.

So it looks like the `os.close()` is redundant here or i'm missing something?

**Comment by sksamuel** [comment]
Thanks, I've fixed this now.
