### ISSUE TITLE
Is it possible to serialize big decimal as string?

### ISSUE THREAD

**Issue by soloman817** [sksamuel/avro4s#214]
To serialize big decimal, it is required to decide the precision before hand. But this is hard to trade-off sometimes. Less precision might loose data, more precision will cost more space. So would it be a good idea to make a custom serializer which transform big decimal into string?

**Comment by sksamuel** [comment]
It's possible, but coming back, if you had a string field, you wouldn't know it was a big decimal. Avro logical type of decimal might not be happy working on a string field.

**Comment by sksamuel** [comment]
In 2.0.0-M3 you can now just add an instance of `SchemaFor` and it will use that when choosing which schema.

Eg, you can do this:

```scala
      implicit object BigDecimalAsString extends SchemaFor[BigDecimal] {
        override def schema: Schema = SchemaBuilder.builder().stringType()
      }
```

before you call AvroSchema[T].

**Comment by sksamuel** [comment]
2.0.0 is now released with this supported, so closing this ticket.
