### ISSUE TITLE
UUID and java.time._ new mapping proposal

### ISSUE THREAD

**Issue by tmnd1991** [sksamuel/avro4s#217]
I think it might be beneficial to all users to change the following mappings:

scala type | avro type
-- | --
java.util.UUID | string
java.time.LocalDate | string

scala type | avro type
-- | --
java.util.UUID | record (lower: long, higher: long)
java.time.LocalDate | long
java.time.ZonedDateTime | record (epoch: long, zoneId: string)

I find myself saving a lot of space using these mappings instead of the default ones (especially for the UUID), also I think that parsing text is slower than constructing date objects from epoch ts.

**Comment by sksamuel** [comment]
We have to maintain compatibility with other systems that use Avro. Since UUID is a logical type in Avro, we should serialise it in the way that it is specified in the spec. 

The date's is different, but I wouldn't be keen on a record.

**Comment by tmnd1991** [comment]
I completely understand your point about UUID. Would you mind elaborate about the "not keen on a record" part? Is there some "avro" best practice I'm missing or performance penalties of records/values I'm not taking into account?

**Comment by sksamuel** [comment]
I guess for ZonedDateTime we could encode it as a record of epoch and zoneId.
I will add this to the 2.0 branch.

**Comment by sksamuel** [comment]
In 2.0 we support Instants which are encoded as timestamp-millis.
