### ISSUE TITLE
Option with default to Schema : Union ordering does not follow Avro standard.

### ISSUE THREAD

**Issue by bellemare** [sksamuel/avro4s#221]
Currently, it seems that 
```
Option[String] = Some("$")
``` 
is converted to:
```
{
      "name": "currency",
      "type": ["null", "string"],
      "default": "$"
    }
```
This can be seen in the expected test output here:
https://github.com/sksamuel/avro4s/blob/master/avro4s-core/src/test/resources/optiondefaultvalues.avsc#L14
I would expect that the order should be:
```
{
      "name": "currency",
      "type": ["string", "null"],
      "default": "$"
    }
```

According to the Avro standard: (https://avro.apache.org/docs/current/spec.html#Unions)
`
(Note that when a default value is specified for a record field whose type is a union, the type of the default value must match the first element of the union. Thus, for unions containing "null", the "null" is usually listed first, since the default value of such unions is typically null.)
`

I mention this as a bug because other tools that I have which read from the output are all sending ERRORs and/or WARNs (depending on the tool) that the schema is not output as expected.

Can you validate that this is indeed an issue as I have outlined above?

**Comment by sksamuel** [comment]
If we adhere to the spec (as we should) then it's a bug.

**Comment by sksamuel** [comment]
Now supported in 2.0 development branch.

**Comment by bellemare** [comment]
Thanks @sksamuel 👍. I appreciate the quick support and am grateful for the work you put into your library.
