### ISSUE TITLE
Add Cats encoders/decoders

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/avro4s#225]

**Comment by sksamuel** [comment]
Done.

**Comment by tPl0ch** [comment]
@sksamuel How come the `cats` integration is commented out in `build.sbt`?

See https://github.com/sksamuel/avro4s/blob/master/build.sbt#L15

**Comment by sksamuel** [comment]
I couldn't get it to compile/test anymore. If you can fix it, a PR would be great.
