### ISSUE TITLE
AvroNamespace ignored on decoding

### ISSUE THREAD

**Issue by iofik** [sksamuel/avro4s#227]
I have problems decoding JSONs generated with classes with altered AvroNamespace if such classes appear in Union. Here is example:

```Scala
package tree
sealed trait Fruit

AvroNamespace("market")
final case class Apple(weight: Double) extends Fruit

AvroNamespace("market")
final case class Orange(color: String) extends Fruit

AvroNamespace("market")
final case class Buy(fruit: Fruit)
```

So I can encode a `Buy` object and `fruit` field will have something like `market.Orange`.
But then I cannot decode such data, because `safeFrom` will compare `market.Orange` to `tree.Orange` and will fail to detect `Orange` instance.
I can't think of a valid scenario when such behaviour might be desired.
Solution seems to be pretty simple: use `AvroNamespace` value if it is defined, and fallback to real class package if the annotation is missing.

**Comment by sksamuel** [comment]
I think you're exactly right, safeFrom should not use the type package if @AvroNamespacae has been added.

**Comment by sksamuel** [comment]
This is working in 2.0.0-M3 if you want to give it a go and report back.

**Comment by sksamuel** [comment]
2.0.0 is now released, so closing this ticket.

**Comment by iofik** [comment]
Ah, I see that 2.0.0 is for Scala 2.12 and later, but we are still on 2.11.
Do you implement/accept patches for 1.9.x branch?

**Comment by iofik** [comment]
While I was trying to find time to backport this to 2.11, we switched to Scala 2.12. :-)

**Comment by sksamuel** [comment]
Nice
