### ISSUE TITLE
Optional field with default value not deserialized correctly when value is missing

### ISSUE THREAD

**Issue by rogueai** [sksamuel/avro4s#228]
I'm trying to implement schema evolution adding a new field to an existing schema. The new field's schema looks like this:
```
{
    "name": "userAgent",
    "type": [
        "null",
        "string"
    ],
    "default": null
}
```
Generated case class is correctly initializing the field as `userAgent: Option[String] = None`, so new instances of the schema are serialized correctly as: `"userAgent":null`

The problem arises for old records serialized with the old version of the schema: the field being optional and with a default value should make the record fully forward compatible, but when deserializing the record avro4s assigns the field a default value of `JsonProperties.NULL_VALUE`  that gets converted to string, resulting in in: `Some("org.apache.avro.JsonProperties$Null@5300cac")`

As a workaround, I'm overriding the implicit for `OptionFromValue` this way:
```
implicit def OptionFromValue[T](implicit fromvalue: FromValue[T]) = new FromValue[Option[T]] {
    override def apply(value: Any, field: Field): Option[T] = value match {
        case JsonProperties.NULL_VALUE => None
        case _ => Option(value).map((value: Any) => fromvalue.apply(value))
    }
}
```
This works, but I guess it should be handled correctly in avro4s.

**Comment by sksamuel** [comment]
So in the old schema, the field was not present at all. So when deserializing the record, the default null should be applied, which should be converted to None, but instead it's wrapping the null in a Some.

**Comment by sksamuel** [comment]
2.0.0 is released with this fix.
