### ISSUE TITLE
Difficulties with documentation for serialization/deserialization with bytes

### ISSUE THREAD

**Issue by NastasiaSaby** [sksamuel/avro4s#232]
Hello,

1.8.3
2.11 for Scala

Maybe I missed something, but I am not able to make the example in the documentation for serialization/deserialization with bytes work:

```
AvroInputStream.binary.from(...).build(...)
AvroInputStream.json.from(...).build(...)
```

I am able to deserialize bytes with something like that for instance:

```
val characterShemaFor = SchemaFor[Character]
val characterFromRecord = FromRecord[Character]
val characterToRecord = ToRecord[Character]

val in: ByteArrayInputStream = new ByteArrayInputStream(bytes)
val output: AvroBinaryInputStream[Character] = AvroInputStream.binary[Character](in)(characterShemaFor, characterFromRecord)
```

Is there a way to deserialize bytes including a schema?
Thanks for your help.

**Comment by sksamuel** [comment]
Hi, Which version ?

**Comment by NastasiaSaby** [comment]
1.8.3

**Comment by sksamuel** [comment]
The documentation on master refers to the 2.0.0 release. If you go back to release 1.8.3 in github tags you can see the older docs.

**Comment by NastasiaSaby** [comment]
Ok sorry. My mistake. I close this issue

**Comment by sksamuel** [comment]
You could try 2.0.1 as well if you are able to change to scala 2.12
