### ISSUE TITLE
Is avro4s compatible with topics registered in avro by third party applications

### ISSUE THREAD

**Issue by NastasiaSaby** [sksamuel/avro4s#233]
1.8.3
2.11 for Scala

Hello,

My problem is as followed.

I have some data in some topics in avro.
And I want to deserialize it with avro4s. It works very well when I have sent my data with avro4s.
But, if I have sent my data with another application like with confluent jars for instance, I don't suceed  in reading them. 
To be more precise, I get my objects with "None" in all the fields.

I did it this way:

```
val characterShemaFor = SchemaFor[Character]
val characterSchemaFrom = FromRecord[Character]
val characterToRecord = ToRecord[Character]

def deser(bytes: Array[Byte]) = {
    val in = new ByteArrayInputStream(bytes)
    val input = AvroInputStream.binary[Character](in)(characterShemaFor, characterSchemaFrom)
    val result: Seq[Character] = input.iterator.toSeq
    result.head
  }
```

I get something like that:
```
Character(None,None)
```

```
+----+----+
|name|age |
+----+----+
|null|null|
|null|null|
|null|null|
|null|null|
|null|null|
|null|null|
+----+----+
```

Note that if I use the deserialization with the confluent jars, it works:
```
+-------+---+
|name   |age|
+-------+---+
|Julien |7  |
|Fatiha |56 |
|Fatiha |56 |
|Adeline|12 |
|Julien |7  |
|Adeline|12 |
+-------+---+
```
Am I missing something or it is not possible to read a Kafka topic registered with the confluent jars ?

Thank you for your answer.

**Comment by sksamuel** [comment]
Are you using the Confluent schema registry ?

**Comment by NastasiaSaby** [comment]
To write the data yes. So, my data have a schema registered in the Confluent schema registry.
I don't find a way to read it after. Maybe the solution is to read it with a schema (confluent schema registry's schema), but I don't find a way to give a schema to read data with the 1.8.3 version of avro4s.

**Comment by sksamuel** [comment]
If you write the data using a `ConfluentAvroSerde` then it puts extra bytes at the start of the data so that when you deserialize it, it knows which schema to fetch. If you take the raw bytes from a kafka topic written in this way, and try to deserialize it in Avro Java or Avro4s it won't work because it won't know that the stream contains these extra bytes at the start.

**Comment by NastasiaSaby** [comment]
Thank you for your answer. So, it is not possible to read a Kafka topic with Avro4s unless we find a solution to remove this exta bytes. Am I right?

**Comment by NastasiaSaby** [comment]
Thank you for your answer. I'm closing this issue.
