### ISSUE TITLE
scala 2.11 support

### ISSUE THREAD

**Issue by borissmidt** [sksamuel/avro4s#237]
Dear,

First of i really like your library because it is written in an easy to use and straight forward way.

Would you be so kind to support scala 2.11 for version 2.x? 
Since spark and many other big data platforms only supporting scala 2.11?

I have pulled the last release and i have been able to fully build for scala_2.11 without any failing test.

Kind regards, Boris Smidt

**Comment by sksamuel** [comment]
I'm happy to do a release of 2.11 from the current master - but I can't promise to support it moving forward if there's bugs that can only be fixed in 2.12.

**Comment by borissmidt** [comment]
That would be perfect, thank you for your help and i'm looking forward to the 2.11 release.

**Comment by sksamuel** [comment]
I've released 2.0.2 with a cross build to 2.11
