### ISSUE TITLE
Support default values in Avro schema generated from a case class that has default parameter values

### ISSUE THREAD

**Issue by Jubobs** [sksamuel/avro4s#24]
As of 2.10, Scala supports [default parameter values](http://docs.scala-lang.org/tutorials/tour/default-parameter-values.html). However, those values get lost in translation when generating a case class's Avro schema. Here is an illustrative example:

```
scala> import com.sksamuel.avro4s.AvroSchema
import com.sksamuel.avro4s.AvroSchema

scala> case class Ingredient(name: String = "flour")
defined class Ingredient

scala> val schema = AvroSchema[Ingredient]
schema: org.apache.avro.Schema = {"type":"record","name":"Ingredient","namespace":"$iw","fields":[{"name":"name","type":"string"}]}
```

Note that the default value `"flour"` for parameter `name` doesn't appear in the Avro schema generated for case class `Ingredient`. It would be nice if the generated schema were, instead,

```
{"type":"record","name":"Ingredient","namespace":"$iw","fields":[{"name":"name","type":"string","default":"flour"}]}
```

Since avro4s requires a later version (2.11.8, currently) than 2.10, I don't think there would be anything blocking such an enhancement.

**Comment by sksamuel** [comment]
Since you can do this:

```scala
object Mongo {
  def name: String = ???
}

case class Foo(name: String = Mongo.name)
```

Which I couldn't invoke at compile time, I wouldn't be able to support default args that invoke a method. It might be possible to use default args that reference a literal, as in your case.

**Comment by Jubobs** [comment]
> Which I couldn't invoke at compile time, I wouldn't be able to support default args that invoke a method

That's a good point. I only had literals in mind when I posted this issue; even only supporting literal default values would be beneficial, in my opinion.

**Comment by sksamuel** [comment]
I was just looking into it, and even literals require a method invocation (they make a method called apply$default$n which is invoked at runtime). I might be able to do same.

**Comment by sksamuel** [comment]
Seems I was able to get it working.

**Comment by Jubobs** [comment]
I just took the new feature for a trial run. Seems to work great. Thanks!

**Comment by sksamuel** [comment]
:+1:
