### ISSUE TITLE
Extending Annotations

### ISSUE THREAD

**Issue by ljurukov** [sksamuel/avro4s#242]
I would like to be able to create custom annotations that translate into one or many of the base annotations.

For example creating something like:
`case class DocProp(doc:String, property:String) extends AvroProp(name = "static", value= property) with AvroDoc(doc=doc)`

Allows me to annotate a field without needing to define both AvroProp and AvroDoc along with keeping the static property the same across potentially a large number of classes

Obviously this can't be done as is because all the annotations are case classes.

So a question and a proposal. First is this behavior that you wish to expose? It wouldn't be adding any additional schema produced and it would be transparent to anyone who doesn't need/want it would interact as documented in the Readme currently.

Proposed changes would require changing `AnnotationExtractors` to not match on class string name
As well as creating a show trait for each case class in `annotations` that each corresponding case class would inherit. That way if someone wants to create their own annotation they can do so by extending the traits of the annotations they want to "merge".

I have done as described above and if there is interest I can make a PR. It's a diff of about 9 lines of code minus the shadow traits (where it become more like 30-40 lines)
Thanks!

**Comment by sksamuel** [comment]
So introduce a trait say "AvroNameable" which @AvroName now implements, and instead of matching on AvroName we match on the trait. Meaning you can just implement the trait instead ?

**Comment by ljurukov** [comment]
Yes, exactly. 
Something like this:
`case class AvroName(name: String) extends Name

trait AvroNameable extends StaticAnnotation {
  val name: String
}`

**Comment by sksamuel** [comment]
I think that's perfectly reasonable, just need some good names for the traits.

**Comment by ljurukov** [comment]
Pr Merged: https://github.com/sksamuel/avro4s/pull/246
