### ISSUE TITLE
New Annotation Proposal

### ISSUE THREAD

**Issue by ljurukov** [sksamuel/avro4s#243]
Would it be possible to add a new Annotation that is like @AvroProp except backed by a Map instead of a key value. Something like:
`@AvroPropMap(properties: Map[String,String])`
or have @AvroProp take one or more tuples as the constructor argument
So that if I have a list of properties I wish to add I can do so in one tag instead of N tags

**Comment by sksamuel** [comment]
Yeah that's a good idea, probably what I should have done to start with.

@AvroProps
