### ISSUE TITLE
Json Serialisation Support is missing

### ISSUE THREAD

**Issue by dlynam01** [sksamuel/avro4s#25]
The library should support json as a way of serialisation.  At the minute only binary and file serialisation is available.

**Comment by sksamuel** [comment]
Out of interest, why would you chose to serialize in avro4s over a "proper" json library?

**Comment by dlynam01** [comment]
We write messages to a kafka event queue, these messages are written as json, we would like to use avro to ensure that both producer of the events and consumer of the events are in sync. We would prefer to keep with json in the event queue.

**Comment by sksamuel** [comment]
It's merged :+1:

**Comment by dlynam01** [comment]
great thanks 👍

**Comment by Jubobs** [comment]
Shouldn't the new case class be called `AvroJsonOutputStream`, for consistency?

**Comment by sksamuel** [comment]
That's a good point. I'll rename it and do a release.

**Comment by sksamuel** [comment]
1.4.2 should appear on maven central soon
