### ISSUE TITLE
Compile times scale poorly when using large ADT types

### ISSUE THREAD

**Issue by coltfred** [sksamuel/avro4s#252]
Currently I'm struggling with a large Coproduct type (ADT) that is dragging my compile times into the dirt and I'm not sure how to fix it. I'm hoping you might have some ideas.

The issue is that as you scale an ADT the macro expansions duplicate work for each additional member. Following the [blogpost](https://www.scala-lang.org/blog/2018/06/04/scalac-profiling.html) on this subject led me to believe that I could somehow cache the sub pieces of this computation in implicits and that it would help the compiler to not redo work. This didn't appear to work for me.

I made a test project to hopefully lower the barrier to getting some help on this topic. That project is [here](https://github.com/coltfred/avro4s-test-event). I've also included the flamegraph of the implicit search which shows the problem in a more visual manner. If you clone the repo and `sbt compile` you'll see the implicit searches, macro expansions as well and overall time taken in the typer.

My questions boil down to:
1) Is there anyway to create these implicits for `ToValue` and `ToSchema` which are being generated hundreds of time _outside_ the call to `ToRecord` on the Event type to keep the compiler from redoing this work? 
2) If you can't, what can we do to fix this issue internally to hopefully save this repeated work and save future poor souls from the implicit optimization hell I've endured?

Thanks!

**Comment by sksamuel** [comment]
So it's the repeated invocations of the macros for `ProjectId` and `OrgId` that (in this example) slow things down. They could in theory be cached yes.

**Comment by sksamuel** [comment]
Did pulling `ToValue` and `ToSchema` for the types out and putting them into scope not work for you?

**Comment by coltfred** [comment]
@sksamuel I moved the repo to 2.x since I'm able to upgrade now. It seems that SchemaFor only gets called once for each of the types I have, but the majority of the macro expansions are now ClassTag related. These are the worst offenders.

```
[info]   "shapeless.Generic.Aux[test.OrgId,Int :: shapeless.HNil]" -> 32,
[info]   "shapeless.Generic.Aux[test.ProjectId,Int :: shapeless.HNil]" -> 35,
[info]   "scala.reflect.ClassTag[test.Foo]" -> 36,
[info]   "reflect.runtime.universe.TypeTag[Long]" -> 36,
[info]   "reflect.runtime.universe.TypeTag[String]" -> 44,
[info]   "reflect.runtime.universe.TypeTag[test.OrgId]" -> 44,
[info]   "scala.reflect.ClassTag[Long]" -> 44,
[info]   "shapeless.Lazy[com.sksamuel.avro4s.SchemaFor[Int]]" -> 46,
[info]   "reflect.runtime.universe.TypeTag[test.ProjectId]" -> 48,
[info]   "scala.reflect.ClassTag[String]" -> 55,
[info]   "scala.reflect.ClassTag[test.OrgId]" -> 64,
[info]   "scala.reflect.ClassTag[test.ProjectId]" -> 70,
[info]   "reflect.runtime.universe.TypeTag[Int]" -> 96,
[info]   "scala.reflect.ClassTag[Int]" -> 118
```

I tried to cache the ClassTag in the companion object of those objects, but that didn't seem to help. Also it seems like the Lazy from shapeless is a repeat offender too. 

Should I be caching these values right before the invocation of the macro? Am I missing the point entirely?

**Comment by sksamuel** [comment]
ClassTag is added by the compiler. I'm not sure how you would cache it or why it would be slow.
