### ISSUE TITLE
ToRecord on a sealed trait union with a field level namespace anno fails

### ISSUE THREAD

**Issue by lacarvalho91** [sksamuel/avro4s#255]
When using `ToRecord` on a schema that contains a sealed trait of case classes and there is a namespace annotation at the field level for the union, calling `.to` throws "java.lang.RuntimeException: Cannot find subschema for type name"

```scala
sealed trait Foo
case class Bar(i: Int) extends Foo
case class Baz(s: String) extends Foo

case class MySchema(@AvroNamespace("broken") foo: Foo, id: String, x: Int)

val schema = AvroSchema[MySchema]

val ms = MySchema(Bar(1), "", 0)
ToRecord[MySchema](schema).to(ms) //throws
```

Error message:

```
Cannot find subschema for type name some.package.Bar in [{"type":"record","name":"Bar","namespace":"broken","fields":[{"name":"i","type":"int"}]}, {"type":"record","name":"Baz","namespace":"broken","fields":[{"name":"s","type":"string"}]}]
```

**Comment by sksamuel** [comment]
It works if you move the annotation to the Foo type.

**Comment by lacarvalho91** [comment]
@sksamuel yeah, its more for this feature though: https://github.com/sksamuel/avro4s/issues/170 I think there might have been a regression since that was added

**Comment by sksamuel** [comment]
I got this to work in master, try the latest snapshot. @lacarvalho91

**Comment by lacarvalho91** [comment]
@sksamuel nice one, thanks! Will give it a go soon, hopefully today

**Comment by lacarvalho91** [comment]
Looks good! Thanks for your work @sksamuel
