### ISSUE TITLE
Latest version generates namespace & class name differently

### ISSUE THREAD

**Issue by gregsilin** [sksamuel/avro4s#257]
We're serializing a generic type, such as:

```scala 
package com.mycompany.events

object Types {
  case class Event[T] private[events](payload: T)

  case class Foo(s: String)
}

import Types._
val schema = AvroSchema[Event[Foo]].toString
```

Namespace & name are generating differently in avro4s `2.0.2` vs what we had in `1.8.4`:

```avro
// 1.8.4

{
  "type" : "record",
  "name" : "Event",
  "namespace" : "com.mycompany.events",
....

// 2.0.2: adds the `Types` to namespace and `__Foo` to name
{
  "type" : "record",
  "name" : "Event__Foo",
  "namespace" : "com.mycompany.events.Types",
....

```
Note the difference in the name & namespace generated.  

As far as the namespace change goes, `Types` is a Scala object, and not part of the package, yet it's included as part of the namespace.

Is that by design? Is there a way to generate a consistent schema across versions?

**Comment by sksamuel** [comment]
Yes it's by design. It's to avoid clashes when you want to generate a schema for `Event[Foo]` and `Event[Bar]`. You can disable this feature by annotation your case class with `@AvroErasedName`

```/**
  * This annotation is used to disable generics in the encoding
  * of a record's name.
  *
  * Normally, the record name for a generic type is the name of the
  * raw type, plus the actual type parameters. For example, a class Foo
  * with type parameters Int and Boolean, would have a generated name of
  * `Foo__Int_Boolean`
  *
  * When this annotation is present on a type, the name used in the
  * schema will simply be the raw type, eg `Foo`.
  */``

**Comment by sksamuel** [comment]
Added docs to the readme.
https://github.com/sksamuel/avro4s/blob/master/README.md#type-parameters
