### ISSUE TITLE
License of avro4s-core

### ISSUE THREAD

**Issue by dkobylarz** [sksamuel/avro4s#266]
I am a little bit confused. The github project reports this project to be under Apache License 2.0, but the avro4s-core 1.9.0 I want to use in my project is reported/released under MIT:
https://mvnrepository.com/artifact/com.sksamuel.avro4s/avro4s-core_2.12/1.9.0
Which license should this particular avro4s-core version be referenced with?

Thank you,

**Comment by sksamuel** [comment]
Should all be apache 2.0.

**Comment by dkobylarz** [comment]
Excellent! Thank you for the quick response
