### ISSUE TITLE
Encoder depends on SchemaName for Union[T,Null]

### ISSUE THREAD

**Issue by zzeekk** [sksamuel/avro4s#268]
Problem:
Encoding a nested case class to Avro normally works without matching SchemaName/Namespace's, except for Union types. For Union's the selection of the relevant type must be done using SchemaName/Namespace. The pitty is that a scala Option[T] in is an Avro Union[T,Null] - which means in this case SchemaName/Namespace need to match, even if it is obvious which type to choose. As we have to enocode to external Schemas which don't match our package structure, we would need to annotate all our deeply nested case class with corresponding SchemaName/Namespaces. 

Solution:
A small change in SchemaHelper.extractTraitSubschema could check if after filtering all Null types only one real type is left, and in that case do without checking SchemaName/Namespace. Would you agree on this improvement?

**Comment by sksamuel** [comment]
Yes that makes sense.

**Comment by zzeekk** [comment]
Thanks, i'll create a pull request.
