### ISSUE TITLE
BigDecimal encoding is not compatible with Spark

### ISSUE THREAD

**Issue by blemale** [sksamuel/avro4s#271]
# Context

I'm using avro4s 2.0.3 to serialize some case classes into Parquet files using the `org.apache.parquet.avro.AvroParquetWriter`. These Parquet files are then read by a Spark 2.4 job.
The case classes I'm serializing contain `BigDecimal` so to take a minimal example: `case class MyBigDecimal(value: BigDecimal)`. 

# Issue

When I serialize my class using the default `ScalePrecisionRoundingMode` and try to read the Parquet files in Spark, I get the following exception:
```
org.apache.spark.sql.execution.QueryExecutionException: Parquet column cannot be converted in file s3a://teads-hadoop/test/batch-smoothing/2019-01-10-18-24/c2dd1921-83e9-4db1-8f19-552119806a20/c2dd1921-83e9-4db1-8f19-552119806a20.snappy.parquet. Column: [revenueSinceStart], Expected: decimal(8,2), Found: BINARY
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:187)
	(...)
Caused by: org.apache.spark.sql.execution.datasources.SchemaColumnConvertNotSupportedException
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedColumnReader.constructConvertNotSupportedException(VectorizedColumnReader.java:250)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedColumnReader.readBinaryBatch(VectorizedColumnReader.java:497)
	(...)
```

# Cause

avro4s choose to serialize all `BigDecimal` whatever the precision to a `decimal` logical type using `bytes` physical type which is perfectly fine regarding Avro spec (https://avro.apache.org/docs/1.8.1/spec.html#Decimal). This map in parquet format to a `DECIMAL` logical type backed bya `BINARY` physical type which is perfectly fine regarding Parquet spec (https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#decimal).

However Spark takes liberties with the specs to deserialize Parquet files and have custom logic.
It will read a binary column as a decimal only if the precision is bigger than 18, see:
* https://github.com/apache/spark/blob/v2.4.0/sql/core/src/main/java/org/apache/spark/sql/execution/datasources/parquet/VectorizedColumnReader.java#L471
* https://github.com/apache/spark/blob/v2.4.0/sql/catalyst/src/main/scala/org/apache/spark/sql/types/DecimalType.scala#L236
* https://github.com/apache/spark/blob/v2.4.0/sql/catalyst/src/main/scala/org/apache/spark/sql/types/Decimal.scala#L421

To be precise Spark expect the following mapping type -> precision:
* INT32 => 0 <= precision <= 9
* INT64 => 9 < precision <= 18
* BINARY => 18 < precision
* FIXED_LEN_BYTE_ARRAY => 0 <= precision
See:
* https://github.com/apache/spark/blob/v2.4.0/sql/catalyst/src/main/scala/org/apache/spark/sql/types/DecimalType.scala#L211-L242
* https://github.com/apache/spark/blob/v2.4.0/sql/catalyst/src/main/scala/org/apache/spark/sql/types/Decimal.scala#L417-L421
* https://github.com/apache/spark/blob/v2.4.0/sql/core/src/main/java/org/apache/spark/sql/execution/datasources/parquet/VectorizedColumnReader.java#L501-L538

# Workaround

Use a custom `ScalePrecisionRoundingMode` with a precision bigger than 18.

# Solution

A solution could be to provide opt-in instances of `Encoder`, `Decoder` and `SchemaFor` compatible with Spark for `BigDecimal`.

**Comment by sksamuel** [comment]
That seems a good solution. If you wish to raise a PR I will do the release.

**Comment by blemale** [comment]
How Spark write decimal in Parquet: https://github.com/apache/spark/blob/v2.4.0/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetWriteSupport.scala#L210

**Comment by sksamuel** [comment]
What happens if the precision is 0 ?

**Comment by sksamuel** [comment]
I've added a big decimal schema for that works like spark. We can build on that to add encoders and decoders.

**Comment by sksamuel** [comment]
I've had a play with the decoders and avro won't let you define a decimal type on an int or long.
`java.lang.IllegalArgumentException: Logical type decimal must be backed by fixed or bytes`

So I'm not sure how you'd be able to get the scale in order to decode an int or long.
