### ISSUE TITLE
[QUESTION] Conflict with avro using apache spark

### ISSUE THREAD

**Issue by andrelu** [sksamuel/avro4s#274]
hello everyone,

I'm trying to use avro4s with apache spark, but when a run my job on my cluster a got this exception:
` java.lang.NoSuchMethodError: org.apache.avro.Schema$Field.defaultVal()Ljava/lang/Object;`

I know that apache spark use avro 1.7.7 and i tried lots of workarounds to make it work with this library without success. Do you know some workaround that works?

Tks for everything

**Comment by sksamuel** [comment]
In spark 2.4 they are using 1.8.2
https://search.maven.org/artifact/org.apache.spark/spark-parent_2.12/2.4.0/pom

I'm not aware of much you could do other than fork the library, change the deps to 1.7.7 and then see if the code that uses `org.apache.avro.Schema$Field.defaultVal` can be replaced with another line. Then you could do an internal release until you upgrade to 2.4

For further information, 1.7.7 came out in 2014 !
Spark are notoriously slow (or conservative if you prefer) at upgrading their dependencies.

**Comment by andrelu** [comment]
We use 2.2.2 here and upgrade is not yet possible.

We find a solution: We used sbt-assembly to shade avro classes in the project an it worked!
tks

**Comment by sksamuel** [comment]
Ah great!
