### ISSUE TITLE
Huge files size compared to parquet and Spark avro

### ISSUE THREAD

**Issue by lucmolinari** [sksamuel/avro4s#279]
Hey all,

I have a reasonable big hierarchy of case classes that map a parsed XML file and sometimes these XML files can be quite big. For the numbers above, the raw XML used has 12MB.
I've realized that the avro files generated are quite huge, mainly considering it's a compressed format. So I decided to write the same case classes using other tools/formats to compare the size and they vary a lot:

* avro4s (`.data`): 3.1MB
* avro4s (`.binary`): 3.0MB
* avro spark: 344KB
* parquet spark: 66KB
* parquet using avro4s `RecordFormat` and `parquet-mr`: 62KB

As one can see, there's a huge difference between avro files generated by `avro4s` and `spark` and then another huge difference between `avro` and `parquet`. Does this make any sense? Any ideas why the avro file generated by `avro4s` is so huge?

I'm using version `1.9.0` and the code I used to write it is:

```
    val currentOs = AvroOutputStream.binary[MyType](new File("/tmp/test_avro/with_binary.avro"))
    currentOs.write(myObject)
    currentOs.flush()
    currentOs.close()
```

Thanks!

**Comment by jtvoorde** [comment]
The file is uncompressed. You should pass a compression CodecFactory using: https://github.com/sksamuel/avro4s/blob/197ebae6c567da9c2162142d24daa85e01d3523d/avro4s-core/src/main/scala/com/sksamuel/avro4s/AvroOutputStream.scala#L106

**Comment by lucmolinari** [comment]
thanks @jtvoorde , I shouldn't have missed that...now it looks correct. By using `Snappy` the file size is `282KB`, which is way better.
