### ISSUE TITLE
Scala Type DateTime is not supported.

### ISSUE THREAD

**Issue by chandradevaguptapu** [sksamuel/avro4s#28]
If i have org.joda.time.DateTime in my case class declaration, I am seeing an error while Invoking AvroInputStream . Please find below the error .It would be great if avro4s has a type matching this DateTime

**my case class** : a.b.c.d.e.pkg01.TransactionLine
Error:(90, 78) could not find implicit value for evidence parameter of type com.sksamuel.avro4s.FromRecord[a.b.c.d.e.pkg01.TransactionLine]
  val is: AvroInputStream[TransactionLine] = AvroInputStream[TransactionLine](new File("/tmp/TransactionLine.avro"))

**Comment by sksamuel** [comment]
Adding support for this means adding a dependency on joda-time, which might
not be suitable for everyone.
Perhaps there is a way we can support it as an add on module or something.

**Comment by aseigneurin** [comment]
I agree it would not be a good thing to add a dependency to JodaTime. Instead, I found we can declare converters. Here is the code:

```
package com.example

import java.io.File

import com.sksamuel.avro4s._
import org.apache.avro.Schema
import org.joda.time.DateTime
import org.joda.time.format.ISODateTimeFormat

object Sample {

  case class MyRecord(name: String, date: DateTime)

  def main(args: Array[String]) = {

    implicit object DateTimeToSchema extends ToSchema[DateTime] {
      override def apply(): Schema = Schema.create(Schema.Type.STRING)
    }

    implicit object DateTimeToValue extends ToValue[DateTime] {
      override def apply(value: DateTime): String = ISODateTimeFormat.dateTime().print(value)
    }

    implicit object DateTimeFromValue extends FromValue[DateTime] {
      override def apply(value: Any): DateTime = ISODateTimeFormat.dateTime().parseDateTime(value.toString())
    }

    val myrecord1 = MyRecord("abc", DateTime.now())

    // writing
    val os = AvroOutputStream[MyRecord](new File("/tmp/myrecords.avro"))
    os.write(Seq(myrecord1))
    os.flush()
    os.close()

    // reading
    val is = AvroInputStream[MyRecord](new File("/tmp/myrecords.avro"))
    val myrecords = is.iterator.toSet
    is.close()
    println(myrecords.mkString("\n"))
  }
}
```

I think we should add that to the documentation!

**Comment by sksamuel** [comment]
Yep easy enough.

**Comment by sksamuel** [comment]
Thanks I've used your examples to update the readme @aseigneurin

**Comment by aseigneurin** [comment]
Awesome! Thanks!

**Comment by amit4767** [comment]
what about java 8  it should support java8 time ?

**Comment by sksamuel** [comment]
@amit4767 if I make it support java8 time by default, then its java8 only. Loads of people still on java7. Very trivial to add support yourself using the examples on the readme

**Comment by amit4767** [comment]
ok... thanks .
