### ISSUE TITLE
Release 2.0.4 for Scala 2.11

### ISSUE THREAD

**Issue by alexanderzafirov** [sksamuel/avro4s#280]
Hey @sksamuel! Is it possible to do that?

**Comment by betehess** [comment]
Is there any plan to release 2.0.4 for Scala 2.11? Or maybe 2.0.5?

**Comment by alexanderzafirov** [comment]
It seems to me that Scala 2.11 is on par with the other Scala versions. @sksamuel are you planning on releasing a new version?

**Comment by sksamuel** [comment]
Yes, I will do it next day or so.

**Comment by toggm** [comment]
Still not release, right?

**Comment by keweishang** [comment]
Can you publish it please?

**Comment by frossi85** [comment]
I need it too please

**Comment by frossi85** [comment]
@sksamuel I need this too, any chance to have it soon? thanks

**Comment by obogobo** [comment]
Yeaaah unfortunately I need this as well because of Spark. A 2.11 build would be much appreciated!

**Comment by sksamuel** [comment]
Can you guys try the 3.0.x snapshot from 
https://oss.sonatype.org/content/repositories/snapshots/com/sksamuel/avro4s/avro4s-core_2.12/

This is a new version and is available for 2.11 and 2.22
