### ISSUE TITLE
RecordFormat[T].from() cannot take SpecificRecord (v2.0.4)

### ISSUE THREAD

**Issue by ChengGit** [sksamuel/avro4s#284]
Hi,

Based on the documentation on `Avro Records` v2.0.4 (see link: https://github.com/sksamuel/avro4s/blob/master/README.md#avro-records)

My understanding is that now avro4s support bi-directional conversion between a case class `T` and `avro4s.Record` by doing the following:
 - T to Record:   RecordFormat[T].to(`T instance`)
 - Record to T: RecordFormat[T].from(`Record instance`)

However, in the current version, the `RecordFormat[T].from` still takes a `GenericRecord` instead of a `Record`( see link: 
 https://github.com/sksamuel/avro4s/blob/4f8a4f14a94f209bb3685a80370d54d5ae37892a/avro4s-core/src/main/scala/com/sksamuel/avro4s/FromRecord.scala#L10)

May I know if the type of parameter `RecordFormat[T].from` is supposed to be a `Record` instead?

I am asking because we are current de/serialise our model with `io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde` to convert between specific record and binary code. So I would love to see that we could utilise `avro4s`'s power to convert between specific record and case class.

thanks for your time!

**Comment by sksamuel** [comment]
I think it might be able to have `FromRecord` accept a `IndexedRecord` which is the parent of both.

**Comment by ChengGit** [comment]
hey @sksamuel , thanks for the suggestion! now I have some time to work on it and I drafted this pr to address the issue aforementioned, if you would like to have a look?
https://github.com/sksamuel/avro4s/pull/296
Thanks for your time!

**Comment by bszmit** [comment]
Could you publish a new version with this change?

**Comment by sksamuel** [comment]
Can you try the 3.0.x snapshot from 
https://oss.sonatype.org/content/repositories/snapshots/com/sksamuel/avro4s
This should be fixed and is available for 2.11 and 2.22

**Comment by bszmit** [comment]
It works.
Thanks!
