### ISSUE TITLE
Using Generic type doesn't populate the Record correctly

### ISSUE THREAD

**Issue by dlynam01** [sksamuel/avro4s#29]
I am trying to use a generic on a function that parses my avro record using a schema. However when I use the generic it fails to set the data on the case class, when I use the explicit class on the function it works as expect. 

I've attached a working example of what I'm talking about. 
[MyApp.txt](https://github.com/sksamuel/avro4s/files/278990/MyApp.txt)

Could you explain why this doesn't work, if it should work and is it possible to fix or get around it ?

**Comment by sksamuel** [comment]
The implicits can be added by the compiler only. They cannot be added at runtime. This is because the schemas are generated _by_ the compiler. In your first example, the line `implicit val schema = AvroSchema[T]` will only execute at runtime.

Try this:

  def myFunc[T](toAvro: T)(implicit schema: AvroSchema[T]) :Unit = {
    println(s"Schema is: $schema")
    val record = ToRecord.apply[T]
    println(s"Record is $record")
    val result = record(toAvro)
    println(s"The result is $result")
  }

**Comment by dlynam01** [comment]
I don't want the schema to be created a runtime, I want to read the schema from a resource file and use that to serialise a case class I've written to json.  I use Avro to verify my case class matches the schema and produce the json representation. 
What I tried to do was to create a class that extended schemaFor and in the apply method just return my schema from a file. Is there a better way to do this ?

**Comment by sksamuel** [comment]
Your question asked why `myFuncNoGeneric` works, and why `myFunc` didn't. I answered that. 
If you are now asking can you use a schema from a file as the supplied schema to a reader/writer - no you can't. That might be worth adding.

**Comment by dlynam01** [comment]
Sorry for the misdirection, thats answered both questions thanks
