### ISSUE TITLE
Introducing type-parametrised values breaks derivation for some ADTs

### ISSUE THREAD

**Issue by Astrac** [sksamuel/avro4s#292]
I tried to reproduce an issue I am seeing on my project and I boiled it down to one example; the following code compiles:

```
sealed trait Complex

sealed trait InvertibleComplex extends Complex

case class Foo(value: String) extends InvertibleComplex

case class Bar(value: Int) extends InvertibleComplex

case class InvertibleComplexWrapper(unwrap: InvertibleComplex)

case class Invert(i: InvertibleComplexWrapper) extends Complex

object TestComplex {
  SchemaFor[Complex]
}
```

But if I add a type-parametrised class in certain places of the ADT I will end up with a diverging implicit expansion; e.g.:

```
case class Payload[A](value: A)

sealed trait Complex

sealed trait InvertibleComplex extends Complex

case class Foo(value: String, payload: Payload[String]) extends InvertibleComplex

case class Bar(value: Int) extends InvertibleComplex

case class InvertibleComplexWrapper(unwrap: InvertibleComplex)

case class Invert(i: InvertibleComplexWrapper) extends Complex

object TestComplex {
  SchemaFor[Complex]
}
```

I also tried defining the `SchemaFor` for `Payload` in `TestComplex` as follows:

```
implicit def schemaForPayload[A](implicit sf: SchemaFor[A]): SchemaFor[Payload[A]] = new SchemaFor[Payload[A]] {
    val schema = sf.schema
  }
```

This didn't change anything in the behaviour though. It's worth noting that these compile fine:

```
SchemaFor[Foo]
SchemaFor[InvertibleComplex]
```

And this doesn't either:

```
SchemaFor[InvertibleComplexWrapper]
```

I'm on 2.0.4 with scala 2.12.6.

**Comment by sksamuel** [comment]
Can you try the 3.0.x snapshot from
https://oss.sonatype.org/content/repositories/snapshots/com/sksamuel/avro4s
This should be fixed and is available for 2.11 and 2.22
