### ISSUE TITLE
Generating case classes from Json/IDL schema

### ISSUE THREAD

**Issue by stephendrew** [sksamuel/avro4s#30]
Hi,

In the readme, it says "Class generation from schemas at build time".

I can't quite work out how to go about this though - do you have any pointers?

Thanks,
Stephen

**Comment by sksamuel** [comment]
Yep, this is what you need. https://github.com/sksamuel/sbt-avro4s

**Comment by stephendrew** [comment]
Thanks

**Comment by pmatpadi** [comment]
Hello, we use gradle for builds. How can I get class generation to work at build time in gradle?
