### ISSUE TITLE
Enum type for Scala enumerations

### ISSUE THREAD

**Issue by antoinesauray** [sksamuel/avro4s#305]
Hello 👋

We are using sealed trait and case objects to create enumerations. Those are serialized as enum by avro4s. We'd like to have it serialized as String because we find the enum type to be too restrictive for our use case (changes of our sealed trait will occur in the future)

Is there a way to change this type ? We have tried using the custom mappings without success https://github.com/sksamuel/avro4s#custom-type-mappings

**Comment by sksamuel** [comment]
If you bring an implicit in scope does that not override?

**Comment by antoinesauray** [comment]
When I tried to reproduce I got this working. I guess my implicit was not in scope. I'm closing this
