### ISSUE TITLE
NPE on schema generation for case classes with nullable fields

### ISSUE THREAD

**Issue by SavtechSolutions** [sksamuel/avro4s#306]
```
package test

import com.sksamuel.avro4s.AvroSchema

case class TestClass(name: String = null)

object TestAvroSchema extends App {
  println(AvroSchema[TestClass])
}
```

results in

```
Exception in thread "main" java.lang.NullPointerException
	at org.apache.avro.util.Utf8$2.toUtf8(Utf8.java:123)
	at org.apache.avro.util.Utf8.getBytesFor(Utf8.java:172)
	at org.apache.avro.util.Utf8.<init>(Utf8.java:39)
	at com.sksamuel.avro4s.Encoder$StringEncoder$.encode(Encoder.scala:74)
	at com.sksamuel.avro4s.Encoder$StringEncoder$.encode(Encoder.scala:69)
	at com.sksamuel.avro4s.SchemaFor$.schemaFieldWithDefault(SchemaFor.scala:299)
	at test.TestAvroSchema$$anon$1.<init>(TestAvroSchema.scala:8)
	at test.TestAvroSchema$.delayedEndpoint$test$TestAvroSchema$1(TestAvroSchema.scala:8)
	at test.TestAvroSchema$delayedInit$body.apply(TestAvroSchema.scala:7)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at test.TestAvroSchema$.main(TestAvroSchema.scala:7)
	at test.TestAvroSchema.main(TestAvroSchema.scala)
```

Is this use case not being supported? Seems fairly common to have a default for nullable field

**Comment by lacarvalho91** [comment]
@SavtechSolutions the way you encode an optional (nullable) field in your case class is to use a Scala `Option` so your example would be `case class TestClass(name: Option[String] = None)`

**Comment by SavtechSolutions** [comment]
I'm not asking whether I'm mapping my classes correctly or not, though.
Sometimes the mapping choice isn't under my control, and I don't think it's
framework's purpose to dictate a "proper" mapping design, it should try to
do its best with whatever valid class it's given. Giving an NPE for such a
simple case is definitely not right.

**Comment by lacarvalho91** [comment]
I wouldn't expect many scala libraries to support that. You're setting a string default value to null, I wouldn't expect any outcome other than a NPE. 

It is indeed a common case to have a nullable field in an avro schema as that is how avro encodes optional fields. That is not how you would encode an optional field in scala though, you would use an `Option` as this library does. Using what I suggested above would result in what you want, which is an avro schema with a nullable 'name` field.

**Comment by SavtechSolutions** [comment]
You're missing my point - you're still trying to argue what is the "proper" way of null representation, while I'm saying that it's not up to a framework to have a say in that. That's what separates enterprise-level frameworks from the academic ones, as the former do realize that the object modeling is not always done in the "proper" way, and there's often not much flexibility to change that, for a multitude of reasons (the model might be owned by another team, for example; it could be generated; optional types might not be used at all, for concerns of Java interop; etc.). In the end, any of these potential concerns far outweigh the framework's "purist" stance, and would more often lead to the framework not being selected for the stack, rather than actually changing the object model. That's just how things work in the enterprise, unfortunately.

Speaking of Scala frameworks - in my experience, most actually do bother to handle nulls properly. Spark, Ignite scalar, json4s - none of them have any issues with nulls. In fact, neither does avro4s in some cases - setting an Option field to null (instead of None), for example, serializes the field as Avro null. So the NPE that I experienced is not even a stylistic stance taken by the framework developers - it's simply an oversight. Which needs to be fixed.

**Comment by sksamuel** [comment]
@SavtechSolutions you want the default value of null to indicate that the field can be nullable? I think the framework should support nulls passed into it as values, but as indicators of type? Are you actually defining your case classes like this or do you have some java classes or something?

**Comment by sksamuel** [comment]
Can you try the 3.0.x snapshot from 
https://oss.sonatype.org/content/repositories/snapshots/com/sksamuel/avro4s
Any field with a default value of null will be encoded as a nullable union as you wanted @SavtechSolutions

**Comment by SavtechSolutions** [comment]
@sksamuel Sorry, was away, and missed all the action. Yes, I can confirm the 3.0 snapshot is working properly with the nullable fields. Great job, I'll be waiting for the release version. On an unrelated note, thanks for supporting Scala 2.11 in the new snapshot - a number of other frameworks we're using are still at 2.11.
