### ISSUE TITLE
Unable to deserialize Avro message (ProducerRecord) send from Java Kafka producer

### ISSUE THREAD

**Issue by yohei1126** [sksamuel/avro4s#309]
I am trying to deserialize Avro format data sent from Java Kafka producer in Apache Beam application. But it failed with the error mentioned below.

* Kafka Producer (Java) sends data as `ProducerRecord`.
* Producer get schema from Schema Registry and serialize using `KafkaAvroSerializer`.
* Note: Avro Schema is generated using `avro4s` and register it to Schema Registry in advance.
```
// use KafkaAvroSerializer and Schema Registry
props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, KafkaAvroSerializer.class);
props.put(AbstractKafkaAvroSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG, schemaRegistryUrl);
props.put(AbstractKafkaAvroSerDeConfig.AUTO_REGISTER_SCHEMAS, false);

final Transaction transaction = new Transaction(transactionId, data);
final ProducerRecord<Long, Transaction> record = new ProducerRecord<>(TOPIC, new Random().nextLong(), transaction);
```

* Consumer (Scala; Apache Beam) tries to deserialize data using AvroInputStream

```
val  byteArray: Array[Byte] = xxx
val is = AvroInputStream.binary[EPCTransaction].from(byteArray).build(schema)
is.close()
```

Then I got the following error. This might be similar issue as this one https://stackoverflow.com/questions/42328506/malformed-data-length-is-negative-while-deserializing-avro-class

```
Malformed data. Length is negative: -40, org.apache.avro.AvroRuntimeException: Malformed data. Length is negative: -40
	at org.apache.avro.io.BinaryDecoder.doReadBytes(BinaryDecoder.java:336)
...
```

* I also tested the same data with local test as below
* I used the same data that the Apache 

```
  "AvroSchema" should "serialize / deserialize Java object2" in {
    val hex = "xxx"
    val byteArray = BaseEncoding.base16().decode(hex)
    val is = AvroInputStream.binary[EPCTransaction].from(byteArray).build(schema)
    is.close()
    assert(true)
  }
```

Then I got this error.

```
 java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 343
[info]   at com.google.common.io.BaseEncoding.decode(BaseEncoding.java:219)
```

So avro4s does not support Avro message serialized using Kafka producer (Java) and Schema Registry?

**Comment by klass-ivan** [comment]
The avro4s uses native apache avro format, it does not use SchemaRegistry ( which is supported by Confluent inc). Looks like you're trying to de-serialize data written by confluent serializer. It prepends binary data with schema id (in registry). That means, when reading confluent-written data, you probably should extract a schema Id from initial bytes, then lookup the schema in registry, and then deserialize other bytes using that schema

**Comment by yohei1126** [comment]
yep it works with custom KafkaAvroDeserilizer

**Comment by Taqi1234** [comment]
We need to look up rest of the byte array other than Id and deserialise it by latest look up from schema registry ?
