### ISSUE TITLE
Removing namespace entirely

### ISSUE THREAD

**Issue by alexjg** [sksamuel/avro4s#316]
As far as I can tell it's valid for a schema to not have a namespace. More to the point I'm writing code that interacts with a legacy schema which has no namespace so I need a way to remove the namespace entirely from the generated schema. Would it make sense to modify the `AvroNamespace` annotation so that it takes an `Option[String]` rather than a `String`?

**Comment by sksamuel** [comment]
We could if we can make it so it's backwards compatible.

**Comment by alexjg** [comment]
One obvious solution would be to add an `AvroNamepaceOmitted` (or similar) annotation.

I think you could also introduce a new type for the parameter to the `AvroNamespace` annotation with an implicit conversion from `String` to that type, but I can't figure out how you would bring the implicit conversion into scope at the call site.

**Comment by sksamuel** [comment]
Can we have overloadd constructors on an annotation

**Comment by alexjg** [comment]
Oh good point, I've just come back to Scala from a month or two with Go (:nauseated_face:)  and completely forgot that we can overload.

If that's an acceptable approach I'll have a crack at it this week.

**Comment by sksamuel** [comment]
It doesn't seem possible to have apply methods for annotations. I don't want to change the type of AvroNamespace to Option if it means it breaks other code.

However I have been able to get this to work by using the empty string.
https://github.com/sksamuel/avro4s/blob/master/avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/AvroNamespaceSchemaTest.scala#L61-L68

**Comment by alexjg** [comment]
Ah that does the trick nicely. It's slightly surprising that you also need to apply the `@AvroNamespace("")` annotation to any nested records, but not really a problem. Thanks!

**Comment by sksamuel** [comment]
It's because the nested record would go back to the package name, which is the default behaviour.
What you probably want is @AvroEmptyNamespaceAndAllChildren

**Comment by alexjg** [comment]
I'm not sure it's worth the additional effort though. Certainly for my usecase I'm happy to just annotate the nested records in question. I'm happy to close this issue.
