### ISSUE TITLE
Error getting SchemaFor instance for Coproduct with ADT

### ISSUE THREAD

**Issue by ivanobulo** [sksamuel/avro4s#318]
There is a problem deriving schema for the Coproduct that has an ADT.

```scala
sealed trait MyAdt
object MyAdt {
  case class Foo(name: String) extends MyAdt
  case class Bar(id: Int) extends MyAdt
}
case class CoproductWithAdt(cp: MyAdt :+: Boolean :+: CNil)
```
`SchemaFor[CoproductWithAdt]` produces compilation error

> Error:(27, 36) diverging implicit expansion for type com.sksamuel.avro4s.SchemaFor[com.sksamuel.avro4s.schema.CoproductWithAdt]
starting with macro method applyMacro in object SchemaFor
    SchemaFor[CoproductWithAdt]

**Comment by sksamuel** [comment]
Which version?

**Comment by ivanobulo** [comment]
current master

**Comment by sksamuel** [comment]
I added a test for your use case and it compiles in master.

Test;
https://github.com/sksamuel/avro4s/blob/master/avro4s-core/src/test/scala/com/sksamuel/avro4s/github/Github318.scala

Build:
https://travis-ci.org/sksamuel/avro4s/builds/535552083

**Comment by ivanobulo** [comment]
My bad. I had 6 day old fork of master and it was failing there. After syncing with upstream I can confirm it works now!
Looks like a lot was changed since then. Great work!
