### ISSUE TITLE
AvroSchema[MyCaseClass] generates builds error

### ISSUE THREAD

**Issue by Vesli** [sksamuel/avro4s#321]
So I'm trying the very basic of your library:

build.sbt:
```

scalaVersion := "2.12.8"
val sparkVersion = "2.4.3"


val sparkLibraries = Seq(
  "org.apache.spark" %% "spark-core" % sparkVersion,
  "org.apache.spark" %% "spark-sql" % sparkVersion,
  "org.apache.spark" %% "spark-sql-kafka-0-10" % sparkVersion
)

val commons = Seq(
  "com.github.scopt" %% "scopt" % "3.7.1",
  "com.lucidchart" %% "xtract" % "2.0.0",
  "com.sksamuel.avro4s" % "avro4s-core_2.11" % "3.0.0-RC2"
)
```
from those case classes:

```
package org.cpmy.scorespro_parser.models

case class Sport (
                   code: String,
                   id: String,
                   name: String,
                   hid: String,
                   lineup_hid: String,
                   commentary_hid: String,

                   MatchDays: Seq[Matchday] (more nested case class to map an xml)
                 )

case class Wrapper (
                     Sports: Seq[Sport]
                   )
```
being called at the beginning of my program:

```
import com.sksamuel.avro4s.{AvroSchema}
...

 val wrapper = parseXml(xml)
 val schema = AvroSchema[Wrapper]

 { some other code... }
```

this produce those errors:

> Error:(150, 28) could not find implicit value for parameter schemaFor: com.sksamuel.avro4s.SchemaFor[org.cpmy.scorespro_parser.models.Wrapper]
    val schema = AvroSchema[Wrapper]

> Error:(150, 28) not enough arguments for method apply: (implicit schemaFor: com.sksamuel.avro4s.SchemaFor[org.cpmy.scorespro_parser.models.Wrapper], implicit namingStrategy: com.sksamuel.avro4s.NamingStrategy)org.apache.avro.Schema in object AvroSchema.
Unspecified value parameter schemaFor.
    val schema = AvroSchema[Wrapper]

any idea about what's going wrong? Should I use another version of avro4s?

Many thanks

**Comment by sksamuel** [comment]
Can you try the latest 3.0 snapshot ?

**Comment by Vesli** [comment]
Hey, thanks for your quick answer, is this one not the latest one?

https://search.maven.org/artifact/com.sksamuel.avro4s/avro4s-core_2.11/3.0.0-RC2/jar

**Comment by Vesli** [comment]
Actually, taking it from there:
https://mvnrepository.com/artifact/com.sksamuel.avro4s/avro4s-core_2.12/3.0.0-RC2

has the build pass.

**Comment by sksamuel** [comment]
No, that's the latest release, but there's newer snapshots. See the badge on the home page, they are built from every build.

**Comment by Vesli** [comment]
Alright, this solves that :)

Thank you for your reactivity!
