### ISSUE TITLE
sealed trait of case objects encoded as union

### ISSUE THREAD

**Issue by lacarvalho91** [sksamuel/avro4s#326]
When trying out `3.0.0-RC2` I noticed that sealed trait of case objects are being encoded as a union of records instead of an enum.

```scala
object Main extends App {
  sealed trait Foo extends Product with Serializable

  case object Bar extends Foo
  case object Baz extends Foo

  case class Schema(foo: Foo)

  println(AvroSchema[Schema])
}
```

Produces the following schema:

```
{
  "type" : "record",
  "name" : "Schema",
  "namespace" : "some.package.Main",
  "fields" : [ {
    "name" : "foo",
    "type" : [ {
      "type" : "record",
      "name" : "Bar",
      "fields" : [ ]
    }, {
      "type" : "record",
      "name" : "Baz",
      "fields" : [ ]
    } ]
  } ]
}
```

UPDATE: as highlighted by @sksamuel below: this problem does not occur if `Foo` and the case objects are not defined inside an object.

**Comment by lacarvalho91** [comment]
Seeing the same on the latest snapshot too

**Comment by sksamuel** [comment]
There is already a test for this:
https://github.com/sksamuel/avro4s/blob/master/avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/SealedTraitSchemaTest.scala#L32-L36

But I will add your use case as as test as well to see.

**Comment by sksamuel** [comment]
It fails when the classes are nested.

**Comment by lacarvalho91** [comment]
Ah, yeah when I was trying it all the code from my example was in an object. It behaves correctly when moving `Foo` and the case objects out of the object. I will update the description to include the outer object

**Comment by sksamuel** [comment]
I've pushed a fix. Give it 10 minutes to build and try the latest snapshot.

**Comment by lacarvalho91** [comment]
Wow, that was fast. Thanks - I'll give it a try.

**Comment by lacarvalho91** [comment]
Looks like it works! Thanks @sksamuel

**Comment by sksamuel** [comment]
:+1:

**Comment by lacarvalho91** [comment]
@sksamuel any plans to release another RC?

**Comment by sksamuel** [comment]
I will once I figure out what to do with https://github.com/sksamuel/avro4s/pull/324

You can use the snapshot in the meantime.
