### ISSUE TITLE
Add refined module

### ISSUE THREAD

**Issue by lacarvalho91** [sksamuel/avro4s#327]
I think it would be cool if there was a [refined](https://github.com/fthomas/refined) module, providing avro4s typeclass instances for refined types. 

I have some experience with this so would be happy to give it a go.

I envision it being setup same way as the cats module.

Let me know what you think!

**Comment by sksamuel** [comment]
Sounds good.

**Comment by lacarvalho91** [comment]
@sksamuel hoping to raise a PR today. Just wondering though if I should have the sbt module for it commented out like the cats one currently is? Or shall I uncomment the cats one as part of this PR?
