### ISSUE TITLE
AvroDoc annotation and shapeless coproducts  

### ISSUE THREAD

**Issue by marcodippy** [sksamuel/avro4s#331]
Hello, I'm facing this issue while trying to update to avro4s 3.0.0-RC2 (I also tried the latest snapshot version): if I have a shapeless coproduct in a class (or somewhere nested), adding an `@AvroDoc` at any place ends up in a compilation error `java.lang.AssertionError: assertion failed: new com.sksamuel.avro4s.AvroDoc("my doc")` 

this is an example 

```scala
import com.sksamuel.avro4s._
import shapeless.{:+:, CNil}

@AvroDoc("my doc")
case class MyCaseClass(myCoproduct: String :+: Int :+: CNil)

object MainApp extends App {
  println(AvroSchema[MyCaseClass].toString(true))
}
```

**Comment by sksamuel** [comment]
I can confirm this happens but the issue is in https://github.com/propensive/magnolia
I wouldn't expect a fix in the short term.

**Comment by TJSomething** [comment]
Is this the same as this issue (https://github.com/propensive/magnolia/issues/154)?

**Comment by TJSomething** [comment]
I should add that I'm getting a similar error, but it took me a while to come up with a small test case. It seems that the error can be caused without Shapeless and happens with any annotation.

```scala
import com.sksamuel.avro4s._

object Main extends App
{
  type OptionInt = Option[Int]
  @AvroNamespace("org.github.tjsomething")
  case class Foo(x: Seq[OptionInt])

  println(AvroSchema[Foo].toString)
}
```

In practice, I'm going to work around this for now by inlining the type alias. But just in case anyone
