### ISSUE TITLE
Is there a way to remove default value from schema?

### ISSUE THREAD

**Issue by a-panchenko** [sksamuel/avro4s#333]
I have a case class like 
```
case class Foo(time: OffsetDateTime = OffsetDateTime.now())
```
Avro4s produces
```
"default" : 1560266788385 
```
in the schema json. Is there any way to disable this feature?

**Comment by sksamuel** [comment]
Ah so you want the default in scala but not in avro. I can add that via
annotation @AvroNoDefault or something like that.

**Comment by a-panchenko** [comment]
Yes, that'd be perfect. Thanks!

**Comment by sksamuel** [comment]
Added @AvroNoDefault to master. You can try the latest snapshots.
