### ISSUE TITLE
`AvroBinaryInputStream.hasNext ` throws exception, even if using `tryIterator`

### ISSUE THREAD

**Issue by vladimir-lu** [sksamuel/avro4s#338]
In 2.0.4, the implementation of `Iterator.hasNext` for `AvroBinaryInputStream` delegates to `GenericDatumReader` to check whether there is a next element. This throws an exception if next element is malformed, which is surprising. I propose wrapping the call to hasNext in a try and returning true even if there was an error.

To reproduce:

```scala
import scala.collection.JavaConverters._
import org.apache.avro.{Schema}
import com.sksamuel.avro4s.{AvroInputStream, Decoder}

final case class AB(a: Boolean, b: Int)

implicit val decoder = Decoder.applyMacro[AB]

val abSchema = Schema.createRecord("record", "", "a", false, List(
    new Schema.Field("a", Schema.create(Schema.Type.BOOLEAN), "", false),
    new Schema.Field("b", Schema.create(Schema.Type.INT), "", 42),
).asJava)

val schema = Schema.createUnion(abSchema, Schema.createArray(Schema.create(Schema.Type.FLOAT)))

val s = AvroInputStream.binary[AB].from(Array(0xd.toByte, 0x22.toByte, 0xc.toByte)).build(schema)
s.tryIterator.hasNext // throws ArrayIndexOutOfBoundsException
```

(I'm not sure how to reproduce the `ArrayIndexOutOfBoundsException` without using a union type, but this is what we actually got in production)

**Comment by sksamuel** [comment]
I would suggest upgrading to a 3.0 snapshot, or raising a PR to fix in the 2.x branch if you wish to stick with the 2.0 releases.

**Comment by sksamuel** [comment]
Can you try 3.0.0-RC3.
