### ISSUE TITLE
no support for immutable Seq?

### ISSUE THREAD

**Issue by francisdb** [sksamuel/avro4s#339]
Scala `2.12`
Avro4s `3.0.0-RC1`

I was just playing around with the Pizza examples and adding `import scala.collection.immutable.Seq` seems to cause schema generation to fail

```
could not find implicit value for parameter schemaFor: com.sksamuel.avro4s.SchemaFor[test.Pizza]
[error]     val schema = AvroSchema[Pizza]
```

**Comment by sksamuel** [comment]
Which version

**Comment by francisdb** [comment]
Ticket was updated after initial post with more info

**Comment by francisdb** [comment]
I do not have that problem with `2.0.4`

Is this correct?
<img width="617" alt="image" src="https://user-images.githubusercontent.com/161305/60086143-da6d3c00-973a-11e9-8f11-ec37d20d664f.png">

**Comment by francisdb** [comment]
I see that this has been fixed in Avro4s `3.0.0-RC2`, by the way the release tag for that version is missing in Git

**Comment by francisdb** [comment]
was a bit too fast, not fixed

**Comment by francisdb** [comment]
Going to send a pull request to fix this
