### ISSUE TITLE
Serialization for generics in a list fails due to diverging implicit expansion

### ISSUE THREAD

**Issue by Smeb** [sksamuel/avro4s#348]
Using version 2.0.2, Scala 2.11 / 2.12, I get the following compile error:
```
diverging implicit expansion for type com.sksamuel.avro4s.SchemaFor[Wrapper[O]]
```
The following example reproduces the issue (where O has a `SchemaFor` context bound):
```
case class Wrapped[O](item: O)
case class Wrapper[O](
  list: List[Wrapped[O]]
)
SchemaFor[Wrapper[O]]
```

If I was to do, say:
```
case class Wrapper[O](
  list: List[Option[O]]
)
SchemaFor[Wrapper[O]]
```

Then I don't get the error. Do I need to explicitly declare the schema for cases like this?

**Comment by Smeb** [comment]
Update - adding this worked:
```
object SchemaExtensions {
  implicit def schemaForWrapper[O : SchemaFor]: SchemaFor[Wrapper[O]] = {
    SchemaFor[Wrapper[O]]
  }
}
```

**Comment by sksamuel** [comment]
Ok good. Also try the 3.0.x snapshots.

**Comment by Smeb** [comment]
Okay, the initial response didn't work (it compiled but was infinitely recursive). This does work (both at runtime and compile time):

```
def schemaForWrapper[O : SchemaFor]: SchemaFor[Wrapper[O]] = SchemaFor[Wrapper[O]]
implicit val schema = schemaForWrapper[O]
```

**Comment by sksamuel** [comment]
Ok closing this if the workaround is good.
