### ISSUE TITLE
Consuming schema registry Id

### ISSUE THREAD

**Issue by Flamma** [sksamuel/avro4s#363]
We are consuming models from a providers, and it seems that for some of the feeds the provider is now putting the schema registry Id, making the deserialization fail. The guys have implemented this workaround:
`@AvroNamespace("namespace") case class MessageModel(
    b1: Byte,
    b2: Byte,
    b3: Byte,
    b4: Byte,
    b5: Byte,
    // 5 first bytes are the schema ID in hte registry
    field 1:    Long,`

Can I avoid this?

**Comment by sksamuel** [comment]
Confluent add those magic bytes when you use their serializer.
Just serialize without using it, or strip the bytes off before you decode

**Comment by Flamma** [comment]
What I mean is: is there anyway that avro4s can know those bytes are an id, and skipping them without me having to do it manually?

**Comment by sksamuel** [comment]
No, avro4s deals purely with Avro format. If you are using Kakfa you'd need
to do some conversion.

**Comment by Flamma** [comment]
Thank you, that's what I needed to know.
