### ISSUE TITLE
Overriding Avro name and namespace coupled to package name?

### ISSUE THREAD

**Issue by flybonzai** [sksamuel/avro4s#366]
When trying to create the Schema and RecordFormat classes, we are getting the following: `could not find implicit value for parameter schemaFor: com.sksamuel.avro4s.SchemaFor[api.entities.Metadata]`.  We are overriding them with annotations, but the overrides don't match the package name, thus leading to the above error.  Do we need to create a `SchemaFor[T]` in scope just to have the name overridden correctly?

**Comment by sksamuel** [comment]
The annotations are nothing to do with the implicit search. They're used
only at runtime.

**Comment by sksamuel** [comment]
I think non-literal strings is breaking the underlying macros that avro4
uses.
