### ISSUE TITLE
ADT

### ISSUE THREAD

**Issue by Fristi** [sksamuel/avro4s#37]
Given (defined in a different module, nesting the case class in a companion object `UserEvent` also doesn't work)

```scala
sealed trait UserEvent
case class Registered(id: UUID, name: String, email: String, password: String) extends UserEvent
case class EmailUpdated(id: UUID, email: String) extends UserEvent
case class PasswordUpdated(id: UUID, newPassword: String) extends UserEvent
case class LoggedIn(id: UUID, newPassword: String) extends UserEvent
```

Running
```scala
  val schema = AvroSchema[UserEvent]

  println(schema.toString(true))
```

Gives
```
{
  "type" : "record",
  "name" : "UserEvent",
  "namespace" : "statements.example",
  "fields" : [ {
    "name" : "newPassword",
    "type" : [ "null", "string" ]
  }, {
    "name" : "name",
    "type" : [ "null", "string" ]
  }, {
    "name" : "email",
    "type" : [ "null", "string" ]
  }, {
    "name" : "id",
    "type" : [ "string" ]
  }, {
    "name" : "password",
    "type" : [ "null", "string" ]
  } ]
}
```

I would expect a enum here. It should also include a discriminator field (like `type` or something)

As a side note, can't we use the shapeless type class derivation trick to create product and coproduct instances for `SchemaFor[T]` ?

WDYT?

**Comment by sksamuel** [comment]
I don't think enums can have fields. https://avro.apache.org/docs/1.8.1/spec.html#Enums

**Comment by Fristi** [comment]
Ah, nice point. Are ADT's supported in avro4s by the way?

If not, I see all fields from all case classes are encoded though and they are optional right ?? Maybe we can add a type field to discriminate over the cases to support this use-case

**Comment by Fristi** [comment]
If that's possible, it would be interesting how schema evolution works out on this..

**Comment by sksamuel** [comment]
It's difficult to do, because of the loss of type information, schema evolution, etc. You can use the trait and all the non-universal fields are encoded as unions of type,null. So it works to a certain extent. There comes a point where the richness of Scala's typesystem and Avro just are too far apart to make it work imo.

**Comment by Fristi** [comment]
Let's put this idea to rest then.
