### ISSUE TITLE
add support for TreeSet

### ISSUE THREAD

**Issue by Zhen-hao** [sksamuel/avro4s#372]
I see that TreeSet is missing from the supported Scala types. I wonder if there are some intrinsic difficulties in supporting. I am willing to collaborate on this if it is not done yet.

**Comment by sksamuel** [comment]
You would just need to add an encoder, decoder, and schemafor instances to
the existing files.

**Comment by Zhen-hao** [comment]
Thank you for the fast response! 
Do you mean to add to Encoder.scala? Decoder? 
To serialize SortedSet and SortedMap, I think we need to manage to serialize lambda functions used by sorting.

**Comment by Zhen-hao** [comment]
now I am thinking of it, my proposed approach is not that good. Basically, it focuses on the performance of serialization and de-serialization on the Scala side. Serializing lambda functions has to produce binary data which non-jvm language will not understand. I think it is better to convert sorted sets and sorted maps to Avro arrays which all different consuming languages can decode.

**Comment by Zhen-hao** [comment]
After thinking it for a while, I think it is better to do the conversion as user side logic instead of offloading it to the library. For example, the serialization of a `TreeSet[A]` can be made in two steps. 1. convert to a representation class `case class TreeSetSeqRep[A](rep: Seq[A])` and then serialize.
