### ISSUE TITLE
Error with default values on custom types serialized as Strings

### ISSUE THREAD

**Issue by larochef** [sksamuel/avro4s#378]
I have an issue if I want a custom mapping on ZonedDateTimes, that I want to encode as ISO Strings (which I was doing fine in older versions).

I have a case class with a ZonedDateTime. Without any default value, all works fine. If I set a default value on the date, I have the following error:

`org.apache.avro.AvroRuntimeException: Unknown datum class: class java.time.ZonedDateTime`

Here is my code to reproduce:

```scala
package com.sksamuel.avro4s.github

import java.time.ZonedDateTime

import com.sksamuel.avro4s.{AvroSchema, Decoder, Encoder, FieldMapper, SchemaFor}
import org.apache.avro.{Schema, SchemaBuilder}
import org.scalatest.{FunSuite, Matchers}

class Github378 extends FunSuite with Matchers {

  implicit object ZonedDateTimeSchemaFor extends SchemaFor[ZonedDateTime] {
    override def schema(fieldMapper: FieldMapper): Schema =
      SchemaBuilder.builder.stringType
  }

  implicit object ZonedDateTimeEncoder extends Encoder[ZonedDateTime] {
    override def encode(t: ZonedDateTime, schema: Schema, fieldMapper: FieldMapper): AnyRef =
      t.toString
  }

  implicit object ZonedDateTimeDecoder extends Decoder[ZonedDateTime] {
    override def decode(value: Any, schema: Schema, fieldMapper: FieldMapper): ZonedDateTime =
      ZonedDateTime.parse(value.toString)
  }

  test("Error building schemas with custom types serialized as Strings") {
    AvroSchema[Github378Model].toString()
  }
}

final case class Github378Model(date: ZonedDateTime = ZonedDateTime.now())
```

My problem is that I really need these default values

**Comment by larochef** [comment]
After looking at the code, it feels like something is wrong with default values. 

I think that the de `DefaultResolver` should try to find an appropriate `Encoder` for the default value, instead of having a list of conversions that are supported. Else, it will be hard to support custom types.

What do you think?

**Comment by larochef** [comment]
looks like it is hard to have an access at that point to the encoder at that point.

It's not really great, but adding the following case in `com.sksamuel.avro4s.DefaultResolver` works:

`case other if schema.getType == Type.STRING => other.toString`

it's not great though since it forces users to use the toString method.

**Comment by bobbyrauchenberg** [comment]
@larochef it wouldn't be possible to use an `Encoder` 

The defaults are resolved as part of the schema creation, and `Encoder` has a requirement of  a schema instances

Furthermore `Encoder` encodes into an `ImmutableRecord` which is a mix of `GenericRecord` and `SpecificRecord` whereas the java api for `Schema` does validation over a specific set of types which can be used as defaults - that's what's generating the error you're seeing

**Comment by bobbyrauchenberg** [comment]
In case it wasn't clear from my previous answer - those type constraints on the default value are imposed by the underlying Java Avro library, so even if we come up with something at the scala level, you still need to comply to the underlying java lib

**Comment by larochef** [comment]
Hello @bobbyrauchenberg, I understand very well that we need to give to avro only types it can handle. I also understand very well the exception I get when I run my code and why I get it.

I don't really see the issue with encoders needing the schema, since an instance of `SchemaFor` is provided as an implicit (in my example, I also provide the encoder implicitely).

thinking more about it, I feel like we'd need a typeclass that would mix Encoder, Decoder and SchemaFor. 

When looking at the documentation, there is an example doing the same as I want: https://github.com/sksamuel/avro4s#custom-type-mappings using plain Strings to encode / decode to and from the avro values, but default values was not included in the example. Since we have custom types, it cannot be one of these default java types directly. I felt that the encoders would be the right tool to turn the custom value into an avro/simple java type

**Comment by sksamuel** [comment]
I think the easiest way forward for now is just to overload the `DefaultResolver` with knowledge of more types. I think it's fine to match on anything that's built into the JDK. Do you want to raise a PR for the date types @larochef  ?

**Comment by sksamuel** [comment]
We could update the schema for typeclass to support generate the default values as well. That might be nicer.

**Comment by larochef** [comment]
Hi and sorry for the delay.

I could add support for the dates, but still, it wouldn't be enough for me to migrate to version 3.0: I have historical data for which I need compatible schemas. If the schema for dates move from String (which I currently have) to Long, then it won't work. I also have a few other types like enums for which the encoded values are custom.

**Comment by larochef** [comment]
@sksamuel I've pushed a PR with a solution that would work for me: it consists in adding an annotation with the default value, as a String, and do the best possible to make it compatible with the schema of the field.

What do you think?

**Comment by larochef** [comment]
@sksamuel did you have a change to look at the PR? 

Please tell me if you'd like anything changed, or if you think of another way to do it better.
