### ISSUE TITLE
Maybe 'Record' should not extend both 'GenericRecord' and 'SpecificRecord'?

### ISSUE THREAD

**Issue by yeryomenkom** [sksamuel/avro4s#385]
Hi!
We (hello @maxstreese) use avro4s together with [confluent_serdes](https://github.com/confluentinc/schema-registry/tree/master/avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro) in our project.
And we found weird serializing performance issue today.
That's how we create serdes (simplified a bit) :
```
private def createSerde[T >: Null](genericSerde: GenericAvroSerde, format: RecordFormat[T]): Serde[T] = {
    val serde: Serde[T] = Serdes.fromFn(
      serializer = (topic, value) => {
        if (value == null) null
        else genericSerde.serializer().serialize(topic, format.to(value))
      },
      deserializer = ???
    )

    serde
  }
```
And, if we will try to use this serde, for 50K records we will get the next timings:
```
Serde serialization. Time: 3.671 seconds.
Serde deserialization. Time: 0.409 seconds.
```
The reason lives inside the implementation of `AbstractKafkaSerializer` [link](https://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java#L88).
As you can see, it always treats container value as `SpecificRecord`, since `Record` is indeed a proper implementation of `SpecificRecord`.
If we will use workaround and just wrap `Record` in the `WrappedRecord`:
```
class WrappedRecord(val record: Record) extends GenericRecord {
  override def put(key: String, v: Any): Unit = record.put(key, v)
  override def get(key: String): AnyRef = record.get(key)
  override def put(i: Int, v: Any): Unit = record.put(i, v)
  override def get(i: Int): AnyRef = record.get(i)
  override def getSchema: Schema = record.getSchema
}
```
the timings will be the the following:
```
Serde serialization. Time: 0.683 seconds.
Serde deserialization. Time: 0.409 seconds.
```

What do you think about all this situation? Do we do something wrong? Or maybe we should use another workaround?

Thanks!

**Comment by sksamuel** [comment]
The implement of Record is `case class ImmutableRecord(schema: Schema, values: Vector[AnyRef]) extends Record`
So I guess the vector is slow with indexed lookup and if it's using the specific record (get by index) then it might be slow. In your wrapper it might be using the get by key? 
We could try changing the record implementation to using an array.

**Comment by yeryomenkom** [comment]
My wrapper just wraps `ImmutableRecord`. Yes, I think `get(key: String)` method can be improved in terms of performance.
But, in any case, how about this problem with distinguishing `GenericRecord` and `SpecificRecord`? I think it is a problem because java code, that uses `Record`, has no way to understand what is it. 
What do you think?

**Comment by yeryomenkom** [comment]
Maybe we should have something like: 
```
trait ToRecord[T] extends Serializable {
  def toGeneric(t: T): GenericRecord
  def toSpecific(t: T): SpecificRecord
}
```
?

**Comment by sksamuel** [comment]
A Record is a GenericRecord. And a SpecificRecord.

val r : SpecificRecord = record.

**Comment by yeryomenkom** [comment]
> A Record is a GenericRecord. And a SpecificRecord.

And this is a problem.
Take look on the implementation here:
https://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java#L88

It means that even if I would like my `Record` to be treated as GenericRecord, I have no chance to achieve that.

**Comment by sksamuel** [comment]
But that's not a problem other than performance right ?
And switching to Arrays should solve that problem.

**Comment by yeryomenkom** [comment]
If we will introduce ability to serialize our case class into `SpecificRecord` or `GenericRecord`, we also will be able to use appropriate data structure for the fields. Lets say `Map` for `SpecificRecord` and `Array` for `GenericRecord`

**Comment by sksamuel** [comment]
I feel like the general purpose structure can still work. The get by key
just looks up the index in a map. Then the array is indexed. I'm doing this
in avro4k.

**Comment by yeryomenkom** [comment]
> But that's not a problem other than performance right ?

In this particular case yes) But in general how can I distinguish between SpecificRecord and GeneralRecord if I will get object of the type `Record`? Lets say that I am designing a new library for working with kafka serdes. And I have a method that takes parameter of type `GenericContainer`. And inside that method I wanna do 'x' if this container is `GenericContainer` and do 'y' if it is `SpecificContainer`. How should I check that if this parameter will be an instance of `Record`?

> I feel like the general purpose structure can still work. The get by key
just looks up the index in a map. Then the array is indexed. I'm doing this
in avro4k.

Maybe. Let's change it and see how does it perform.

**Comment by sksamuel** [comment]
I honestly don't think it matters. Specific allows you access by index, Generic by key. If the record implementation supports both in a performant way, then it's fine. Obviously it seems the current Vector implementation is not performance for Specific but we can just change that to an Array and it should hopefully fix it.
If you want to make a PR I'll release.

**Comment by yeryomenkom** [comment]
> I honestly don't think it matters.

Ok
> Obviously it seems the current Vector implementation is not performance for Specific...

Even though Array may help us a bit, I think that the problem is the first line of the method.
```
//how many times this method will be called during the record serialization? I guess as many times as many
//fields the record has. It means that complexity of the specific serialization is n* log n, where n is a number
//of the record fields. Correct me if I am wrong. Meanwhile complexity of the generic serialization is linear.
//And moreover I am not sure how expensive is `.asScala`
override def get(key: String): AnyRef = {
    val index = schema.getFields.asScala.indexWhere(_.name == key)
    if (index == -1)
      sys.error(s"Field $key does not exist in this record (schema=$schema, values=$values)")
    get(index)
  }
```
> If you want to make a PR I'll release.

I will try to find some time during this week. Or maybe @maxstreese wanna do it? =) 

Thanks!
