### ISSUE TITLE
LocalTimeEncoder: Encoder[LocalTime] incorrectly encodes local time

### ISSUE THREAD

**Issue by rbnks** [sksamuel/avro4s#387]
The Encoder for LocalTime produces values that cannot be decoded to reproduce the same value on a roundtrip.  The schema for LocalTime sets the logical type to milliseconds and the type to `int`.  I believe this should be considered the incorrect behavior as [LocalTime has the precision of nanoseconds](https://docs.oracle.com/javase/8/docs/api/java/time/LocalTime.html). 

However, even if the correct behavior is supposed to be truncating LocalTime to milliseconds, the Encoder still does not do that calculation correctly.

```
val encoded = Encoder[LocalTime].encode(
        LocalTime.MAX,
        AvroSchema[LocalTime],
        DefaultFieldMapper
      )
encoded shouldBe LocalTime.MAX.toNanoOfDay / 1000000 // nano is 1000000 millis
``` 
```
Expected :86399999
Actual   :87398999
```

I propose to create a logical type `time-nano` with type `long` and make this the default schema for LocalTime and update the Encoder and Decoder. We can keep the Decoder backward compatible with the previous schemas.  I can open a pull request with this change.

**Comment by sksamuel** [comment]
Please make the PR yes !

**Comment by rbnks** [comment]
After reviewing some more Avro documentation and the LocalTime documentation, I have decided that I will fix the math behind the conversion to milliseconds and leave `time-millis` as the logical value for LocalTime.  `Localtime.now()` returns millisecond precision by default.

**Comment by sksamuel** [comment]
Ok sounds good.

**Comment by rbnks** [comment]
PR has been submitted. #388

**Comment by rbnks** [comment]
PR was merged.
