### ISSUE TITLE
LogcialType needs to be implicit

### ISSUE THREAD

**Issue by rbnks** [sksamuel/avro4s#394]
https://github.com/sksamuel/avro4s/blob/1282297ae89c5ff95b9fd86dfbea83e757833ab4/avro4s-core/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala#L177

The logical type for OffsetDateTime needs to be implicit.  When I import Avro4s v3.0.2 into another project, I am unable to create schemas for anything that has an OffsetDateTime.  If that logical type is made implicit, then the compiler can find all of the implicits necessary.  

```libraryDependencies += "com.sksamuel.avro4s" %% "avro4s-core" % "3.0.2"```

```    val offsetDateTimeSchemaF = SchemaFor[OffsetDateTime] ```
```    val offsetDateTimeAvroSchema = AvroSchema[OffsetDateTime]```

```
[error] . . . : could not find implicit value for parameter schemaFor: com.sksamuel.avro4s.SchemaFor[java.time.OffsetDateTime]
[error]     val offsetDateTimeSchemaF = SchemaFor[OffsetDateTime]
[error]                                          ^
```
```
[error] . . . : could not find implicit value for parameter schemaFor: com.sksamuel.avro4s.SchemaFor[java.time.OffsetDateTime]
[error]     val offsetDateTimeAvroSchema = AvroSchema[OffsetDateTime]
```

I have verified that when the object is made implicit everything works.  I, however, do not know how to demonstrate this with tests.

**Comment by rbnks** [comment]
PR #395

**Comment by sksamuel** [comment]
I think I changed this, so I broke it sorry.

**Comment by rbnks** [comment]
Any chance you can cut a release today?

**Comment by sksamuel** [comment]
Tonight once I'm home I can.

**Comment by sksamuel** [comment]
You could use the auto snapshot ?

**Comment by rbnks** [comment]
A release tonight would be great.  Thank you.

**Comment by sksamuel** [comment]
3.0.4 was released.
