### ISSUE TITLE
Precedence of @AvroName seems backwards

### ISSUE THREAD

**Issue by dylanwilder** [sksamuel/avro4s#396]
The following code works somewhat unexpectedly:
```scala
import com.sksamuel.avro4s._
implicit val snake = SnakeCase
case class Foo(@AvroName("BOOM_BAM") barBaz: String)
println(AvroSchema[Foo])
// {"type":"record","name":"Foo","namespace":"line11.read.iw.iw.iw.iw","fields":[{"name":"b_o_o_m__b_a_m","type":"string"}]}
```
i.e. it applies field mapping to explicitly specified name.  Generally I would expect that specifying AvroName would override everything as it is explicitly meant to be the serialized name, but it seems to be [an explicit choice](https://github.com/sksamuel/avro4s/blob/master/avro4s-core/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala#L226) to work this way? I also use the somewhat contrived all caps `BOOM_BAM` because it illustrates the non-workaroundable scenarios that this behavior creates (i.e. can't just specifcy `boomBam`). Is there are reason for this design choice? Is there way to force the serialized type?

**Comment by sksamuel** [comment]
I think probably AvroName should override the FieldMapper to me ?

**Comment by dylanwilder** [comment]
Agreed. Seems like a straight forward change

**Comment by dylanwilder** [comment]
[Pull Request](https://github.com/sksamuel/avro4s/pull/398)

**Comment by dylanwilder** [comment]
@sksamuel messed up the original PR. [Here's some stuff i missed](https://github.com/sksamuel/avro4s/pull/399/files). I didn't see anything else but lmk.
