### ISSUE TITLE
Deeply nested structures can lead to 'code too large' compilation error

### ISSUE THREAD

**Issue by enhan** [sksamuel/avro4s#401]
I have a structure containing a lot of nested (optional) fields (which themselves contain several (optional) fields, and so on) which leads to a massive structure (which, unfortunately I cannot share). To give an idea of the scale, I am talking about ~80 records type which can be nested with a depth of 8 (max). 

I came up to
```scala
class SomeCodec[T >: Null: SchemaFor: Encoder: Decoder](
  /* bunch of params */
) /* bunch of extends with*/{

  private val schema = AvroSchema[T]
  
  // some methods using capabilities of Encoder or Decoder like  
  // AvroOutputStream.binary[T].to(out).build(schema)

//.... other methods...
}
```

For our use case, splitting the generation of the Encoder in one object and Decoder in another one was a quick and easy workaround. 

The issue seems related to magnolia and macro evaluation which generate code in one and only method, leading to a `could not write class X because it exceeds JVM code size limits. Methods Y's code too large` error at compile time. 

Generating only the `Decoder`for instance with 

```scala
val src = Decoder[MyBigStruct]
```

leads indeed to a large code. I did a `javap -c` on the generated class and it gets ~24K instructions. 

I know avro4s is using magnolia to generate code, so, maybe I am on the wrong project to report this. 
Let me know if rolling a sample project without sensitive data is useful.

**Comment by ivan-klass** [comment]
Also faced this issue.
Our workaround was to put decoders and encoders into companion objects of field types.
Like if you have 
```
case class Bar ... 

sealed trait Baz ...

case class Foo(bar: Option[Bar], baz: Option[Baz])
```
adding companions like
```
object Bar {
   implicit val avro4sSchemaFor: SchemaFor[Bar] = SchemaFor.gen[Bar]
   implicit val avro4sDecoder: Decoder[Bar]           = Decoder.gen[Bar]
   implicit val avro4sEncoder: Encoder[Bar]           = Encoder.gen[Bar]
}
```
would help

There is a lightweight compiler plugin (it's does not depend on scalaz as it may seem like) to simplify such things
[scalaz-deriving](https://github.com/scalaz/scalaz-deriving)

**Comment by davideicardi** [comment]
@ivan-klass  Thank you for the fix!

Just want to add for future reference that this fix seems to solve also problems with complex classes (for example a trait with many implementations) that otherwise generate mostly random errors like `code too large`, `class too large`, `method too large`, `OutOfMemoryException` (compile Java heap space errors...).

@sksamuel  Do you think that there is some way to avoid these errors for the future?
