### ISSUE TITLE
Performance of sealed traits and type parameters

### ISSUE THREAD

**Issue by andreas-schroeder** [sksamuel/avro4s#422]
I have been working with avro4s since 1,5 years and I must first say thank you for providing this very convenient library. It is really well documented all around and nice to use; thank you for the effort you put into it!

Recently however, I have experienced a significant performance impact of avro4s on the overall CPU utilization of a codebase. I managed to narrow it down to the performance impact of using sealed traits with one subtype having a type parameter. 

I've provided you a benchmark for encoding / decoding that shows the impact of sealed traits and type parameters, and compares as well with the performance of partially hand-rolling encoders and decoders. I will share the benchmarks as PR soon.

The numbers are roughly as follows:
```
::Benchmark avro4s simple field decoding::                           0.003976 ms
::Benchmark avro4s type union decoding::                             0.010974 ms
::Benchmark avro4s type parameter decoding::                         0.003747 ms
::Benchmark avro4s union type with type param decoding::             0.012863 ms
::Benchmark Avro specific record union type field decoding::         0.001309 ms
::Benchmark avro4s union type with type param hand-rolled decoding:: 0.00148  ms

::Benchmark avro4s simple field encoding::                           0.003463 ms
::Benchmark avro4s type union encoding::                             0.014125 ms
::Benchmark avro4s type parameter encoding::                         0.004532 ms
::Benchmark avro4s union type with type param encoding::             0.019654 ms
::Benchmark Avro specific record union type field encoding::         0.00087  ms
::Benchmark avro4s union type with type param hand-rolled encoding:: 0.002641 ms
```

So introducing a sealed trait (with 3 subtypes) makes encoding x 4.0 slower and decoding x 2.7 slower. Introducing a type parameter on its own has little impact, the combination however makes encoding x 5.6 slower and decoding x 3.2 slower in the benchmark.

Comparing this with a partially hand-rolled encoding / decoding is also interesting: encoding is 7.4 x slower than hand-rolled, and 22.6 x slower than specific avro record, and decoding is 8.7 x slower than hand-rolled, and 9.8 x slower than specific avro record. In my real use-case, the improvement of partially hand-rolling the encoding gives a ~ x 12 speedup.

I have been looking around the code (without deep knowledge of it) and pointed a profiler at it (without deep knowledge of it), and gained the impression that there is a lot of potential to move significant amount of logic from encoding / decoding paths to encoder / decoder generation.

I will first now provide you the benchmarks so that you can evaluate what I have been measuring, and then we can maybe proceed with identifying areas of potential improvement. I might be possible to gain significant speedup by moving the Avro Schema parameter from the encode / decode methods to a class parameter of encoder / decoders. As far as I looked, this seems possible, but there might be corner cases that make it infeasible.

**Comment by sksamuel** [comment]
This is fantastic, thank you.

**Comment by andreas-schroeder** [comment]
You're welcome; I've generated a Flamegraph with the built-in IntelliJ profiler, here's a fragment of the result:

<img width="1284" alt="Flamegraph" src="https://user-images.githubusercontent.com/6724788/71748271-44953500-2e72-11ea-9297-2478099451ce.png">

Interestingly, NameExtractor.apply makes up 85 % of the total encoding time. Moving that out of the encoding / decoding path would quite dramatically improve performance.

**Comment by andreas-schroeder** [comment]
I've experimented with a quick-win, i.e. with caching the construction of NameExtractors with a concurrent hashmap. The improvements are:

```
::Benchmark avro4s union type with type param encoding:: 0.007508 ms
::Benchmark avro4s union type with type param decoding:: 0.003873 ms
```

i.e. encoding speedup is x 2.6, decoding speedup is x 3.3.

The flamegraphs show that there is still time spent in NameExtractor.apply, now mainly due to computation of hashcodes for the map lookup. The overhead of NameExtractor is still significant, but it would be an immediate improvement that doesn't require changing the Encoder / Decoder API.

Encoding before caching:
<img width="1566" alt="Encode before caching" src="https://user-images.githubusercontent.com/6724788/71763421-15b3a900-2edc-11ea-80b2-8a8092da8a89.png">

Encoding with caching:
<img width="1568" alt="Encode after caching" src="https://user-images.githubusercontent.com/6724788/71763425-1b10f380-2edc-11ea-86c3-abe73834c17d.png">

Decoding before caching:
<img width="1565" alt="Decode before caching" src="https://user-images.githubusercontent.com/6724788/71763513-05e89480-2edd-11ea-9b1e-9750bcab7773.png">

Decoding with caching:
<img width="1563" alt="Decode after caching" src="https://user-images.githubusercontent.com/6724788/71763533-46e0a900-2edd-11ea-913b-216ed83ba692.png">

PR follows suit.

**Comment by andreas-schroeder** [comment]
Note that still with the optimizations, encoding / decoding spends roughly 70% time on things related to schema and determining what the proper names of types and fields should be. @sksamuel what do you think, is it worth to try moving that from encoding / decoding time to encoder / decoder construction time?

**Comment by andreas-schroeder** [comment]
For a more straight-forward first optimization, see PR #425 and flame graphs in that.
