### ISSUE TITLE
Support for Avro 1.8.2 in Avro4s 3.x

### ISSUE THREAD

**Issue by RyanBerti** [sksamuel/avro4s#428]
Hello!

We've been using Avro4s to build avro schemas based on case classes and it's been super helpful when reading/writing Parquet data via Scio (Spotify's Scala API for Apache Beam). I wanted to open an issue because up until this point, we've been able to use Avro4s 3.0.x alongside Scio 0.8.0-beta2, even though Scio/Beam have not migrated past Avro 1.8.2. Scio just released 0.8.0, and we're now seeing issues due to the Avro version mismatch. 

I understand that Avro 1.8.x is pretty outdated, but from what I can tell, both Spark and Beam have not been able to migrate to 1.9.x yet because of the breaking datetime changes. Here's the Beam PR that trailed out late last year attempting the upgrade for some context: https://github.com/apache/beam/pull/9779

I've been able to make some minimal modifications to Avro4s 3.0.5 to depend on Avro 1.8.2, and utilizing this 'avro4s-core:3.0.5_avro1.8.2' dependency resolves the issues I'm seeing with Scio 0.8.0; I'm interested in getting your input on whether maintaining an avro 1.8.2 branch in avro4s is worthwhile? Otherwise, I'll likely maintain this implementation locally for the forseeable future, as its unclear how soon Spark/Beam will be able to make the leap forward.

**Comment by RyanBerti** [comment]
Also, as a separate thought - would it be possible to backport all changes from 3.0.x to a new 2.0.5 tag, and keep the 2.0.x releases compatible with Avro 1.8.x while also getting all of the bug fixes available in 3.0.x?

**Comment by sksamuel** [comment]
I'm not super keen on the effort required to support an outdated version of avro ( 2 years old ). What's spark 3 going to use ?
But I feel your pain. Maybe there's something we can do to address the particular areas where it's incompatible ? Or is it just a case of the dependency mis match ?

**Comment by RyanBerti** [comment]
Looks like Spark 3 is still dependent on Avro 1.8.2. When running Beam with Avro4s 3.0.x I was getting NoSuchMethodErrors due to Avro4s referencing some Schema.Field constructors that aren't available in Avro 1.8.x. I think those constructors may still be available, though I'd be weary of mixing Avro dependencies, even if we were able to make Avro4s 3.0.x compatible with both Avro 1.9.x and 1.8.x. 

Do you expect to have any more Avro 2.0.x releases? What do you think about just backporting everything from 3.0.x, removing tests for features that don't exist in 1.8.x, and releasing that as a 2.0.5? I agree, having to do this more than once isn't a great solution, but it does seem like 3.0.x is in a pretty stable place and I'd be surprised if I was the only one that will want to use the more stable 3.0.x in an Avro 1.8.x env.

BTW here's the changes I had to make to get 3.0.x compile against Avro 1.8.2 (some tests were failing but I didn't fix them as they all seemed default value related): https://github.com/sksamuel/avro4s/pull/430)

**Comment by sksamuel** [comment]
I think backporting would be really hard as 3.0 is built on magnolia and
2.x used my own macros. Very different.

We could just update avro4s to not use the constructors that were added in
1.9.x ? I'm happy to make the changes and you can test until we've got rid
of them.

**Comment by RyanBerti** [comment]
I guess when I say backport, I meant copy 3.0.5 into a new 2.0.5, and update the new 2.0.5 to compile and run against Avro 1.8.2. This would bring 2.0.x up to speed with the magnolia changes available in 3.0.x. 

Otherwise, it seems like utilizing the old constructors and not utilizing the enumeration.defaultSymbol methods would be necessary; I figured supporting enum defaults would be something you'd want to retain so I don't know if this is a viable solution?

**Comment by slavaschmidt** [comment]
@RyanBerti would you mind sharing the changes you did in the avro4s-core:3.0.5_avro1.8.2 port? I'm currently trying to do the same but would be really happy to piggyback on your version.

**Comment by saif-ellafi** [comment]
Hi, also interested in this. I am failing to deserialize with Spark's avro version. Hoping newer versions of avro4s would help but they are not compatible.

**Comment by LukeDefeo** [comment]
We are having issues with the macroo in avro4s 2.x which are fixed in 3.x magnolia implementaition. However we are having huge problems updating avro from 1.8 to 1.9. 

They broke nearly everything including:

- Changed internal json lib  from codehaus to fasterxml
- Made several methods / classes private that were visible before
- Change how Null schemas work
- The worst is that some previous schema encoded in the json from with schema.toString() are no longer parsable in 1.9. We have 1000's of schemas which are not usable in the latest version

We would really appreciate some kind of support for 1.8 on the latest macro

**Comment by shankarshastri** [comment]
Any updates regarding this, I've also trying to integrate it with spark. But it gives me no such method error?
