### ISSUE TITLE
value schema in trait ToSchema of type org.apache.avro.Schema is not defined

### ISSUE THREAD

**Issue by blbradley** [sksamuel/avro4s#43]
Hello!

I get this build error when defining a custom type mapping with 1.5.1.
```
Error:(30, 19) object creation impossible, since value schema in trait ToSchema of type org.apache.avro.Schema is not defined
  implicit object InstantToSchema extends ToSchema[Instant] {
```

Here is the mapping code:
```scala
  implicit object InstantToSchema extends ToSchema[Instant] {
    override def apply(): Schema = Schema.create(Schema.Type.STRING)
  }

  implicit object InstantToValue extends ToValue[Instant] {
    override def apply(value: Instant): String = value.toString
  }

  implicit object InstantFromValue extends FromValue[Instant] {
    override def apply(value: Any, field: Field): Instant = Instant.parse(value.toString)
  }
```

This does not happen in 1.4.3 with the same code.

Cheers!

**Comment by jeroentervoorde** [comment]
Hi,

This is caused by my performance refactoring in 1.5. ToValue now expects a val schema to be set and will always return that in apply()

The following does work:

  implicit object InstantToSchema extends ToSchema[Instant] {
    override val schema: Schema = Schema.create(Schema.Type.STRING)
  }

Is this ok for your use-case?

**Comment by sksamuel** [comment]
I've updated the readme to reflect this.

**Comment by blbradley** [comment]
@jeroentervoorde That did work for me. Thanks!

@sksamuel Can you also update the version in the README that should be used when you update the examples? It has been on `1.4.3` for a few versions. That kind of documentation change can be easy to forget. Thanks!

**Comment by sksamuel** [comment]
Done.
