### ISSUE TITLE
Fields with "avro.java.string": "String" type

### ISSUE THREAD

**Issue by jdreyesp** [sksamuel/avro4s#431]
In avro4s I don't find the option to generate Schemas from a Scala case class that generate this type for a field:

```json
"type": {
  "type": "string",
  "avro.java.string": "String"
}
```

So if I have: 
```scala
case class Account(id: String)
```

it will generate (for id field):
```json
"fields": [{
    "name": "id",
    "type": "string"
}
```

This additional "avro.java.string" : "String" is necessary since apparently is checked when comparing schemas. Am I stuck having to define JSON schemas and not using the feature of defining case classes?

Cheers

**Comment by jdreyesp** [comment]
@sksamuel any thoughts about this?

**Comment by sksamuel** [comment]
I'll add this via an annotation. For now you could bring into scope your
own StringSchemaFor.

**Comment by jdreyesp** [comment]
Ok, thanks!

**Comment by jdreyesp** [comment]
@sksamuel StringSchemaFor as far as I've seen applies the 'addProp' to all Strings in the Schema. Is there a way to add the property based on the field name?

Cheers

**Comment by sksamuel** [comment]
You can write your own SchemaFor and bring that into scope

implicit val a = new SchemaFor { // do what you want //

**Comment by jdreyesp** [comment]
I tried that, but SchemaFor doesn't give me an option to apply a specific property only on a field with the specific name I want to, or at least I haven't seen that option.

Cheers

**Comment by sksamuel** [comment]
I see what you mean.

**Comment by skywangyan** [comment]
I have seen the same issue, avro4s generated schema is different from the schema which the scala case classes are, eg. this ``` "avro.java.string": "String"```. Which makes the byte array that avro4s produces can not be deserialized by java avro.

**Comment by sksamuel** [comment]
The `avro.java.string` flag should only be needed when generating strings using java Strings and not avros Utf8 class. 

If we add @AvroJavaString as an annotation, you could use that to generate schemas using this flag.

The String Encoder should respect this flag.

The String Decoder doesn't need this flag, as it will detect the type anyway.

I will raise a PR with the above.

**Comment by teenasharma** [comment]
hey, this there any update on this issue?

**Comment by sksamuel** [comment]
This is now supported in avro4s 5 for scala 3.
