### ISSUE TITLE
Avro4s isn't generating unique schema names for deeply nested generic types

### ISSUE THREAD

**Issue by stevewampler** [sksamuel/avro4s#441]
I need avro4s to generate unique schema names for generic types nested more than one level.

For example, avro4s generates the truncated name `MatchEvent__Advertiser_Option` for the type `MatchEvent[Advertiser, Option[Seq[Organization]]]]`.

A unique name, that captures the actual type, would be `MatchEvent__Advertiser_Option_Seq_Organization`.

**Comment by stevewampler** [comment]
Hi @sksamuel, would you please generate a 3.0.8 build? I'd like to use this fix in my project at work. Or, if there's a way for me to kick off a 3.0.8 build/deploy, let me know how and I'll do it.

**Comment by sksamuel** [comment]
Releasing 3.0.8 now.

**Comment by stevewampler** [comment]
Thanks @sksamuel !

**Comment by sksamuel** [comment]
Should show up in a bit. It's been released.
