### ISSUE TITLE
GenericSerde.scala could also support JSON avro

### ISSUE THREAD

**Issue by sv3ndk** [sksamuel/avro4s#447]
Hi, 

Thanks for creating Avro4s, really helpful !

I recently wanted to use [GenericSerde.scala](https://github.com/sksamuel/avro4s/blob/master/avro4s-kafka/src/main/scala/com/sksamuel/avro4s/kafka/GenericSerde.scala), though needed support for JSON avro for easy debugging, so I ended up duplicating it :

https://github.com/sv3ndk/kafka-to-rdbms-export-akka-demo/blob/master/src/main/scala/com/svend/demo/Avro4sSerdes.scala

Would you like me to submit a PR back to Avro4S with this minor update? 

Also, the readme does not mention the existence of that class, which I find very useful, so I can add a few words about it there as well if you want?

**Comment by sksamuel** [comment]
What did you change exactly ?

**Comment by sv3ndk** [comment]
I added the optional constructor parameter `(jsonFormat: Boolean = false)` that I then use to select the Avro format:  `if (jsonFormat) AvroInputStream.json[T] else AvroInputStream.binary[T]` and `if (jsonFormat) AvroOutputStream.json[T] else AvroOutputStream.binary[T]`

**Comment by sksamuel** [comment]
I think that's good but we could use the AvroFormat trait and then support all 3 formats ?

**Comment by sv3ndk** [comment]
Hi, 

Sorry for the week of silence, I'm back now :)

Good idea to rely on `AvroFormat`. I gave it a try and just submitted a MR here: https://github.com/sksamuel/avro4s/pull/452.

I suggest we continue the discussion over there?
