### ISSUE TITLE
Scala 2.11 Release 

### ISSUE THREAD

**Issue by kotiajit** [sksamuel/avro4s#450]
Couple of frameworks I use like Spark & Flink we are still dependent on Scala 2.11, I have used Avro4s before, But I am now hitting various issues which are resolved in latest version.

Can you please release Avro4s with  Scala 2.11 version

**Comment by kotiajit** [comment]
Issues like these are fixed in the latest version 
https://github.com/sksamuel/avro4s/issues/247
https://github.com/sksamuel/avro4s/issues/411

**Comment by LBsh** [comment]
We are using hadoop that also depends on scala 2.11. We would like use optional fields and it gave us the error
```org.apache.avro.AvroRuntimeException: Unknown datum class: class scala.None$```
Is this something that could be fixed with scala 2.11? @sksamuel

**Comment by sksamuel** [comment]
I don't think it would be possible because this library relies on magnolia which has no recent 2.11 release.
