### ISSUE TITLE
Avro Schema Evolution Using Avro4s

### ISSUE THREAD

**Issue by shankarshastri** [sksamuel/avro4s#461]
I was exploring avro4s for one of my projects and wanted to know about handling Avro schema evolution using avro4s.

To explain it with an example tried the below with JSON serialization/deserialization,  everything worked fine:
```scala
import java.io._
import com.sksamuel.avro4s._

object SchemaEvolutionUsingAvro4S {

  case class UserV1(name: String, favNum: Int)
  case class UserV2(name: String, favNum: Int, age: Option[Int] = None)


  def main(args: Array[String]): Unit = {
    val userV1Schema = AvroSchema[UserV1]
    val userV2Schema = AvroSchema[UserV2]

    val b = new ByteArrayOutputStream()

    val userV1Write = AvroOutputStream.json[UserV1].to(b).build(userV1Schema)
    userV1Write.write(UserV1("H1", 2))
    userV1Write.flush()

    val userV2Write = AvroOutputStream.json[UserV2].to(b).build(userV2Schema)
    userV2Write.write(UserV2("H2", 2, Some(26)))
    userV2Write.flush()

    println(b.toString)

    val userV2Read = AvroInputStream.json[UserV2].from(new ByteArrayInputStream(b.toByteArray)).build(userV2Schema)
    println(userV2Read.tryIterator.toList)
  }
}
```
But the below one, tried it using data or binary it throws exceptions:
```scala
import java.io._
import com.sksamuel.avro4s._

object SchemaEvolutionUsingAvro4sData {
  case class UserV1(name: String, favNum: Int)
  case class UserV2(name: String, favNum: Int, age: Option[Int] = None)

  def main(args: Array[String]): Unit = {
    val userV1Schema = AvroSchema[UserV1]
    val userV2Schema = AvroSchema[UserV2]

    val b = new ByteArrayOutputStream()

    val userV1Write = AvroOutputStream.binary[UserV1].to(b).build(userV1Schema)
    userV1Write.write(UserV1("H1", 2))
    userV1Write.flush()

    val userV2Write = AvroOutputStream.binary[UserV2].to(b).build(userV2Schema)
    userV2Write.write(UserV2("H2", 2, Some(26)))
    userV2Write.flush()

    val userV2Read = AvroInputStream.binary[UserV2].from(b.toByteArray).build(userV2Schema)
    println(userV2Read.tryIterator.toList)
  }
}
```

Exception:
```
List(Failure(java.lang.ArrayIndexOutOfBoundsException: 2), Failure(java.io.EOFException))
```

I wanted to know how can I use avro4s to serialize data in binary with backward compatibility.
Went through README.md, couldn't find it. Please let me know, about it.

**Comment by shankarshastri** [comment]
Update:
Also tried to use:
```scala
val userV2Read = AvroInputStream.binary[UserV2].from(b.toByteArray).build(userV1Schema, userV2Schema)
println(userV2Read.tryIterator.toList)
```
But still ending up with this error:
Exception:
```
List(Success(UserV2(H1,2,None)), Success(UserV2(H2,21,None)), Failure(java.io.EOFException))
```

**Comment by andreas-schroeder** [comment]
The thing is that the input stream reader assumes a stable writer schema. If the schema actually changes per record, you need a source of information that indicates which writer schema applies. With Kafka's Avro Serdes and schema registry, the writer schema version number is stored as integer with each record, and the reader looks up the schema with the available version information.

As for your error, I think what happens is that there are some bytes left after reading the second user (the bytes for the age of the second item), which makes the iterator attempt to read a third item.

**Comment by shankarshastri** [comment]
@andreas-schroeder , so is it not possible to do schema evolution with avro4s alone?

**Comment by andreas-schroeder** [comment]
@shankarshastri no, not in the sense as Confluent's Kafka Avro Serdes can. As I said, for that to work you'd need enhance the data with information about the used schema, which is not part of the Avro spec and avro4s doesn't offer support for it. You'd have to write something of your own along the lines of https://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java#L81 your own when writing the data, and conversely when deserializing data do the lookup of the proper writer schema.

**Comment by andreas-schroeder** [comment]
@shankarshastri to give you a way out: you can still use avro4s `Encoder` and `Decoder` to serialize/deserialize data to avro generic records, and set up an extended machinery based on what you find wrapped in `AvroInputStream.binary` yourself and do the writer schema lookup per record - I've done this also myself and put an example up here: https://github.com/andreas-schroeder/demo-segmenter/blob/master/common/src/main/scala/common/AvroSerde.scala#L13

**Comment by shankarshastri** [comment]
Thanks @andreas-schroeder . I will take a look at it.

**Comment by LeonardMeyer** [comment]
For anyone who stumbles upon this looking for insights, here's how I did it : 

```
/** Generic serde allowing to do the following conversions :
  *   Case class -> GenericRecord -> Bytes
  *   Bytes -> GenericRecord -> Case class
  *
  * This serde can handle schema evolution because it relies on the GenericAvroSerde from Kafka, which reads the
  * schema id from each message, depending on the config
  *
  * @param schemaRegistryClient Registry containing the schemas used to read the avroSerde data
  * @param config Configuration for the GenericAvroSerde
  * @param format avro4s typeclass instance to convert case classes to and from GenericRecord
  * @tparam T Case class type
  */
final class GenericSchemaAwareSerde[T](
  schemaRegistryClient: SchemaRegistryClient,
  config: Map[String, Any] = Map.empty,
  format: RecordFormat[T]
) extends Serde[T]
    with Deserializer[T]
    with Serializer[T]
    with Serializable {

  private val avroSerde = new GenericAvroSerde(schemaRegistryClient)
  this.configure(JavaConverters.mapAsJavaMap(config), isKey = false)

  override def serializer(): Serializer[T] = this

  override def deserializer(): Deserializer[T] = this

  override def configure(configs: util.Map[String, _], isKey: Boolean): Unit = avroSerde.configure(configs, isKey)

  @throws
  override def deserialize(topic: String, data: Array[Byte]): T =
    format.from(avroSerde.deserializer().deserialize(topic, data))

  @throws
  override def serialize(topic: String, data: T): Array[Byte] =
    if (data == null) null
    else avroSerde.serializer().serialize(topic, format.to(data))

  // This probably does nothing looking at the code...
  override def close(): Unit = avroSerde.close()
}

object GenericSchemaAwareSerde {

  def apply[T](implicit
    format: RecordFormat[T],
    schemaRegistryClient: SchemaRegistryClient,
    config: Map[String, Any] = Map.empty
  ) = new GenericSchemaAwareSerde[T](schemaRegistryClient, config, format)
}
```

It relies on Kafka's serde and seems to work fine from my tests.
