### ISSUE TITLE
Request: "discriminator" based sealed trait encoding

### ISSUE THREAD

**Issue by obogobo** [sksamuel/avro4s#471]
Hello there! My organization has ended up with a moderately-large sealed trait hierarchy at this point (11 subtypes, ~500 total fields amongst them) and have been encoding the leaf classes individually thus far to keep the fields per .avsc file manageable. I'm wondering if it's reasonable (or even possible!) to support "discriminator" style encoding like Circe offers, for Avro types that would presently be encoded as a Union?

For example:

**encoding records by trait: Union style**
```
sealed trait Pizza
case class Pepperoni(...) extends Pizza
case class Hawaiian (...) extends Pizza

val p: Pizza = Pepperoni(...)
val os = AvroOutputStream.data[Pizza].to(new File("pizzas.avro")).build(schema)
os.write(p)
os.flush()
os.close()

// serializes under the union schema
[ {
  "type" : "record",
  "name" : "Pepperoni",
  "fields" : [ ... ]
  },
  {
  "type" : "record",
  "name" : "Hawaiian",
  "fields" : [ ... ]
  }
]
```

**encoding records by trait: Discriminator style**
```
@AvroUseNameDiscriminator
sealed trait Pizza
case class Pepperoni(...) extends Pizza
case class Hawaiian (...) extends Pizza

val p: Pizza = Pepperoni(...)
val os = AvroOutputStream.data[Pizza].to(new File("pizzas.avro")).build(schema)
os.write(p)
os.flush()
os.close()

// serializes using the Pizza.Pepperoni schema only, Discriminator captured in the record's "name" (for example)
{
  "type" : "record",
  "name" : "Pizza.Pepperoni", 
  "fields" : [ ... ]
 }
```

Confluent Schema Registry _effectively_ does this by prepending a unique byte identifier to the output Avro (representing the schema), just wondering if it's possible to do something in similar form here to avoid Union types where desirable. End goal being, the ability to both serialize/deserialize records using the base trait - and having avro4s know which subtype each record represents internally.

**Comment by sksamuel** [comment]
Circe doesn't have to worry about a schema.

When you generate the schema for your hierarchy it will detect a sealed trait and say, well this has to be a union.

But then when serialising you want it to just use a record type instead. Unfortunately then, the generated GenericRecord isn't going to be compatible with it's own schema.

**Comment by obogobo** [comment]
Hmm yeah I see how that would be tricky :/ 

Had originally thought when a sealed trait was detected, there might be a way to "defer" resolution of that schema until just before writing, to a point at which the subclass record's leaf type information would be present and could be swapped in for a more specific output schema. I imagine that's how Circe manages to do it, but have to admit I haven't checked and Avro is an entirely different beast!

Thanks for looking

**Comment by andreas-schroeder** [comment]
Have you tried implementing what you need on top of (or as a wrapper around) avro4s? For writing, you'd need to define how to extract the discriminator from a record's schema, and for reading, having a lookup means for mapping discriminator to schema / FromRecord - similarly to how Confluent schema registry does it. Actually, what you need is an additional protocol on top of Avro, as there's nothing defined in Avro to support that (which is also probably why Confluent implemented it on top of Avro).

**Comment by andreas-schroeder** [comment]
Sorry, my bad, I hadn't seen that the example code was using the `data` output stream that writes the schema at the beginning. In this case, my suggestion obviously doesn't apply. I see however the issue that there is no guarantee that only a singular subtype (e.g. Pepperoni) will be written when the output stream is created with the supertype (e.g. Pizza) - there wouldn't be much preventing you from sending other subtypes to that output stream.

**Comment by obogobo** [comment]
I think I'll close this, we're effectively doing that - wrapping the encoders in an object and providing SerDe helper methods that summon the appropriate subclasses' implicit vs. doing SerDe on the sealed trait hierarchy directly. Thanks!
