### ISSUE TITLE
[Question] New Release

### ISSUE THREAD

**Issue by juanpedromoreno** [sksamuel/avro4s#472]
Hi, 

Is there any possibility of releasing a new avro4s version soon? Some patch fixes would be significant to have them published, like these two:

https://github.com/sksamuel/avro4s/pull/455
https://github.com/sksamuel/avro4s/pull/456

Thanks!

**Comment by juanpedromoreno** [comment]
Temporarily, we are using a temporary release:

* https://github.com/47degrees/avro4s/compare/v3.0.9...v3.0.10-temp
* https://github.com/47degrees/avro4s/releases/tag/v3.0.10-temp

```
"com.47deg" %% "avro4s-<module>" % "3.0.10-temp"
```

**Comment by sksamuel** [comment]
I've released 3.10.10 now.
Apologies for the delay.
