### ISSUE TITLE
Can't create schema for case class with enum field

### ISSUE THREAD

**Issue by tomakita** [sksamuel/avro4s#487]
Hi,

Thanks for the great library!  

I've run into some unexpected behavior when using avro4s 3.0.9 (also happens with 3.0.8).  Let's say you have a case class that has a field of type `Option[Seq[SomeEnum.Value]] = None`, e.g. `case class C(x: Option[Seq[MyEnum.Value]] = None)`.  Then, we want to wrap that class in a Seq, then an Option, and then create a schema of the resulting type, like `AvroSchema[Option[Seq[C]]]`.  This results in the following exception:

> [31m  org.apache.avro.AvroTypeException: Invalid default for field x: null not a [{"type":"record","name":"None","namespace":"scala","fields":[]},{"type":"record","name":"Some__Seq__Value","namespace":"scala","fields":[{"name":"value","type":{"type":"array","items":{"type":"enum","name":"SomeEnum","namespace":"com.x.y","symbols":["Choice"]}}}]}][0m
[31m  at org.apache.avro.Schema.validateDefault(Schema.java:1540)[0m
[31m  at org.apache.avro.Schema.access$500(Schema.java:87)[0m
[31m  at org.apache.avro.Schema$Field.<init>(Schema.java:521)[0m
[31m  at org.apache.avro.Schema$Field.<init>(Schema.java:557)[0m
[31m  at com.sksamuel.avro4s.SchemaFor$.com$sksamuel$avro4s$SchemaFor$$buildField(SchemaFor.scala:320)[0m
[31m  at com.sksamuel.avro4s.SchemaFor$$anon$13.$anonfun$schema$8(SchemaFor.scala:378)[0m
[31m  at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)[0m
[31m  at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)[0m
[31m  at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)[0m
[31m  at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)[0m

Aside from the fact that this throws an exception, I've also noticed that the generated schema doesn't seem to include the default value of `None` for `C.x`.  Maybe that's a clue?  Anyway, if you think this is a bug, would you accept a PR with a fix, if I'm able to fix it?  Here are a few test cases that show the problem:

```
package com.x.y

import com.sksamuel.avro4s.AvroSchema
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

class Avro4sReproSpec extends AnyFlatSpec with Matchers {

  object MyEnum extends Enumeration {
    val Choice = Value
  }

  // causes a problem
  case class MyCaseClassWithDefault(x: Option[Seq[MyEnum.Value]] = None)

  // doesn't cause a problem
  case class MyCaseClassWithoutSeq(x: Option[MyEnum.Value] = None)

  // doesn't cause a problem
  case class MyCaseClassWithoutDefault(x: Option[Seq[MyEnum.Value]])

  // doesn't cause a problem
  case class MyCaseClassWithoutEnum(x: Option[Seq[String]] = None)

  "avro4s" should "has a problem with this" in {
    val schema = AvroSchema[Option[Seq[MyCaseClassWithDefault]]]
    println(schema.toString(true))
  }

  "avro4s" should "can do just seq" in {
    val schema = AvroSchema[Seq[MyCaseClassWithDefault]]
    println(schema.toString(true))
  }

  "avro4s" should "can do just option" in {
    val schema = AvroSchema[Option[MyCaseClassWithDefault]]
    println(schema.toString(true))
  }

  "avro4s" should "can do unwrapper" in {
    val schema = AvroSchema[MyCaseClassWithDefault]
    println(schema.toString(true))
  }

  "avro4s" should "can do case class with no default" in {
    val schema = AvroSchema[Option[Seq[MyCaseClassWithoutDefault]]]
    println(schema.toString(true))
  }

  "avro4s" should "can do case class with no enum" in {
    val schema = AvroSchema[Option[Seq[MyCaseClassWithoutEnum]]]
    println(schema.toString(true))
  }

  "avro4s" should "can do case class with no seq" in {
    val schema = AvroSchema[Option[Seq[MyCaseClassWithoutSeq]]]
    println(schema.toString(true))
  }
}
```

Note: If I replace `MyEnum.Value` with an enum that's implemented by extending a sealed trait, the schema is generated successfully.  So that's a workaround for this bug, in case anyone else encounters it.

**Comment by andreas-schroeder** [comment]
Thanks for reporting, this is indeed a very unexpected behavior. As far as I can infer from your tests there is an issue with how implicits are resolved; the wrong implicit gets selected, but only in this very specific setup.

**Comment by andreas-schroeder** [comment]
Can only reproduce with Scala 2.12.10, 2.13.1 doesn't have the problem - this indicates that the issue is with how the Scala compiler resolves implicits between the Magnolia macro and the other implicits

**Comment by tomakita** [comment]
Oops, I forgot to mention that we're using 2.12.10 -- thanks for pointing that out.  And you're right, I've just tried with 2.13.1, and this doesn't happen with that version.

**Comment by andreas-schroeder** [comment]
Btw (to bring things together and document them), I think that #443 has the same problem of wrong implicit resolution - there, it's for shapeless Coproduct with Option.

**Comment by andreas-schroeder** [comment]
Two solutions I see:
* we could follow https://github.com/propensive/magnolia/issues/213#issuecomment-600584671 and use (a copy of) `Refute`
 * we could "hack" around the issue and redirect Option and shapeless Coproducts that happen to be caught by Magnolia to the proper implicits.

**Comment by andreas-schroeder** [comment]
@tomakita one thing you can do to get the schema generated properly without changing the model is guiding the implicit resolution by introducing intermediate steps like so:

```scala
val schema = {
  val sf = SchemaFor[MyCaseClassWithDefault]
  implicit val myCaseClassSchemaFor = sf
  AvroSchema[Option[Seq[MyCaseClassWithDefault]]]
}
println(schema.toString(true))
```
