### ISSUE TITLE
A new annotation @AvroError may help defining error records

### ISSUE THREAD

**Issue by angiolep** [sksamuel/avro4s#492]
According to the official AVRO specification, at section [Protocol Declaration](https://avro.apache.org/docs/current/spec.html#Protocol+Declaration)

> ... an error definition is just like a record definition except it uses "error" instead of "record" ...

By reading the following line of Scala code

https://github.com/sksamuel/avro4s/blob/master/avro4s-core/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala#L382

where the Avro4s implementation of `SchemaFor` is creating a record with the `isError` field always set to `false`, makes me suspect that Avro4s does not support definition of Avro records of type error. 

A new annotation, such as `@AvroError`, may help developers defining such a kind of Avro record, as per following example:

```scala
import com.sksamuel.avro4s.AvroError

@AvroError
case class ErrorOccurred(uuid: String, message: String)
```

Could this be a desirable feature?

**Comment by sksamuel** [comment]
So effectively @AvroError would switch the "type" from "record" to "error" when the schema is generated?

**Comment by angiolep** [comment]
yes, that's it
