### ISSUE TITLE
Significant performance regression between version 3.0.9 and 2.03

### ISSUE THREAD

**Issue by KGoodale13** [sksamuel/avro4s#495]
Hello, we recently upgraded from avros4s version 2.0.3 to 3.0.9 and have noticed some massive performance regressions. 

Some basic benchmarks show a hit of about 3X on serialization: 
```
Avro Serialization (3.0.9):
Parameters(numberOfEvents -> 500): 105.949524 ms
Parameters(numberOfEvents -> 2000): 426.090214 ms
Parameters(numberOfEvents -> 3500): 745.042044 ms
Parameters(numberOfEvents -> 5000): 1061.600599 ms
Parameters(numberOfEvents -> 6500): 1379.572099 ms
```

```
Avro Serialization (2.0.3):
Parameters(numberOfEvents -> 500): 32.817919 ms
Parameters(numberOfEvents -> 2000): 134.431979 ms
Parameters(numberOfEvents -> 3500): 238.911994 ms
Parameters(numberOfEvents -> 5000): 333.905703 ms
Parameters(numberOfEvents -> 6500): 435.456092 ms
```

Independent of those benchmarks we have observed an even greater hit to cpu and serialization times when using avro4s 3.0.9 in production.
![Screen Shot 2020-06-02 at 2 35 50 PM](https://user-images.githubusercontent.com/13970273/83557555-d9629400-a4df-11ea-872e-d087a0cc99a8.png)
In the screenshot above we have a particular service running avro4s version 3.0.9 on the left side. After reverting to avro4s version 2.0.3 with no other changes you can see the serialization time drop significantly on the right side.

Additional info: 
- This only appears to effect serialization times. Deserialization times remain unaffected based on our observations. 
- We are serializing to a binary avro output stream.

**Comment by andreas-schroeder** [comment]
Thank you for the detailed report. Yes, there is a significant performance issue and we have been working on fixing it in version 4.0.0 for a couple weeks now. Maybe the new version will bring you the performance back that you need, maybe even better. I'd love to have your numbers with version 4.0.0 once it is there.

**Comment by sksamuel** [comment]
Can you try 4.0.0.RC1 now it has been released @KGoodale13

**Comment by KGoodale13** [comment]
It appears it may have gotten worse. I did five separate runs to confirm. Here are the results for both serialization and deserialization for versions 4.0.0-RC1 and 2.0.3:
```
4.0.0-RC1 Avro Serialization
numberOfEvents -> 500: 652.079ms, 647.694ms, 650.549ms, 647.507ms, 643.936ms
numberOfEvents -> 1000: 1301.201ms, 1307.920ms, 1296.771ms, 1295.441ms, 1312.230ms
numberOfEvents -> 1500: 1964.508ms, 1944.739ms, 1962.846ms, 1940.858ms, 1942.202ms

4.0.0-RC1 Avro Deserialization
numberOfEvents -> 500: 1331.793ms, 1331.359ms, 1334.465ms, 1328.856ms, 1344.235ms
numberOfEvents -> 1000: 2679.562ms, 2663.810ms, 2664.805ms, 2681.070ms, 2654.347ms
numberOfEvents -> 1500: 4014.252ms, 4006.239ms, 3996.186ms, 4016.320ms, 4018.596ms


2.0.3 Avro Serialization
numberOfEvents -> 500: 35.671ms, 36.302ms, 35.662ms, 35.565ms, 35.460ms
numberOfEvents -> 1000: 70.759ms, 119.163ms, 70.808ms, 70.962ms, 70.871ms
numberOfEvents -> 1500: 106.605ms, 106.552ms, 103.998ms, 103.987ms, 105.103ms

2.0.3 Avro Deserialization
numberOfEvents -> 500: 63.619ms, 63.568ms, 65.142ms, 63.631ms, 64.006ms
numberOfEvents -> 1000: 126.087ms, 125.335ms, 125.820ms, 125.449ms, 125.226ms
numberOfEvents -> 1500: 187.445ms, 188.058ms, 189.631ms, 187.311ms, 187.773ms
```

Below is visual representation. At the start of each graph the performance tests are being run with version 2.0.3. At the end of each graph you can see switching to 4.0.0-RC1 significantly increases both the serialization and deserialization times.

![avro4s-perf](https://user-images.githubusercontent.com/13970273/87584936-42772300-c6ac-11ea-829a-e6ff9e387248.png)

**Comment by andreas-schroeder** [comment]
This is quite surprising. Can you share how you are using avro4s, and want your schema/types look like?
Instantiating encoders and decoders is really expensive, and that could explain want you see.

**Comment by KGoodale13** [comment]
We are lazily instantiating the encoders and decoders once. Here is a reproducible example scalameter test that is similar to how we are using avro4s. This produces the following results: 

```
4.0.0-RC1
Parameters(numberOfEvents -> 500): 125.239635 ms
Parameters(numberOfEvents -> 1000): 251.589681 ms
Parameters(numberOfEvents -> 1500): 373.394427 ms
```
```
2.0.3
Parameters(numberOfEvents -> 500): 28.487295 ms
Parameters(numberOfEvents -> 1000): 51.471666 ms
Parameters(numberOfEvents -> 1500): 78.818563 ms
```


```scala
import java.io.ByteArrayOutputStream
import com.sksamuel.avro4s.{AvroInputStream, AvroInputStreamBuilder, AvroOutputStream, AvroOutputStreamBuilder, AvroSchema}
import org.scalameter.api._
import org.apache.avro.Schema

object PerfTest extends Bench.ForkedTime {
  case class TestEvent2(
    a: String,
    b: String,
    c: String
  )

  case class TestEvent(
    a: String,
    b: String,
    c: Long,
    d: String,
    e: Long,
    f: String,
    g: List[String],
    h: Option[Long],
    i: Option[String],
    j: String,
    k: String,
    l: String,
    m: String,
    n: String,
    o: String,
    p: String,
    q: String,
    r: String,
    s: String,
    t: String,
    u: String,
    v: String,
    aa: List[TestEvent2]
  )

  val sampleTestList = (1 to 100).map(_ => TestEvent2("a", "b", "c")).toList
  val sampleEvent = TestEvent("a", "b", 0L, "d", 0L, "f", List("g", "g", "g"), None, None, "j", "", "", "", "", "", "", "", "", "", "", "", "", sampleTestList)

  lazy val schema: Schema = AvroSchema[TestEvent]
  lazy val ser: AvroOutputStreamBuilder[TestEvent] = AvroOutputStream.binary[TestEvent]
  lazy val de: AvroInputStreamBuilder[TestEvent] = AvroInputStream.binary[TestEvent]

  def serialize(msg: TestEvent): Array[Byte] = {
    val baos = new ByteArrayOutputStream()
    val output = ser
      .to(baos)
      .build() // For 2.0.3 add schema as a param here. Remove it for 4.0.0

    output.write(msg)
    output.close()
    baos.toByteArray
  }

  performance of "TestEvent Serialization" in {
    using(Gen.range("numberOfEvents")(500, 1500, 500)) config(
      exec.benchRuns -> 5,
      exec.independentSamples -> 1
    ) in { numberOfEvents =>
      val events = (0 to numberOfEvents).map(_ => sampleEvent)
      events.map(serialize)
    }
  }
}

```

**Comment by andreas-schroeder** [comment]
I see. Just before the `lazy val`, try to add 

```scala
implicit val encoder: Encoder[TestEvent] = Encoder.gen[TestEvent].resolveEncoder() 
implicit val decoder: Decoder[TestEvent] = Decoder.gen[TestEvent].resolveDecoder() 
```

If that helps, I think we definitely need to improve the setup happening behind the scenes...

**Comment by KGoodale13** [comment]
Wow, yea this is miles faster that even the 2.0.3 code with those implicits added. 

```
4.0.0-RC1 WITHOUT implicit encoder
Parameters(numberOfEvents -> 500): 699.693395 ms
Parameters(numberOfEvents -> 1000): 1401.89647 ms
Parameters(numberOfEvents -> 1500): 2100.414417 ms
```
```
4.0.0-RC1 WITH implicit encoder
Parameters(numberOfEvents -> 500): 23.941706 ms
Parameters(numberOfEvents -> 1000): 48.102779 ms
Parameters(numberOfEvents -> 1500): 71.897657 ms
```

**Comment by andreas-schroeder** [comment]
Good to know. We will improve the setup so that you won't need these implicits before we release the final 4.0.0 ;)

**Comment by sksamuel** [comment]
I wonder if the AvroSchema is invoking the encoder macro every time.

**Comment by andreas-schroeder** [comment]
@sksamuel it's rather the resolveX methods that are called too late (i.e.) in the build() method. That one is expensive, but idempotent. We should resolve earlier.

**Comment by andreas-schroeder** [comment]
@KGoodale13 avro4s 4.0.0-RC2 is out, in case you want to give it a try without the implicits.

**Comment by KGoodale13** [comment]
Nice, this is faster than 2.0.3 now! Thank you for resolving this! I'll go ahead and close this issue.

```
numberOfEvents -> 500: 20.671ms, 20.589ms, 20.701ms, 20.552ms, 20.665ms
numberOfEvents -> 1000: 41.155ms, 41.125ms, 41.163ms, 60.103ms, 77.547ms
numberOfEvents -> 1500: 61.676ms, 61.674ms, 61.516ms, 61.666ms, 61.466ms
```

**Comment by sksamuel** [comment]
20% faster which is fanastic.
