### ISSUE TITLE
could not find implicit value for parameter schemaFor: com.sksamuel.avro4s.SchemaFor[T]

### ISSUE THREAD

**Issue by nitinpandey-154** [sksamuel/avro4s#503]
Hi,

My requirement takes a class and should return me an avro-schema. Below is the code, I'm trying:

The idea is to achieve something like this

```
import scala.reflect.ClassTag
import com.sksamuel.avro4s.AvroSchema

case class Ingredient(name: String, sugar: Double, fat: Double)

case class Pizza(
    name: String,
    ingredients: Seq[Ingredient],
    vegetarian: Boolean,
    vegan: Boolean,
    calories: Int
)

class AvroUtil[T: ClassTag](implicit m: Manifest[T]) {

  def caseClassToAvroSchema() = {
    val schema = AvroSchema[T]
    schema
  }

}

new AvroUtil[Pizza].caseClassToAvroSchema()

```

How can I fix this?

Error - **could not find implicit value for parameter schemaFor: com.sksamuel.avro4s.SchemaFor[T]**

Scala Version - 2.12.8
Avro4s - "com.sksamuel.avro4s" %% "avro4s-core" % "3.1.1"

**Comment by andreas-schroeder** [comment]
Hi, instead of requiring a `ClassTag` and `Manifest` in AvroUtil signature, you could require an `SchemaFor`, that will do the trick.
