### ISSUE TITLE
Wrong schema for top level union type

### ISSUE THREAD

**Issue by Zuchos** [sksamuel/avro4s#508]
For message with seal trait hierarchy I'm able to generate schema that is union type but after `RecordFormat.to` I'm getting `ImmutableRecord` with schema that only includes type that is being serialized

e.g. 
```
import com.sksamuel.avro4s.{AvroSchema, RecordFormat}
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

sealed trait A

final case class B(name: String) extends A
final case class C(age: Int)     extends A

object A {
  implicit lazy val schema = AvroSchema[A]
}

class AvorSpec extends AnyFlatSpec with Matchers {

  it should "serialize with schema" in {
    //Given
    val b = B("Some")
    //When
    println(A.schema)
    val serialized = RecordFormat[A].to(b)

    //Then
    println(serialized)
  }

}
```
Output
```
[{"type":"record","name":"B","namespace":"com.primavera.warehouse.resources.api.messaging","fields":[{"name":"name","type":"string"}]},{"type":"record","name":"C","namespace":"com.primavera.warehouse.resources.api.messaging","fields":[{"name":"age","type":"int"}]}]
ImmutableRecord({"type":"record","name":"B","namespace":"com.primavera.warehouse.resources.api.messaging","fields":[{"name":"name","type":"string"}]},ArraySeq(Some))
```
I would expect ImmutableRecord to contain union schema. My problem is that when I'm using this with Kafka schema registry I'm sending new schema for each record type instead of the same one for all of them. 

The workaround is to pack hierarchy inside case class e.g. `Envelope(a: A)`

**Comment by andreas-schroeder** [comment]
The workaround you suggest is also something I had been going with in the past, and along the way I discovered that this envelope can be used for passing along data and metadata that all records have.

The thing is, records cannot have a union type as their type - the Avro library wouldn't let you do that. To solve your problem with the Kafka Schema registry, have you considered using a different [subject naming strategy](https://docs.confluent.io/current/schema-registry/serdes-develop/index.html#sr-schemas-subject-name-strategy) in the Kafka schema registry?

**Comment by Zuchos** [comment]
@andreas-schroeder thank you for explaining the problem, it's similar to the "array as top level element" in JSON, it's not valid JSON but some libraries are able to parse it etc. I will stick with "Envelope" workaround, my records already contain metadata, it's quite useful because I don't need to pass them around.
