### ISSUE TITLE
AvroDoc annotation will result in multiple doc fields

### ISSUE THREAD

**Issue by RoccoMathijn** [sksamuel/avro4s#509]
Given this message structure:
```
@AvroDoc("This is record 1")
case class Record1(field: String)
case class Message(record1: Record1)
```

Avro4s will generate the following schema:
```
{
  "type": "record",
  "name": "Message",
  "namespace": "Avro4s",
  "fields": [
    {
      "name": "record1",
      "type": {
        "type": "record",
        "name": "Record1",
        "doc": "This is record 1",
        "fields": [
          {
            "name": "field",
            "type": "string"
          }
        ]
      },
      "doc": "This is record 1"
    }
  ]
}
```

I would like to have it generate a schema where the doc field for Record1 is only in the object where Record1 is defined like this:
```
{
  "type": "record",
  "name": "Message",
  "namespace": "Avro4s",
  "fields": [
    {
      "name": "record1",
      "type": {
        "type": "record",
        "name": "Record1",
        "doc": "This is record 1",
        "fields": [
          {
            "name": "field",
            "type": "string"
          }
        ]
      }
    }
  ]
}
```

Any ideas?

Some background:
We use the io.confluent.kafka.serializers.KafkaAvroSerializer for serializing the message which requires the schema to exactly match the one registered in the Schema Registry (including the doc fields). Since we have multiple producers (over multiple teams) for the same topic we defined a schema centrally and manually upload it to the Schema Registry. This schema is defined like my second example. In this specific producer we use Avrohugger to create the case classes, then manually add the AvroDocs annotations and use Avro4s to transform the case class in a GenericRecord to be used with the KafkaAvroSerializer.

Reproduction:

```
import com.sksamuel.avro4s.{AvroDoc, ToRecord}

object Avro4s extends App {
  @AvroDoc("This is record 1")
  case class Record1(field: String)
  case class Message(record1: Record1)

  val derivedSchema = ToRecord[Message].to(Message(Record1("value"))).getSchema

  println(derivedSchema)
}
```

**Comment by andreas-schroeder** [comment]
Good catch, I am assembling a fix for this.
