### ISSUE TITLE
RecordFormat and polymorphic types

### ISSUE THREAD

**Issue by blbradley** [sksamuel/avro4s#51]
Hello!

I have a case class and `RecordFormat.to` usage like so:

``` scala
// with type mappings for Instant in scope
case class Trade(tid: Long, price: BigDecimal, volume: BigDecimal, timestamp: Instant, tpe: String)

val trades = List(Trade(....))
val listFormat = RecordFormat[List[Trade]]

val listRecord = listFormat.to(trades)
```

which has compilation error:

``` scala
could not find implicit value for parameter toRecord: com.sksamuel.avro4s.ToRecord[List[co.coinsmith.kafka.cryptocoin.Trade]]
[error]   val listFormat = RecordFormat[List[Trade]]
```

Is this code snippet supposed to work? I believe so.

**Comment by sksamuel** [comment]
It doesn't support a list at top level atm. So you would need to wrap it in some object

**Comment by blbradley** [comment]
Ok. Is it your intent to support this without wrapping?

**Comment by blbradley** [comment]
I will gladly make contributions towards this usage if that is your intent.

**Comment by blbradley** [comment]
I see that each Avro record field requires a name. It might not be possible to support this usage without wrapping. Do you agree?

**Comment by sksamuel** [comment]
You might be able to do it of avro allows top level arrays.

**Comment by blbradley** [comment]
Avro does support top level arrays. But records are like a map with some extra metadata. So, I don't think my usage is possible. I would expect `AvroSchema[List[Trade]]` to work but haven't tried it.

So, does `RecordFormat` only work on case classes? Maybe most primitives also? If so, that should be part of the docs for it.

Thanks for your time! I'm satisfied with the discussion but leaving this issue open in case you add documentation.

**Comment by sksamuel** [comment]
Should be able to add this by adding additional implicits in the `RecordFormat` companion object, if you fancy a go.

**Comment by blbradley** [comment]
Whoops! I may give it a go sometime. I'm still trying to determine if I can use this project.

**Comment by sksamuel** [comment]
What's issue with using it?

**Comment by blbradley** [comment]
As mentioned in #56, different scales and precisions across decimals in a single schema. I don't think that is possible without passing some extra mapping to `toSchema`. At that point, I believe it is easier to use the Avro API directly. I haven't decided if I can settle with what I implemented in that PR or if I need more control.

FWIW, this project has be invaluable while prototyping my Avro schemas. I'm likely to use it for that again. Thanks for your work!

**Comment by sksamuel** [comment]
You're welcome.

We support annotations on the fields. So you can do @AvroProp("scale", "10")
