### ISSUE TITLE
Doesn't support java.time.Instant

### ISSUE THREAD

**Issue by irenkamalova** [sksamuel/avro4s#515]
If my case class contain field with java.time.Instant type - I get the next error:

Error:(25, 48) could not find implicit value for evidence parameter of type com.sksamuel.avro4s.FromRecord[MyRecord]
        val is = AvroInputStream.data[MyRecord](bytes)
Error:(25, 48) not enough arguments for method data: (implicit evidence$31: com.sksamuel.avro4s.FromRecord[MyRecord])com.sksamuel.avro4s.AvroDataInputStream[MyRecord].
Unspecified value parameter evidence$31.
        val is = AvroInputStream.data[MyRecord](bytes)
```scala
import java.time.{Duration, Instant}
import java.util

import com.sksamuel.avro4s.AvroInputStream
import org.apache.kafka.clients.consumer.KafkaConsumer

import scala.collection.JavaConverters._

case class MyRecord(id: String, time: Instant)

object Consumer {

  def main(args: Array[String]): Unit = {
    consumeFromKafka()
  }
  def consumeFromKafka(): Unit = {

    val props = Properties.props
    val consumer: KafkaConsumer[String, Array[Byte]] = new KafkaConsumer[String, Array[Byte]](props)
    consumer.subscribe(util.Arrays.asList(Properties.topic))
    while (true) {
      val record = consumer.poll(Duration.ofMillis(1000)).asScala
      for (data <- record.iterator) {
        val bytes = data.value()
        val is = AvroInputStream.data[MyRecord](bytes)
        val users = is.iterator.toSet
        is.close()

        println("len: " + bytes.length)
        println(users.mkString("\n"))
      }
    }
  }
}

```

**Comment by andreas-schroeder** [comment]
Hi, 
try `AvroInputStream.data[MyRecord].from(bytes).build` instead of `AvroInputStream.data[MyRecord](bytes)` (if you are using 4.0.0-RC1 or 3.1.1)

**Comment by irenkamalova** [comment]
For 3.1.1 this is works, but I need to support scala 2.11 in my project, so I can use only vesion 1.8.3

**Comment by sksamuel** [comment]
As I'm sure you know the last update to Scala 2.11 was 2.5 years ago, so I'm afraid we won't be supporting 2.11 anymore.
