### ISSUE TITLE
Serialization roundtrip of optional Coproduct with Array[Byte] in signature deserializes to None 

### ISSUE THREAD

**Issue by kpmeen** [sksamuel/avro4s#520]
I'm trying to get serializers and deserializers to work as expected for a class of the following structure:

```scala
case class Inner(key: String, value: String)

type SimpleCo = Array[Byte] :+: String :+: CNil

@AvroNamespace("simple")
case class SimpleOpt(
    k: Option[SimpleCo] = None,
    v: Array[Byte],
    h: Option[Seq[Inner]] = None
)
```

The schema for the type is produced correctly, and serialization doesn't fail after #505 was merged. However, when I try to deserialize the bytes into an instance of `SimpleOpt` the `k` value is always `None` when the value is of type `Array[Byte]`.

I'm not 100% sure if the data for `k` is omitted at serialization or deserialization, but somewhere along the line the byte array disappears.

Here's a full sample to reproduce the issue using `4.0.0-RC1` using Scala 2.12 with compile flag `-Xsource:2.13`:

```scala
import com.sksamuel.avro4s._
import com.sksamuel.avro4s.kafka.GenericSerde
import shapeless._

object Types {
  @AvroNamespace("simple.inner")
  case class Inner(key: String, value: String)

  type SimpleCo = Array[Byte] :+: String :+: CNil

  @AvroNamespace("simple")
  case class SimpleOpt(
      k: Option[SimpleCo] = None,
      v: Array[Byte],
      h: Option[Seq[Inner]] = None
  )

  object SimpleOpt {
    implicit val schemaFor = SchemaFor[SimpleOpt]
    implicit val enc       = Encoder[SimpleOpt]
    implicit val dec       = Decoder[SimpleOpt]
  }

  @AvroNamespace("payload")
  case class Payload(a: String, b: String)

  object Payload {
    implicit val schemaFor = SchemaFor[Payload]
    implicit val enc       = Encoder[Payload]
    implicit val dec       = Decoder[Payload]
  }
}

class TestSerdes[T >: Null: SchemaFor: Encoder: Decoder]
  extends GenericSerde[T] {

  // scalastyle:off
  def serializeT(data: T): Array[Byte]   = serialize(null, data)
  def deserializeT(data: Array[Byte]): T = deserialize(null, data)
  // scalastyle:on
}

import Types._

val simpleSerdes = new TestSerdes[SimpleOpt]
val payloadSerdes = new TestSerdes[Payload]


println(s"schema: ${SimpleOpt.schemaFor.schema.toString(true)}")

val bytes = "This is a string".getBytes("UTF-8")

val payload1 = Payload("foo", "bar")
val payloadBytes1 = payloadSerdes.serializeT(payload1) // payloadBytes1: Array[Byte] = Array(6, 102, 111, 111, 6, 98, 97, 114)

val simpleOpt0 = SimpleOpt(v = bytes)  // simpleOpt0: Types.SimpleOpt = SimpleOpt(None,[B@458c0924,None)
val simpleOpt1 = SimpleOpt(Some(Coproduct[SimpleCo]("simple1")), bytes) // simpleOpt1: Types.SimpleOpt = SimpleOpt(Some(Inr(Inl(simple1))),[B@458c0924,None)
val simpleOpt2 = SimpleOpt(Some(Coproduct[SimpleCo](payloadBytes1)), bytes) // simpleOpt2: Types.SimpleOpt = SimpleOpt(Some(Inl([B@64012dec)),[B@458c0924,None)
// Serialize
val arrOpt0 = simpleSerdes.serializeT(simpleOpt0) // arrOpt0: Array[Byte] = Array(0, 32, 84, 104, 105, 115, 32, 105, 115, 32, 97, 32, 115, 116, 114, 105, 110, 103, 0)
val arrOpt1 = simpleSerdes.serializeT(simpleOpt1) // arrOpt1: Array[Byte] = Array(4, 14, 115, 105, 109, 112, 108, 101, 49, 32, 84, 104, 105, 115, 32, 105, 115, 32, 97, 32, 115, 116, 114, 105, 110, 103, 0)
val arrOpt2 = simpleSerdes.serializeT(simpleOpt2) // arrOpt2: Array[Byte] = Array(2, 16, 6, 102, 111, 111, 6, 98, 97, 114, 32, 84, 104, 105, 115, 32, 105, 115, 32, 97, 32, 115, 116, 114, 105, 110, 103, 0)

// Deserialize
val desOpt0 = simpleSerdes.deserializeT(arrOpt0) // desOpt0: Types.SimpleOpt = SimpleOpt(None,[B@7cf7ecdc,None)
val desOpt1 = simpleSerdes.deserializeT(arrOpt1) // desOpt1: Types.SimpleOpt = SimpleOpt(Some(Inr(Inl(simple1))),[B@5db7c142,None)
val desOpt2 = simpleSerdes.deserializeT(arrOpt2) // desOpt2: Types.SimpleOpt = SimpleOpt(None,[B@6cdd6c85,None)
```

I'm going to continue digging for a reason why this happens, but if this is a known issue it would be great to know.

**Comment by kpmeen** [comment]
Maybe you have and idea about what is going on @andreas-schroeder ?

**Comment by kpmeen** [comment]
I've been debugging a bit now, and it certainly _seems_ to me that the `k: Option[SimpleCo]` value is serialized correctly.
The problem seems to be in the `com.sksamuel.avro4s.Records#decode(value: Any): T` function. Where the value is transformed into a `None` on line [51](https://github.com/sksamuel/avro4s/blob/master/avro4s-core/src/main/scala/com/sksamuel/avro4s/Records.scala#L51).
Futher stepping through the call chain takes me to line [80](https://github.com/sksamuel/avro4s/blob/master/avro4s-core/src/main/scala/com/sksamuel/avro4s/RecordFields.scala#L80) in `com.sksamuel.avro4s.RecordFields`, where an exception is swallowed by the `NonFatal` case handling. The parameter `k` does indeed have a default parameter `None` which is what is returned. But the fact is that an `Avro4sDecodingException` is swallowed with the message:

```
Unable to decode value 'java.nio.HeapByteBuffer[pos=0 lim=12 cap=12]'
```

Note that this _only_ happens if the value of `k` is a `Some(Coproduct[Array[Byte]](bytes))`. Is there a way to prevent or fix this error from happening?

**Comment by andreas-schroeder** [comment]
@kpmeen thanks for the details, I will look at it as soon as I find some time. I think I will come back to you on Monday.

**Comment by andreas-schroeder** [comment]
@kpmeen this is a bug in coproduct decoding not considering properly how byte arrays are encoded.
Thanks for reporting and for the reproducer! For the fix, see #522 - I must say though that I wouldn't know how to easily do reproduce the fix client-side; the best option to go forward with 4.0.0 would be to write a custom decoder for the Coproduct.

**Comment by kpmeen** [comment]
Thanks for looking into this @andreas-schroeder! :+1:
I think this fix will at least cover my specific use-case. I'll see if I can verify it sometime during the next couple of days
What would a custom decoder for such a coproduct potentially look like, do you think?

**Comment by andreas-schroeder** [comment]
@kpmeen try something like
```scala
  implicit val decoder: Decoder[SimpleCo] = new Decoder[SimpleCo] {

    val stringDecoder = Decoder[String]

    def decode(value: Any): SimpleCo = {
      case bytes: ByteBuffer => Coproduct[SimpleCo](bytes)
      case _                 => Coproduct[SimpleCo](stringDecoder.decode(value))
    }

    val schemaFor: SchemaFor[SimpleCo] = SchemaFor[SimpleCo]
  }
```
