### ISSUE TITLE
Generation problem with union type of only one value.

### ISSUE THREAD

**Issue by joelvim** [sksamuel/avro4s#524]
We used to generate schema from case classes, starting with version 2.x of avro4s. We used shapeless coproducts to represent sealed traits. In some classes, we had a coproduct with only one value (the sealed trait, at the moment had only one implementation possible).
For instance, let's say that one field of our class was of type `Long :+: CNil`. The generated type in avro schema was `["long"]` which is fine.
We then decided to change the way we worked in order to make the avro schema the source of truth. We now commit the avro schema, using the generation to write them into a file, and replace our old case classes by case class generation.
In that case, an avro field on type `["long"]` for example in now generated as type `Long` in scala instead of `Long :+: CNil`, so it seems to break the compatibility between the avro schema and the generated code: data serialized with the 2.x codebase cannot be deserialized by 3.x codebase.
With 4.x code base, I observed another behavior: data serialized with 2.x can be deserialized explicitely passing the textual schema to the deserializer, but 4.x does not allow passing a schema to the serializer, so it relies on the schema infered from the code, which is different than the textual one, so it fails.

An example: 
*Avro schema*
```
{
  "type":"record",
  "name":"TestData",
  "namespace":"my.namespace",
  "fields":[
    {"name":"longValue","type":"long"},
    {"name":"unionValue","type":["long"]},
    {"name":"stringValue","type":"string"}
  ]
}
```

*Generated case class (the union type is lost)*
```
final case class TestData(longValue: Long, unionValue: Long, stringValue: String)
```

*Expected generated code (at least one possibility)*
```
final case class TestData(longValue: Long, unionValue: Long :+: CNil, stringValue: String)
```

NB: I understand that using a union when having a single type inside is not really smart, but we have to keep it for legacy support.
NB2: We could get rid of using code generation, in one way or another, but it is a great feature.

**Comment by joelvim** [comment]
I realize that it may be an inconsistency between sbt-avrohugger code generation and avro4s schema inference. Should I move this issue to sbt-avrohugger?

**Comment by andreas-schroeder** [comment]
You can pass a schema to encoders/decoders via .withSchema, however I think that validation of the schema type might make it fail. Did you try that?

**Comment by andreas-schroeder** [comment]
You can also open an issue on avrohugger since the generated code doesn't reflect the schema faithfully, yes.

**Comment by joelvim** [comment]
I figured out what was wrong. The default configuration of sbt-avrohugger for union types is `OptionEitherShapelessCoproduct` that seem to use `Coproduct` if the union has at least 3 types, `Either` if there are 2 types, and drops the union if there is only one type (which does not seem correct to me). Using `OptionalShapelessCoproduct` uses `Coproduct` every time there is a union, even if only one type, so it does not drop the union.
I think I am gonna open a bug on avrohugger because dropping the union does not seem normal (I don't know how a union with only one type is serialized, maybe it is equivalent, but I doubt it seeing the behaviour observed above).
