### ISSUE TITLE
Primitive type schemas

### ISSUE THREAD

**Issue by MLnick** [sksamuel/avro4s#54]
Hi @sksamuel 
 
When I used to do `println(AvroSchema[Double])`, it would return `"double"`. Now it seems to do `{"type":"record","name":"Double","namespace":"scala","fields":[]}`.

Not sure if I'm doing something wrong here?

**Comment by sksamuel** [comment]
I've fixed this for 1.5.7 when its released.

**Comment by MLnick** [comment]
Thanks! Does it also apply to things like `Array[Double]` or `Map`? The result is similar, e.g. `{"type":"record","name":"Array","namespace":"scala","fields":[{"name":"_length","type":"int"}]}`

It used to be all the implicits in `object ToSchema` seemed to handle this?

**Comment by sksamuel** [comment]
I've only added the raw primitives, not map or array. I guess we can add the entire lot.

**Comment by MLnick** [comment]
it would help me quite a lot if it's not too much trouble :)
