### ISSUE TITLE
Support for deserializing top level different multiple objects

### ISSUE THREAD

**Issue by berkesokhan** [sksamuel/avro4s#541]
This is more of a question (or a feature request if not implemented). How do you deserialize a message which is sent via Kafka using below AVSC at the top level for a topic:

[
    {
        "type": "record",
        "name": "EventA",
        "namespace": "com.demo.events",
        "doc": "....",
        "fields": [...]
    },
    {
        "type": "record",
        "name": "EventB",
        "namespace": "com.demo.events",
        "doc": "...",
        "fields": [...]
    },
    {
        "type": "record",
        "name": "EventC",
        "namespace": "com.demo.events",
        "doc": "...",
        "fields": [...]
    }
]

**Comment by andreas-schroeder** [comment]
You would use a shapeless coproduct for that: `EventA :+: EventB :+: EventC` or a sealed trait with subtypes:

```scala
sealed trait Event
case class EventA( /* ... */ ) extends Event
// ...
```
