### ISSUE TITLE
Custom field name TypeMapper ends with `missing parameter type for expanded function`

### ISSUE THREAD

**Issue by fpopic** [sksamuel/avro4s#547]
Hi,

I was following the [README](https://github.com/sksamuel/avro4s/blob/master/README.md#field-mapping) example to use custom field names defining implicit TypeMapper as:

```scala
implicit val short: FieldMapper = {
  case "userName"     => "user"
  case "emailAddress" => "email"
}
``` 

But I get 

```log
[error] .../Main.scala:41:41: missing parameter type for expanded function
[error] The argument types of an anonymous function must be fully known. (SLS 8.5)
[error] Expected type was: com.sksamuel.avro4s.FieldMapper
[error]       implicit val short: FieldMapper = {
[error]                                         ^
[error] one error found
[error] Compilation failed
```

There is also opened StackOverflow [ticket](https://stackoverflow.com/questions/62184491/avro4s-the-argument-types-of-an-anonymous-function-must-be-fully-known-sls-8).

**Comment by andreas-schroeder** [comment]
Hey @fpopic , thanks for pointing this out. The docs are wrong here, FieldMapper can't be extended as it is a sealed trait. Customizing names works only via `@AvroName` annotations on the class parameter itself. I will take care of fixing the docs. Do you have a use-case where that annotation is difficult?

**Comment by fpopic** [comment]
Hi,

yeah, a bit pitty we can't provide a custom name field mapper implementation. My use case would to override `snake_case`.

```scala
import com.sksamuel.avro4s.{AvroSchema, FieldMapper, RecordFormat, SnakeCase}

val extendedSnakeFieldMapper new FieldMapper {
  override def to(name: String): String = {
    name match {
      case "e2EId" => "e2e_id"
      case camelCaseName => SnakeCase.to(camelCaseName)
    }
  }
}
``` 

Does annotation `@AvroName` have priority over a `SnakeCase` mapper if both are provided?

We have some common pipeline conversions (Kafka Protobuf (ScalaPB) messages -> Scala Case Class (Apache Beam) -> (avro4s) Avro BigQuery) so can try to define a custom ScalaPB [field option](https://scalapb.github.io/docs/user_defined_options) that will basically set an Avro annotation

**Comment by andreas-schroeder** [comment]
Hm I see. Well at least the avroName does have priority over the fieldmapper, see https://github.com/sksamuel/avro4s/blob/baf372e05ab8e63ff6e7fe5cb68dbe23a5ba48fc/avro4s-core/src/main/scala/com/sksamuel/avro4s/RecordFields.scala#L158 I am actually not seeing much benefit from the FieldMapper trait being sealed... @sksamuel what do you think, could & shoukd we remove the sealing there?

**Comment by fpopic** [comment]
It worked https://github.com/fpopic/proto-scalapb-to-avro4s/blob/master/protobuf/my_case_class_with_fields_annotation.proto#L15.
