### ISSUE TITLE
Backward compatibility is not fully supported for enums

### ISSUE THREAD

**Issue by yeryomenkom** [sksamuel/avro4s#548]
Hi!
I've realised the following problem. If you use in some model field of type Seq[SomeEnum], backward compatibility doesn’t work. So, the next test will fail:
```
import com.sksamuel.avro4s._
import org.scalatest.freespec.AnyFreeSpec
import org.scalatest.matchers.should.Matchers

object Initial {
  @AvroNamespace("test.namespace")
  case class Foo(enums: Seq[Enum])

  @AvroEnumDefault(Enum.Default)
  sealed trait Enum
  object Enum {
    @AvroSortPriority(0) case object Default extends Enum
    @AvroSortPriority(1) case object A extends Enum
  }
}

object BackwardCompatibleChange {
  @AvroNamespace("test.namespace")
  case class Foo(enums: Seq[Enum])

  @AvroEnumDefault(Enum.Default)
  sealed trait Enum
  object Enum {
    @AvroSortPriority(0) case object Default extends Enum
    @AvroSortPriority(1) case object A extends Enum
    @AvroSortPriority(2) case object B extends Enum
  }
}

class CompatibilitySpec extends AnyFreeSpec with Matchers with KafkaSerdesSupport {
  "Deserializer" - {
    "should work properly for old and new versions" - {
      "when schema has changed in a backward compatible way" in {
        val fooOld = Initial.Foo(Seq(Initial.Enum.A))
        val fooNew = BackwardCompatibleChange.Foo(Seq(BackwardCompatibleChange.Enum.B))

        val oldSerialized = Encoder[Initial.Foo].encode(fooOld)
        val newSerialized = Encoder[BackwardCompatibleChange.Foo].encode(fooNew)

        noException should be thrownBy {
          info("Old record in new env: " + Decoder[BackwardCompatibleChange.Foo].decode(oldSerialized))
          info("New record in old env: " + Decoder[Initial.Foo].decode(newSerialized))
        }
      }
    }
  }

}
```

**Comment by yeryomenkom** [comment]
Any reaction to this?

**Comment by davideicardi** [comment]
What happen if you change the order of priorities? Using 0, -1, -2, ... 
Because elements are sorted descending... so to keep the first on top it should be the greatest number.

```
object Initial {
  @AvroNamespace("test.namespace")
  case class Foo(enums: Seq[Enum])

  @AvroEnumDefault(Enum.Default)
  sealed trait Enum
  object Enum {
    @AvroSortPriority(0) case object Default extends Enum
    @AvroSortPriority(-1) case object A extends Enum
  }
}

object BackwardCompatibleChange {
  @AvroNamespace("test.namespace")
  case class Foo(enums: Seq[Enum])

  @AvroEnumDefault(Enum.Default)
  sealed trait Enum
  object Enum {
    @AvroSortPriority(0) case object Default extends Enum
    @AvroSortPriority(-1) case object A extends Enum
    @AvroSortPriority(-2) case object B extends Enum
  }
}
```

**Comment by yeryomenkom** [comment]
> What happen if you change the order of priorities? Using 0, -1, -2, ...
> Because elements are sorted descending... so to keep the first on top it should be the greatest number.
> 
> ```
> object Initial {
>   @AvroNamespace("test.namespace")
>   case class Foo(enums: Seq[Enum])
> 
>   @AvroEnumDefault(Enum.Default)
>   sealed trait Enum
>   object Enum {
>     @AvroSortPriority(0) case object Default extends Enum
>     @AvroSortPriority(-1) case object A extends Enum
>   }
> }
> 
> object BackwardCompatibleChange {
>   @AvroNamespace("test.namespace")
>   case class Foo(enums: Seq[Enum])
> 
>   @AvroEnumDefault(Enum.Default)
>   sealed trait Enum
>   object Enum {
>     @AvroSortPriority(0) case object Default extends Enum
>     @AvroSortPriority(-1) case object A extends Enum
>     @AvroSortPriority(-2) case object B extends Enum
>   }
> }
> ```

it doesn't help. 
also I think that priorities should not affect the way have default enum case should be picked.

**Comment by yeryomenkom** [comment]
reopen the issue please
