### ISSUE TITLE
allow java.time.Instant codec decode/encode data with respects to avro logical-type

### ISSUE THREAD

**Issue by chenharryhua** [sksamuel/avro4s#549]
Looks like Instant codec use fixed schema to do encode/decode [https://github.com/sksamuel/avro4s/blob/master/avro4s-core/src/main/scala/com/sksamuel/avro4s/Temporals.scala#L12](url) such that if I use .withSchema to change the logical-type of the schema to "timestamp-micros", it did not encode/decode accordingly.

One way to overcome it is to implement a customized version of Instant as mentioned in the homepage. it works but the import tax is non trivial.

is there something I overlooked?

**Comment by andreas-schroeder** [comment]
Hi @chenharryhua , thanks for reporting, that is indeed an interesting issue; we should support all existing logical types here similar to what we do in https://github.com/sksamuel/avro4s/blob/master/avro4s-core/src/main/scala/com/sksamuel/avro4s/BaseTypes.scala#L228

**Comment by chenharryhua** [comment]
Thanks @andreas-schroeder for reply. In my mind, it looks more like the LocalDateTime codec: https://github.com/sksamuel/avro4s/blob/master/avro4s-core/src/main/scala/com/sksamuel/avro4s/Temporals.scala#L31
