### ISSUE TITLE
undocumented default snappy compression

### ISSUE THREAD

**Issue by Zhen-hao** [sksamuel/avro4s#570]
I'm using this library in my own serializer for Akka persistence, 
which uses this function
```
  def toBin[T: Encoder](o: T): Array[Byte] = {

    val output = new ByteArrayOutputStream
    val avro = AvroOutputStream.binary[T].to(output).build()
    avro.write(o)
    avro.close()

    output.toByteArray
  }
```
I got the following error from line `val avro = AvroOutputStream.binary[T].to(output).build()
`.

```
[info] [2020-10-10 20:20:06,977] [DEBUG] [org.apache.avro.file.CodecFactory] [] [nt-ui-akka.persistence.cassandra.default-dispatcher-32] - Snappy was not available {}
[info] java.lang.NoClassDefFoundError: org/xerial/snappy/Snappy
[info]  at org.apache.avro.file.SnappyCodec$Option.<clinit>(SnappyCodec.java:34)
[info]  at org.apache.avro.file.CodecFactory.snappyCodec(CodecFactory.java:69)
[info]  at org.apache.avro.file.CodecFactory.<clinit>(CodecFactory.java:125)
[info]  at com.sksamuel.avro4s.AvroOutputStreamBuilderWithSource$.$lessinit$greater$default$3(AvroOutputStream.scala:52)
```

It seems that snappy is set as the default value of some argument. 
however, I couldn't find documentation or code about it.

**Comment by sksamuel** [comment]
It's avro itself that does this. You can see in the CodecFactory class it tries to load snappy. It's supposed to catch it in Avro 1.9. Is another version of avro on the classpath ?

**Comment by Zhen-hao** [comment]
I don't have other avro dependencies.
But I solved the issue by adding snappy-java to `libraryDependencies`

**Comment by adrian-salajan** [comment]
In my case snappy was brought by: akka-serialization-jackson
so i excluded it.
```
   excludeDependencies ++= Seq(
        ExclusionRule("org.xerial.snappy", "snappy-java")
      )
```

**Comment by Zhen-hao** [comment]
for me, using snappy is fine. but I'm concerned with this behavior with the Avro library. 
you never know what future dependencies can suddenly change your compression method. 
that's why I am using snappy all the time to be safe.

closing since it is supposed to be fixed in new Avro versions
