### ISSUE TITLE
Scala 2.11 support for 4.0.x

### ISSUE THREAD

**Issue by burakkose** [sksamuel/avro4s#589]
Hey @sksamuel, thanks for your effort to maintain the library with other contributors. I understand that 2.11 in not really desirable anymore, but how difficult to release the new version for it? There are many platforms in big data still using 2.11, and difficult to migrate it.

**Comment by sksamuel** [comment]
If you can make a branch that works with 2.11 then I will merge it in. I suspect that you will struggle however because magnolia, a key dependency, stopped scala 2.11 support last year. https://search.maven.org/search?q=a:magnolia_2.11
