### ISSUE TITLE
Decimal fields with different scales decoded incorrectly to BigDecimal

### ISSUE THREAD

**Issue by tomasz-dudziak** [sksamuel/avro4s#595]
Hey Sam, long time no see! Hope you are well.

My problem is I have a GenericRecord with multiple decimal fields, each with a different scale, but with the same precision of 18 and the same value of 111:
* field big_number with scale 0 gets decoded to 1.11
* field big_number2 with scale 2 gets decoded to 111
* field big_number3 with scale 4 gets decoded to 11100

So it seems every field gets decoded as if its scale was 2 even though GenericRecord explicitly defines scale for each of those fields. I use version 3.1.1 of avro4s with Scala 2.13.

**Comment by sksamuel** [comment]
Hey Tom, nice to hear from you :+1: 

Have you tried 4.0.3? That should use the values from the schema when decoding big decimals.

**Comment by tomasz-dudziak** [comment]
I tried 4.0.3 now, but I does not seem to have worked. 
Let me provide more details. In my testing I use the following classes:
``` scala
case class DebeziumValue[T](before: Option[String],
                            after: Option[T],
                            source: Source,
                            op: String,
                            ts_ms: Option[Long],
                            transaction: Option[ConnectDefault])

case class Person(id: Option[Int],
                    name: Option[String],
                    age: Option[Int],
                    location: Option[String],
                    big_number: Option[BigDecimal],
                    big_number2: Option[BigDecimal],
                    big_number3: Option[BigDecimal],
                    big_number4: Option[BigDecimal])
```
Then I run:
``` scala
print(RecordFormat[DebeziumValue[Person]].from(record))
```
which results in (I highlighted the decimal columns in bold):

DebeziumValue(None,Some(Person(Some(5),Some(Tom),None,None,***Some(1.11)***,***Some(111.00)***,***Some(11100.00)***,***Some(11100.00)***)),Source(1.1.0-SNAPSHOT,blahblahlblah.Scratch,1606748785228,Some(false),Scratch,dbo,people,Some(199),true),c,Some(1606748785228),None)

As I said, the original value in each of the fields is 111 and their scales are:
* big_number - 0
* big_number - 2
* big_number3 - 4
* big_number4 -4

Record's schema is as attached:
[avro_schema.txt](https://github.com/sksamuel/avro4s/files/5616781/avro_schema.txt)

**Comment by sksamuel** [comment]
Do you know the scales in advance (because you can use an annotation to set
this) or is it entirely dynamic?

**Comment by tomasz-dudziak** [comment]
Yes, I do actually. How should I annotate each field? Could you give me an example?

**Comment by sksamuel** [comment]
There is no annotation I'm getting confused. So you have 111 as the value in the generic record, but with different scales, and what outputs are you getting ?

**Comment by tomasz-dudziak** [comment]
Correct, the value is 111 in each field of the generic record.
* field big_number with scale 0 gets decoded to 1.11
* field big_number2 with scale 2 gets decoded to 111 (the only correct decoding)
* field big_number3 with scale 4 gets decoded to 11100
* field big_number4 with scale 4 gets decoded to 11100

**Comment by tomasz-dudziak** [comment]
Sorry, perhaps I was not completely clear. I meant the value is 111 when you consider the scale whereas the actual representation is a byte buffer. 

Let me illustrate it with a code example. I defined the following functions:
```scala
  def getByteBuffer(record: ConsumerRecord[GenericRecord, GenericRecord], fieldName: String): Option[java.nio.ByteBuffer] = {
    Option(
      record
        .value()
        .get("after")
        .asInstanceOf[GenericRecord]
        .get(fieldName)
        .asInstanceOf[java.nio.ByteBuffer]
    )
  }

  def getBigInt(record: ConsumerRecord[GenericRecord, GenericRecord], fieldName: String): Option[BigInt] =
    getByteBuffer(record, fieldName).map(byteBuffer => BigInt(byteBuffer.array))

  def getBigDecimal(record: ConsumerRecord[GenericRecord, GenericRecord], fieldName: String, scale: Int): Option[BigDecimal] =
    getBigInt(record, fieldName).map(bigInt => BigDecimal(bigInt, scale))
```
Now, if I run something like this on my record:
```scala
println(s"${getBigInt(record, "big_number")}, ${getBigDecimal(record, "big_number", 0)}")
println(s"${getBigInt(record, "big_number2")}, ${getBigDecimal(record, "big_number2", 2)}")
println(s"${getBigInt(record, "big_number3")}, ${getBigDecimal(record, "big_number3", 4)}")
println(s"${getBigInt(record, "big_number4")}, ${getBigDecimal(record, "big_number4", 4)}")
```
I get:
```
Some(111), Some(111)
Some(11100), Some(111.00)
Some(1110000), Some(111.0000)
Some(1110000), Some(111.0000)
```
So that is effectively my manual conversion of a field from GenericRecord to BigDecimal, where I explicitly specify the scale. It works as expected. However avro4s seems to act as if in every case the scale parameter passed was 2 despite the fact that information about what scale should be applied is available in GenericRecord's schema. For example the chunk of schema for field big_number looks like this:
```
{"name":"big_number","type":["null",{"type":"bytes","scale":0,"precision":18,"connect.version":1,"connect.parameters":{"scale":"0","connect.decimal.precision":"18"},"connect.name":"org.apache.kafka.connect.data.Decimal","logicalType":"decimal"}],"default":null}
```
