### ISSUE TITLE
Deep nested structure results in "Method too large" error during scalac compilation

### ISSUE THREAD

**Issue by fsarradin** [sksamuel/avro4s#602]
Hi,

I've got this error message

```
scalac: Error while emitting io/univalence/avro_serde/Main$
Method too large: io/univalence/avro_serde/Main$.main ([Ljava/lang/String;)V
```

For the following IDL: https://gist.github.com/fsarradin/da8049e388e39de8e34ba17d24b54457

And for this code

```scala
package io.univalence.avro_serde

import com.sksamuel.avro4s.JsonFormat
import com.sksamuel.avro4s.kafka.GenericSerde
import test.entity.Entity

object Main {
  def main(args: Array[String]): Unit = {
    val entitySerde = new GenericSerde[Entity](JsonFormat)
    println(entitySerde)
  }
}
```

Do you know why I got this message and how to avoid it?

I'm using
* Avro4s 4.0.0
* Scala 2.13.3
* SBT 1.3.13
* SBT-AvroHugger 2.0.0-RC22

**Comment by sksamuel** [comment]
Do you have a huge class hierarchy ?

**Comment by fsarradin** [comment]
I've just added in the Gist the generated class hierarchy:
* [TestEntity.scala](https://gist.github.com/fsarradin/da8049e388e39de8e34ba17d24b54457#file-testentity-scala)
* [Currency.java](https://gist.github.com/fsarradin/da8049e388e39de8e34ba17d24b54457#file-currency-java)

**Comment by sksamuel** [comment]
Yes it's giant. You would need to split it up.

**Comment by fsarradin** [comment]
Actually, I cannot change this Avro schema as it is based on a standard and used in production in Kafka topics.

Is there other possibilities or does such structure reach the limit of Scala macro?

**Comment by sksamuel** [comment]
If you split up the macro by introducing intermediate schemas it _should_ work.

Eg, if you had

```scala
case class Goo(a: String)
case class Woo(a: Int)
case class Foo(a: Goo, b: Woo)
```

then you can do something like:

```scala
implicit val gschema = AvroSchema[Goo]
implicit val wschema = AvroSchema[Woo]
implicit val fschema = AvroSchema[Foo]
```

This should force the compiler to generate smaller macro methods.

You can try by picking 2 or 3 large nested types and pulling out the implicits. You need to do it for schemas and encoders / decoders.

**Comment by fsarradin** [comment]
I understand that by dividing the big structure, it will work. But, by being just a dev in a small team in a big organization, I'm not the one who manages the schema and its modifications. I'm also not the one that produces the Avro messages from such schema on the Kafka topic. I'm only on the consumer side and I should conform to the imposed schema. The solution of dividing the schema would be a too expensive approach knowing that there are other consumers of such structure managed by other teams. Modifying the schema in a non-compatible way would need imposing migration and team synchronization.

My other solutions would be 1/ to keep avrohugger and use Confluent serde 2/ to use sbt-avro and use Confluent serde. This will help me to keep an automatic approach from Avro IDL to Avro messages serde. But I lose the benefits of the potential performances to use Scala macro and the possibility to generate messages in JSON for local development.

I just understand that the error "Method too large" does not come from a limitation of Scala but from a constraints imposed by the JVM (see https://github.com/sbt/sbt-jacoco/issues/101#issuecomment-725509086 and `code_length` description in https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.3 – no more than 64kb).

Isn't there a possibility to generate intermediate methods (ans method calls) when you have to deal with a giant structure you cannot change? Or is it a question for the Magnolia project?

**Comment by sksamuel** [comment]
My suggestion won't change the structure of your domain model or schema.
It just instructs the compiler to pull intermediate code out into separate methods (if it works). Please try it.

**Comment by fsarradin** [comment]
Ok. It works and I've finally understood the underlying mechanism you were trying to explain :)

However, this breaks the automatic workflow I've setup which goes from the AVDL declaration to the serde usage by including a manual step where I've to explicitly specify implicit declaration. Your solution works and is quite elegant. But I will have to repeat this solution for every big structure I'll have to deal with, knowing I can't guess the number of implicit declarations I have to write down until the compiler accept my code.

**Comment by LBsh** [comment]
Hi I'm having this problem as well but the above suggested method still doesn't work.
Here's dilemma:
* We wrap all implicits in one single object `AvroSchemas`, and during compilation it throws `Method too large: com/etsy/featurepipe/AvroSchemas$.<init> ()V`

like this:

```scala
object AvroSchemas {
  implicit val gschema = AvroSchema[Goo]
  implicit val wschema = AvroSchema[Woo]
  implicit val fschema = AvroSchema[Foo]
}
```

* We then tried separating the implicits and put each in a different object
```scala
object gs {
  implicit val gschema = AvroSchema[Goo]
}
object ws {
  implicit val wschema = AvroSchema[Woo]
}
object fs {
  implicit val fschema = AvroSchema[Foo]
}
```

but then object `fs` is not benefiting from the above 2 smaller objects.

If try importing gs and ws into fs, then it will say 'not used' which will fail compilation because we don't allow unused import.

How can we do in this case?

**Comment by LBsh** [comment]
Hi I'm having this problem as well but the above suggested method still doesn't work.
Here's dilemma:
* We wrap all implicits in one single object `AvroSchemas`, and during compilation it throws `Method too large: xxx/AvroSchemas$.<init> ()V`

like this:

```scala
object AvroSchemas {
  implicit val gschema = AvroSchema[Goo]
  implicit val wschema = AvroSchema[Woo]
  implicit val fschema = AvroSchema[Foo]
}
```

* We then tried separating the implicits and put each in a different object
```scala
object gs {
  implicit val gschema = AvroSchema[Goo]
}
object ws {
  implicit val wschema = AvroSchema[Woo]
}
object fs {
  implicit val fschema = AvroSchema[Foo]
}
```

but then object `fs` is not benefiting from the above 2 smaller objects.

If try importing gs and ws into fs, then it will say 'not used' which will fail compilation because we don't allow unused import.

What can we do in this case?

**Comment by sksamuel** [comment]
> Ok. It works and I've finally understood the underlying mechanism you were trying to explain :)
> 
> However, this breaks the automatic workflow I've setup which goes from the AVDL declaration to the serde usage by including a manual step where I've to explicitly specify implicit declaration. Your solution works and is quite elegant. But I will have to repeat this solution for every big structure I'll have to deal with, knowing I can't guess the number of implicit declarations I have to write down until the compiler accept my code.

You might be able to do something when you generate your code, that makes an implicit for every case class.

**Comment by sksamuel** [comment]
> Hi I'm having this problem as well but the above suggested method still doesn't work.
> Here's dilemma:
> 
> * We wrap all implicits in one single object `AvroSchemas`, and during compilation it throws `Method too large: xxx/AvroSchemas$.<init> ()V`
> 
> like this:
> 
> ```scala
> object AvroSchemas {
>   implicit val gschema = AvroSchema[Goo]
>   implicit val wschema = AvroSchema[Woo]
>   implicit val fschema = AvroSchema[Foo]
> }
> ```

> What can we do in this case?

Those 3 implicits would not share the same method. So having them in one object is not your problem. There must be a huge object graph inside one of those types, and adding implicit steps will work for you.

**Comment by sksamuel** [comment]
> Hi I'm having this problem as well but the above suggested method still doesn't work.
> Here's dilemma:
> 
> * We wrap all implicits in one single object `AvroSchemas`, and during compilation it throws `Method too large: xxx/AvroSchemas$.<init> ()V`
> 
> like this:
> 
> ```scala
> object AvroSchemas {
>   implicit val gschema = AvroSchema[Goo]
>   implicit val wschema = AvroSchema[Woo]
>   implicit val fschema = AvroSchema[Foo]
> }
> ```
> 
> * We then tried separating the implicits and put each in a different object
> 
> ```scala
> object gs {
>   implicit val gschema = AvroSchema[Goo]
> }
> object ws {
>   implicit val wschema = AvroSchema[Woo]
> }
> object fs {
>   implicit val fschema = AvroSchema[Foo]
> }
> ```
> 
> but then object `fs` is not benefiting from the above 2 smaller objects.
> 
> If try importing gs and ws into fs, then it will say 'not used' which will fail compilation because we don't allow unused import.
> 
> What can we do in this case?

avro4s builds schemas using `SchemaFor` so you could split out the three types, and then add an implicit schema for where you need it.

```
object gs {
  implicit val gschema = AvroSchema[Goo]
}
object ws {
  implicit val wschema = AvroSchema[Woo]
}
object fs {
  implicit val useG = new SchemaFor[Goo] { .... }
  implicit val useW = new SchemaFor[Woo] { .... }
  implicit val fschema = AvroSchema[Foo]
}
```

**Comment by LBsh** [comment]
Thank you! It worked perfectly this way.

Just a note that my intellij (2019.3.5) was not smart enough that it indicates me to implement the below function in the `{ .... }`

```scala
 override def schema(fieldMapper: FieldMapper): Schema = ???
```

however it's these two functions that bypass the compilation

```scala
def fieldMapper: com.sksamuel.avro4s.FieldMapper = DefaultFieldMapper
def schema: Schema = QueryAvroSchema.queryAvroSchema
```

otherwise, we are able to use it without problem
