### ISSUE TITLE
How to decode timestamp-micros

### ISSUE THREAD

**Issue by KannarFr** [sksamuel/avro4s#608]
I see the Avro specification does not support timestamp-nanos which is the avro4s default for LocalDateTime.

```
{
    "name" : "epoch_micros",
    "type" : {
      "type" : "long",
      "logicalType" : "timestamp-nanos"
    }
  }
```

wanted: 

```
{
    "name" : "epoch_micros",
    "type" : "long",
    "logicalType" : "timestamp-micros"
  }
```

How to override it to directly decode timestamp-micros to LocalDateTime?

**Comment by KannarFr** [comment]
Adding

```
    implicit object LocalDateTimeOverride extends SchemaFor[LocalDateTime] {
      override def schema(fieldMapper: FieldMapper): Schema = LogicalTypes.timestampMicros.addToSchema(SchemaBuilder.builder.longType)
    }
``` 

fixes the issue (as pulsar4s uses avro4s 3.1.0). But I definitely think timestamp-nanos should not existing as it doesn't in the avro spec (even if it's a good idea :p).

**Comment by sksamuel** [comment]
Yes, what you've done is right.
pulsar4s will be upgraded to use avro4s 4.0.4

**Comment by KannarFr** [comment]
Hum not well fixed, got timestamp-micros, but it's defined as `type` body and it must be at the same level, correct?

**Comment by KannarFr** [comment]
```
{
    "name" : "epoch_micros",
    "type" : "long",
    "logicalType" : "timestamp-micros"
  }``` 
  
  against
  
  ```
{
    "name" : "epoch_micros",
    "type" : {
      "type" : "long",
      "logicalType" : "timestamp-micros"
    }
  }
```

WDYT @sksamuel?

**Comment by sksamuel** [comment]
Yeah looks correct to me.
https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/LogicalTypes.TimeMillis.html

**Comment by jakubciepiela** [comment]
Hi,
I picked up avro4s 4.0.4 and it still encodes java.time.LocalDateTime into timestamp-nanos
