### ISSUE TITLE
add nonEmptySet to cats

### ISSUE THREAD

**Issue by TimPigden** [sksamuel/avro4s#609]
could you add nonEmptySet to the cats encoders please?

**Comment by sksamuel** [comment]
Can you make a PR and I will make the release ?

**Comment by TimPigden** [comment]
Hmm - it turns out to be rather difficult. Cats nonEmptySet is based on treeset which requires an Order[T] which was done because they wanted to avoid universal equality and didn't want to write a completely new set implementation from scratch (as far as I can tell). Anyhow, I can't figure a clean way to do this and resorted to storing my data as nonemptyvector in a proxy class. Do you want to close the issue?

**Comment by sksamuel** [comment]
Yes can do.
