### ISSUE TITLE
How to export schema

### ISSUE THREAD

**Issue by florianmutter** [sksamuel/avro4s#611]
I want to provide the schema to other developers. Therefor I would like to write the generated avro schema to a file. During compile time so I can add it to git. Is this possible?

**Comment by atnoya** [comment]
I would be interested on this as well, does anybody know a quick workaround to get this sorted?

**Comment by Zhen-hao** [comment]
I don't know how to write it here in a short time.

If anyone is interested in this, you can post a pairing request on https://pairtime.com with tags like `avro`, `scala`, or `avro4s`.
I can share my screen to show you how I did it in my project (used in production). 
I will charge a very small fee, 10 USD (or EUR) per hour, more for testing the platform than making money for myself.
