### ISSUE TITLE
Deserialising ADT

### ISSUE THREAD

**Issue by rabzu** [sksamuel/avro4s#62]
Hi,
how  to map to avro:

```
sealed trait A
case class B(id: String) extends A
case class C(id: String) extends A
case class D(a: A)



def toBinary[T: SchemaFor : ToRecord](event: T): Array[Byte] = {
  val baos = new ByteArrayOutputStream()
  val output = AvroOutputStream.binary[T](baos)
  output.write(event)
  output.close()
  baos.toByteArray
}

def fromBinary[T: SchemaFor : FromRecord](bytes: Array[Byte]) = {
  val in = new ByteArrayInputStream(bytes)
  val input = AvroInputStream.binary[T](in)
  input.close()
  input.iterator.toSeq
}

val d = D(B("1"))

val b = toBinary(d)

fromBinary(b)

```

When deserializing there is an error:

` could not find implicit value for evidence parameter of type com.sksamuel.avro4s.FromRecord[`

How can we deserialize ADTs, do we need a [Packing Object ](https://github.com/sksamuel/avro4s/blob/master/avro4s-core/src/test/scala/com/sksamuel/avro4s/examples/TraitObjectEnumerationExample.scala#L38)

But the Packing object, Packs instances and not Type:

`implicit val BasePack = Pack[Base](A -> 0, B -> 1)`

**Comment by sksamuel** [comment]
Sealed traits aren't supported well. It's easier to pick another abstraction to model your data imo.

**Comment by rabzu** [comment]
I apologize.

Next time I will use the stackvoverflow

**Comment by sksamuel** [comment]
No need to apologize :) It's just better for everyone on SO. I'll try and help as I watch for avro4s tags.
