### ISSUE TITLE
Suggestion: change "wontfix" label used by stale bot

### ISSUE THREAD

**Issue by nadavwr** [sksamuel/avro4s#630]
Teeny tiny suggestion: stale bot closes tasks with the `wontfix` tag, which I think has bad optics. I suggest using `stale` or `abandoned` instead, reserving `wontfix` for cases of intentional rejections (e.g. non-goals etc).

Users browsing through pr/issue lists may encounter issues they care about that have been closed, which is completely understandable--I've abandoned PRs in the past, let he who is without sin cast the first stone...
However, seeing them labeled `wontfix` signifies rejection, i.e. the maintainers decided the issue won't be addressed. This is an immediate turnoff and many users won't scroll through the discussion to find out this has been a bot decision. `abandoned` is more likely to engage users who might be inclined to lend a hand.

**Comment by sksamuel** [comment]
Makes sense yeah. Thanks for making the change.
