### ISSUE TITLE
Either of UUID is not working 

### ISSUE THREAD

**Issue by David-hod** [sksamuel/avro4s#636]
code : 
  ```
case class Hello(id: Either[Double,UUID])

  test("write UUIDS") {
    writeRead(Hello(id = Right(UUID.randomUUID())))
  }

```

failure : 

[31m- write UUIDS *** FAILED *** (1 second, 112 milliseconds)[0m
**[31m  com.sksamuel.avro4s.Avro4sDecodingException: Could not decode 46500c76-3a8f-4442-859f-ba8652b361f1 into Either[double, string][0m**
[31m  at com.sksamuel.avro4s.CollectionAndContainerDecoders$$anon$20$$anon$21.decode(CollectionsAndContainers.scala:216)[0m
[31m  at com.sksamuel.avro4s.CollectionAndContainerDecoders$$anon$20$$anon$21.decode(CollectionsAndContainers.scala:202)[0m
[31m  at com.sksamuel.avro4s.RecordFields$FieldDecoder$ValueDecoder.tryDecode(RecordFields.scala:78)[0m
[31m  at com.sksamuel.avro4s.RecordFields$FieldDecoder$ValueDecoder.fastDecodeFieldValue(RecordFields.scala:59)[0m
[31m  at com.sksamuel.avro4s.RecordDecoder.decode(Records.scala:51)[0m
[31m  at com.sksamuel.avro4s.ResolvableDecoder.decode(Decoder.scala:95)[0m
[31m  at com.sksamuel.avro4s.ResolvableDecoder.decode$(Decoder.scala:95)[0m
[31m  at com.sksamuel.avro4s.MagnoliaDerivedDecoders$$anon$6.decode(MagnoliaDerived.scala:80)[0m
[31m  at com.sksamuel.avro4s.AvroDataInputStream$$anon$1.next(AvroDataInputStream.scala:29)[0m
[31m  at com.earnix.offer_managament.InputStreamTest.readData(PlayingLocallySpec.scala:203)[0m

**Comment by David-hod** [comment]
@sksamuel  can you please reply to this issue? how can I workaround it ?

**Comment by sksamuel** [comment]
Should be fixed in 4.0.7

**Comment by David-hod** [comment]
@sksamuel when is 4.0.7 would be relesaed? can you direct me to the timelines?

**Comment by sksamuel** [comment]
It's there now.

**Comment by David-hod** [comment]
@sksamuel  I couldn't find it on maven central.
https://mvnrepository.com/artifact/com.sksamuel.avro4s/avro4s-core

**Comment by sksamuel** [comment]
That site is just a UI that takes forever to sync up with maven central.
You can see it's in maven central here:
https://repo.maven.apache.org/maven2/com/sksamuel/avro4s/avro4s-core_2.13/

**Comment by sksamuel** [comment]
You get this working ?
