### ISSUE TITLE
GenericSerde is too explicit with Option when using JsonFormat

### ISSUE THREAD

**Issue by LeonardMeyer** [sksamuel/avro4s#643]
I was trying to serialize some case class containing `Option` using `GenericSerde `, but I find the way it serializes a bit unusual.
    
```
case class Test(str: Option[String], str2: Option[String], str3: String)
val test = Test(Some("a"), None, "b")
val serde = new GenericSerde[Test](JsonFormat)
val data = serde.serialize("whatever", test)
println(new String(data, StandardCharsets.UTF_8))
```

This gives me `{"str":{"string":"a"},"str2":null,"str3":"b"}`, where I would have expected `{"str":"a","str3":"b"}`

Is there any way to configure this ?

**Comment by l-cdc** [comment]
Hi Leonard,

this is as per the [Avro spec](https://avro.apache.org/docs/current/spec.html#json_encoding), hence not configurable.

> The value of a union is encoded in JSON as follows:
> * if its type is null, then it is encoded as a JSON null;
> * otherwise it is encoded as a JSON object with one name/value pair whose name is the type's name and whose value is the recursively encoded value. […]

**Comment by LeonardMeyer** [comment]
@l-cdc Thanks for pointing that out ! Still it would be nice if this was an opt-in configuration on the `GenericSerde`. Sometimes you juste want to generate clean JSON without caring about the Avro spec. My use case is dumping stuff into a schemaless Kafka topic for later investigation, so I want being able to read that clearly.

**Comment by l-cdc** [comment]
Makes sense – maybe you are interested then in a general JSON library? I quite like [circe](https://circe.github.io/circe/).

**Comment by LeonardMeyer** [comment]
Yes of course I could've pulled a JSON library, but it's too bad having to pull a new dependency only for the problem described. I'll live with the Avroesque JSON I guess.
