### ISSUE TITLE
Incorrect schema for map in case class with Option[Seq[]] on Scala 2.12

### ISSUE THREAD

**Issue by df-0101** [sksamuel/avro4s#674]
Hi, thanks for all the awesome work on avro4s!

I'm seeing the following schema being generated incorrectly for a `map` under one specific circumstance.  Here's a minimal reproduction:

```scala
case class SingleMap(one: Option[Map[String, String]] = None)

// outputs correct schema. Map[String, String] is represented as type: "map"
println(AvroSchema[Option[SingleMap]].toString(true))

// outputs incorrect schema.  Map[String, String] is represented as a "record" type.
println(AvroSchema[Option[Seq[SingleMap]]].toString(true))
```

Here is the incorrect schema being generated, you can see the inner definition of `Some__Map__String_String`:

```json
[ "null", {
  "type" : "array",
  "items" : {
    "type" : "record",
    "name" : "SingleMap",
    "namespace" : "avrotest.AvroTest.main",
    "fields" : [ {
      "name" : "one",
      "type" : [ "null", {
        "type" : "record",
        "name" : "Some__Map__String_String",
        "namespace" : "scala",
        "fields" : [ {
          "name" : "value",
          "type" : {
            "type" : "map",
            "values" : "string"
          }
        } ]
      } ],
      "default" : null
    } ]
  }
} ]
```

vs

```json
[ "null", {
  "type" : "array",
  "items" : {
    "type" : "record",
    "name" : "SingleMap",
    "namespace" : "avrotest.AvroTest.main",
    "fields" : [ {
      "name" : "one",
      "type" : [ "null", {
        "type" : "map",
        "values" : "string"
      } ],
      "default" : null
    } ]
  }
} ]
```

Using:
* Scala 2.12.14
* avro4s v4.0.10 (although have tried with all 4.0.x releases)

Unfortunately I am unable to change either the schema or the version of Scala to work around this issue.
Trying the example above with Scala 2.13.6 produces the _correct_ output, so this would seem specific to 2.12.

If you have any ideas on how I could either fix this issue or work around it then I would most grateful.  Please let me know if I can provide more information etc.

Thanks in advance!

**Comment by sksamuel** [comment]
If it works in 2.13 and not 2.12 then probably something changed (was fixed?) in the compiler regarding implicit precedence.

You can probably work around this by adding in your own custom SchemaFor for the type that fails, where you specify the types you want exactly. Bring this schema for into scope as an implicit before you call the AvroSchema on the main type and it should override.
