### ISSUE TITLE
AvroFixed Annotation Usage

### ISSUE THREAD

**Issue by kalvinnchau** [sksamuel/avro4s#68]
I'm trying to create a schema that has some Fixed types, but I can't figure out how to do it.

I saw that there is an `AvroFixed` annotation and the README mentions that String can be a String or Fixed avro type.

This is what I tried:

``` scala
@ case class FixedTest( @AvroFixed(4) value: String)

defined class FixedTest

@ val fixedSchema = AvroSchema[FixedTest]

fixedSchema: org.apache.avro.Schema = 
{"type":"record","name":"FixedTest","namespace":"$sess.cmd12","fields":[{"name":"value","type":"string"}]}
```

However the output doesn't have the fixed types. I looked a bit through the code, but I don't see anything similar to the other annotations where they check if the AvroFixed annotation exists.

I took a look and tried to see if I could take a stab at implementing it but I'm not sure how the Fixed type should exist, should it have an implicit ToSchema somewhere (I think this would mean it would need its own type and at that point no annotation would be needed?) or should it just be overridden at the end similar to how other annotations are handled.

``` scala
    val field = new Schema.Field(name, schema, doc(annos), defaultNode)
    // check if the AvroField annotation exists, and if it does create a new schema or change this one here??
    aliases(annos).foreach(field.addAlias)
    addProps(annos, field.addProp)
```

If this is already done and I'm just going about this wrong let me know.
Any advice would be much appreciated!
Kalvin

**Comment by sksamuel** [comment]
Fixed in 1.8.2
