### ISSUE TITLE
Support of avro 1.8.2 

### ISSUE THREAD

**Issue by hbraux** [sksamuel/avro4s#682]
Hello This request has already been submitted and I agree that Avro 1.8 is old now but the industry is always behind and the 1.8 binary files are not compatible with 1.9 which make any new version of avro4s unusable.  So would it be possible to release such a version ? Thank you.

I've done the work for release 3.0.3 in the attached git patch, so would you mind releasing a version such as 3.0.N ? 

[support_of_avro_1_8_2.zip](https://github.com/sksamuel/avro4s/files/7381991/support_of_avro_1_8_2.zip)
.

**Comment by sksamuel** [comment]
I think the easiest thing to do is fork this repo, apply your patch and release under a different group id.
That way you can have your 1.8 compatible fork for as long as needed.
