### ISSUE TITLE
Scale and precision of Decimal fields are not taken from original schema

### ISSUE THREAD

**Issue by janresiak** [sksamuel/avro4s#686]
Hi,

The issue is that scale and precision for decimal fields are not taken from schema of generic record.

I mean - in current state we are not able to:
- handle dynamically changing scale and precision for single field (schema provided by schema registry)
- have fields with various scale and precision (single case class)

Similar issue has been described already - https://github.com/sksamuel/avro4s/issues/595

Ragards,
Jan

**Comment by sksamuel** [comment]
Ok I've added more tests and the big decimal decoder definitely uses the schema to pick out the scale and precision. So I think the issue is that the schema being used is not the schema from the record.

Do you have sample code of how you use the schema? Are you using the AvroInputStream ?

**Comment by janresiak** [comment]
Hi
I use version avro4s v4.0.11
Basically i use GenericRecord in Databricks Spark, however here sample from Databricks notebook

For following schema 
{"type":"record","name":"Key","namespace":"...","fields":[{"name":"id","type":{**"type":"bytes","scale":0,"precision":12**,"connect.version":1,"connect.parameters":{"scale":"0","connect.decimal.precision":"12"},"connect.name":"org.apache.kafka.connect.data.Decimal",**"logicalType":"decimal"**}}],"connect.name":"..."}

I got following result
![image](https://user-images.githubusercontent.com/3851768/146802649-5d1a9914-fa5f-4989-876d-31fe415c73d2.png)

However i expect 3155888085

**Comment by sksamuel** [comment]
In that example, it doesn't take the schema from the record, but when the
decoder is generated.
That is why you are seeing the issue.
I'll think about how we can fix this.

**Comment by janresiak** [comment]
ok, please keep the issue open and let me know if i can help with that :)

**Comment by janresiak** [comment]
Hi @sksamuel 
Any update about that?
