### ISSUE TITLE
Dependency small security issue

### ISSUE THREAD

**Issue by michalbogacz** [sksamuel/avro4s#688]
Hello, 

Some time ago avro was updated in master branch to newer version
https://github.com/sksamuel/avro4s/commit/fffc8be38fdc274165c1d7d7114936128eecccd4
any plans to release avro4s with that update?

Avro in version 1.10.1 has dependency vulnerability org.apache.commons:commons-compress@1.20

It was fixed in avro 1.10.2 and 1.11.0.

**Comment by sksamuel** [comment]
Do you want a release of avro4s for scala 2 or scala 3 ?

**Comment by michalbogacz** [comment]
Scala 2

**Comment by sksamuel** [comment]
The scala 2 releases use avro 1.9.2 actually. What's on master is for scala 3.

**Comment by michalbogacz** [comment]
Sorry, that's true, 1.9.2.

But still, this dependency has vulnerabilities https://mvnrepository.com/artifact/org.apache.avro/avro/1.9.2

**Comment by sksamuel** [comment]
You can set jackson to be 2.13.0 in your own build and that will bump the
version of the library with a vulnerability.
