### ISSUE TITLE
Can't create schema for generic type

### ISSUE THREAD

**Issue by ryanworsley** [sksamuel/avro4s#69]
Hi,

I'm a fan of your library, having looked around at the others yours is cleanest and most well thought through.  However I've found a limitation that may be a bug - not sure.

I'm trying to nest case classes like this;

```
case class Message[T](payload: T, identity: String = UUID.randomUUID().toString)
case class MyRecord(key: String, str1: String, str2: String, int1: Int) 

AvroSchema[Message[MyRecord]]
```

However I get the compiler error;
`Could not find implicit SchemaFor[Message[MyRecord]] AvroSchema[Message[MyRecord]]`

I need to avoid having a SchemaFor defined for every T.

Perhaps there's something I'm doing wrong?  I've tried several ways to specify a SchemaFor, but not having a lot of luck.

Really keen to use your library on an up-coming project - please help!

Regards,
Ryan.

**Comment by sksamuel** [comment]
Yep it doesn't work if you have nested generics.

**Comment by ryanworsley** [comment]
Hi @sksamuel - does that also mean there's no way to make it work?

**Comment by giampaolotrapasso** [comment]
Is it possible to write a Custom Type Mappings for `Message[MyRecord]`? I mean I'm in a similar case but there are not too much classes to require a total generic approach.

**Comment by sksamuel** [comment]
At the moment no it fails. Whether this is something that can be worked around I haven't yet investigated.

**Comment by nightscape** [comment]
This might be fixed with https://github.com/sksamuel/avro4s/pull/109

**Comment by sksamuel** [comment]
I know this has been open for a long time but here's an update.
You can do this in 2.0.x (latest is 2.0.2).

Generic types are encoded using the format `<rawname>__<typea>_<typeb>_...._<typen>`

So for the original example in this ticket, the outputted schema would be:

```
{
   "type":"record",
   "name":"Message__MyRecord",
   "namespace":"com.sksamuel.avro4s.github",
   "fields":[
      {
         "name":"payload",
         "type":{
            "type":"record",
            "name":"MyRecord",
            "fields":[
               {
                  "name":"key",
                  "type":"string"
               },
               {
                  "name":"str1",
                  "type":"string"
               },
               {
                  "name":"str2",
                  "type":"string"
               },
               {
                  "name":"int1",
                  "type":"int"
               }
            ]
         }
      },
      {
         "name":"identity",
         "type":"string",
         "default":"5b16ca84-f9e1-46a9-bc5c-8c0052b6dd16"
      }
   ]
}
```

There is a test here which covers this.
https://github.com/sksamuel/avro4s/blob/master/avro4s-core/src/test/scala/com/sksamuel/avro4s/github/GithubIssue69.scala
