### ISSUE TITLE
Unused import on AvroOutputStream usage

### ISSUE THREAD

**Issue by MateuszKubuszok** [sksamuel/avro4s#71]
Copy pasted from my [SO question](http://stackoverflow.com/questions/39806624/test-scala1-unused-import-package-test-avro):

I have small test class like this:

```
package test.avro

object Test extends App {
  import java.io.ByteArrayOutputStream
  import com.sksamuel.avro4s.AvroOutputStream

  case class Composer(name: String, birthplace: String, compositions: Seq[String])
  val ennio = Composer("ennio morricone", "rome", Seq("legend of 1900", "ecstasy of gold"))

  val baos = new ByteArrayOutputStream()
  val output = AvroOutputStream.json[Composer](baos)
  output.write(ennio)
  output.close()
  print(baos.toString("UTF-8"))
}
```

With relevant settings:

```
scalaVersion := "2.11.8"
libraryDependencies += "com.sksamuel.avro4s" %% "avro4s-core" % "1.6.1"
```

When I try to compile it I receive following error message:

```
[error] [path on my drive...]/src/main/scala/test/avro/Test.scala:1: Unused import
[error] package pl.combosolutions.jobstream.common
[error] ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
```

I saw that there was similar error reported on [avro4s issue tracker](https://github.com/sksamuel/avro4s/issues/38), but with implicit error not unused imports. However that was in version `1.5.0` - I am using version `1.6.1` (and tried several versions in-between to check if that's not some random regression). Changing avro4j import to `import com.sksamuel.avro4s._` didn't help either.

On the other hand error message is similar to [this one](https://issues.scala-lang.org/browse/SI-9616). I use Scala 2.11.8, but just in case I checked whether changing to 2.11.7 would help (it didn't).

What else can I try to figure out what is the source of such weird behavior? Is it something that I missed or a bug? Of so where should I file it? I suspect it is something with `ToRecord` trait macros, but I cannot tell for sure.

Removal of "-Ywarn-unused-import" make things work again - should I assume it is a bug in a library?

**Comment by sksamuel** [comment]
Does the jobstream.common package exist ?

**Comment by MateuszKubuszok** [comment]
@sksamuel yes, all packages exists, sorry I changed the names of packages to make it shorter but not everywhere.

I suspect that might be something about `ToRecord` macro:

```scala
package pl.combosolutions.jobstream.common

import com.sksamuel.avro4s.ToRecord

object Test extends App {
  case class TestClass(v: String)
  val record = ToRecord[TestClass]
}
```
reports
```
[error] /media/Workspaces/JobStream/modules/common/src/main/scala/pl/combosolutions/jobstream/common/Test.scala:1: Unused import
[error] package pl.combosolutions.jobstream.common
[error] ^
[info] Resolving org.scoverage#scalac-scoverage-plugin_2.11;1.1.1 ...
[error] one error found
```

**Comment by MateuszKubuszok** [comment]
There is a  if else code in a `ToRecord` section - I just guess some of the imports are not used in one case. This should not be an issue but maybe with https://issues.scala-lang.org/browse/SI-9616 unused imports in macros became an issue in Scala 2.11 when one use `scalacOptions ++= Seq("-Ywarn-unused-import", "-Xfatal-warnings")`.

**Comment by MateuszKubuszok** [comment]
I created PR for this issue. @sksamuel, please, tell me if anything needs fixing there.

**Comment by sksamuel** [comment]
Merged, very good work.
