### ISSUE TITLE
Regression: JSON deserializing of default parameter values

### ISSUE THREAD

**Issue by cornerman** [sksamuel/avro4s#718]
This issue https://github.com/sksamuel/avro4s/issues/106 has a regression. We are again failing if providing a JSON string with missing fields. The JSON deserializer somehow needs an explicit null value again.

I have seen that we had code like to fix this before, but it is not there anymore: https://github.com/sksamuel/avro4s/blob/f71b3e5b135adaed02441e40b22d7d02dd228db4/avro4s-core/src/main/scala/com/sksamuel/avro4s/AvroDataInputStream.scala#L16

Can we fix this again? And/or is there a quick workaround to get it running again?

**Comment by cornerman** [comment]
For now, my workaround is to use this json decoder which implements the correct logic: https://github.com/andeb/avro-json-decoder

**Comment by cornerman** [comment]
Still existing. Please dont close.

**Comment by cornerman** [comment]
Still exists.

**Comment by cornerman** [comment]
Still exists...I really do not like these stale bots.

**Comment by blacklight** [comment]
This issue still exist, it's been going on for years and it forces me to use workaround dependencies like avro-json-decoder. Are there any plans to fix it at some point or shall I start looking into alternative serialization protocols?

**Comment by sksamuel** [comment]
This project is in community mode. I don't work on it. If you want to make a PR I'll happily merge and release.
