### ISSUE TITLE
Add scalajs support

### ISSUE THREAD

**Issue by mlvn23** [sksamuel/avro4s#72]
I'm wondering if you could add support for Scala.js. The restriction is you can't do reflection, so it has to be macros and I think you'll need to use a library like https://github.com/mtth/avsc on the JS side. It might be a good fit with autowire. 

Current solution I'm looking at is upickle (arity < 22) + circe (for arity > 22, but it makes the build extremely slow with shapeless and all), and boopickle for binary (not sure how compatible it's with all the browsers, and it's hard to debug since it doesn't have a human-readable codec). ScalaPB is also an alternative, but you need to write an IDL boilerplate.

**Comment by sksamuel** [comment]
I would love to help you out and support this, but realistically it's like writing another library again and I don't have the time. Happy to take PR's.
