### ISSUE TITLE
SchemaParseException Illegal character in: Application/Json

### ISSUE THREAD

**Issue by David-hod** [sksamuel/avro4s#721]
i am gettingn exception for SchemaParseException("Illegal character in: Application/Json")
we have a very large datamodel 'MyModel'. we have a nested enum for defining a serde 
Enum:
`sealed trait Serdes
  case object `Application/Json` extends Serdes`
we try: 
`val recordFormat = RecordFormat[MyModel]`

We try to serialize an object using 'RecordFormat[MyModel]' and we get the above exception.
How can we fix this issue? 

Thanks for the help.

**Comment by sksamuel** [comment]
You probably can't have the slash in the name.
I would try using @AvroName to rename it.
