### ISSUE TITLE
ImmutableRecord to/from JSON

### ISSUE THREAD

**Issue by kyri-petrou** [sksamuel/avro4s#725]
Hi there. This is probably very simple but can't seem to be able to figure it out, so any help is much appreciated.

Is it possible to convert/construct an ImmutableRecord to/from a JSON string?

**Comment by sksamuel** [comment]
You would probably need to load the json via the json input streams.

**Comment by sksamuel** [comment]
Try something like this:

AvroInputStream.json.from(...).build(...)

**Comment by kyri-petrou** [comment]
Thanks for that. I couldn't get it to work initially but I think it was because I was using avro4s 4.x with Scala 3 via the Scala 2.13 compatibility
