### ISSUE TITLE
AvroSchema produce different results in case of tagged fields.

### ISSUE THREAD

**Issue by aludwiko** [sksamuel/avro4s#73]
I created simple project to reproduce this:
https://github.com/aludwiko/avro-tagging/blob/master/src/test/scala/ConversationStateSchemaSpec.scala

Both tests compile just fine, but depending on imports `AvroSchema` produce different results for:
https://github.com/aludwiko/avro-tagging/blob/master/src/main/scala/com/avrotagging/ConversationState.scala

**Comment by sksamuel** [comment]
I don't plan to support tagged types in avro4s.
