### ISSUE TITLE
missing avro4s-refined build for Scala 3

### ISSUE THREAD

**Issue by Zhen-hao** [sksamuel/avro4s#739]
It seems that there is no Scala 3 build for `avro4s-refined` yet. 

If there is no ongoing work for that, I can take a look and see if I can make a PR.

**Comment by sksamuel** [comment]
Pr welcome!

**Comment by Zhen-hao** [comment]
@sksamuel was the refined module removed at a certain point? 

I see [this `RefinedVersion`](https://github.com/sksamuel/avro4s/blob/master/project/Build.scala#L15) has no reference in other files.

**Comment by sksamuel** [comment]
It didn't work at the time with scala 3 I think, so that's why it was removed.
If someone wants to open a PR to restore it, I can release it.
