### ISSUE TITLE
Missing 'default' definition

### ISSUE THREAD

**Issue by zeal18** [sksamuel/avro4s#743]
Hi @sksamuel! Thank you for the such a great library! Recently I've faced an issue related to schema derivation: it ignores case class field default values.
For the model
```scala
case class FooV2(bar: String, baz: Int = 5)
```
it derives the following schema:
```json
{"type":"record","name":"FooV2","namespace":"foo.bar","fields":[{"name":"bar","type":"string"},{"name":"baz","type":"int"}]}
```
as you can see, the `default` property for the `baz` field is missing.

Scala 3.2.0
avro4s: 5.0.3
`-Yretain-trees` compiler option is set

**Comment by Zhen-hao** [comment]
I'm having the same problem with Scala 3.3.0 and avro4s 5.0.4.

@sksamuel! Can you reopen this one?
