### ISSUE TITLE
Getting warning of local val never used, using AvroInputStream.data

### ISSUE THREAD

**Issue by RayRoestenburg** [sksamuel/avro4s#76]
When using `AvroInputStream.data[SomeType](bytes)` I'm getting a warning, 

```local val in value x$1 is never used``` 

I use `-Xfatal-warnings` as scalac option, which means this turns into an error. 
Am I doing something wrong here, or do you ignore warnings?

The below code triggers the warning:

```
package my.pckg

import com.sksamuel.avro4s._
case class Bla(name: String)
object Avro {
  def fromAvro(bytes: Array[Byte]) = {
    AvroInputStream.data[Bla](bytes)
  }
}
```

**Comment by markschaake** [comment]
I'm also seeing this error, and also have `-Xfatal-warnings` as a scalac option.
