### ISSUE TITLE
Option order serialization

### ISSUE THREAD

**Issue by VankaTaganai** [sksamuel/avro4s#760]
Hi, I've got a question about union order in option serialization. As I understand, now null type is always first in Avro Union. Is it possible to change order of null and value in schema generator?

`Option[String] -> ["null", "string"]` to `Option[String] -> ["string", "null"]`

I've tried to find out how to solve this problem but didn't find an example. Can you help me with that?

**Comment by sksamuel** [comment]
It's not possible, and goes against the avro guidelines.
