### ISSUE TITLE
the problem of new schema creation for each record.

### ISSUE THREAD

**Issue by ferhtaydn** [sksamuel/avro4s#81]
Hi Samuel,

I have a problem when using `ToRecord` for converting case class objects to `GenericRecord` for Kafka, since for each object a new schema is generated like at https://github.com/sksamuel/avro4s/blob/master/avro4s-macros/src/main/scala/com/sksamuel/avro4s/ToRecord.scala#L170, kafka takes an exception like that; https://groups.google.com/forum/#!msg/confluent-platform/gkmtn2FO4Ug/IIsp8tZHT0QJ

Could we have a chance to pass a pre-defined schema for a case class to ToRecord instead of generating at each time.

**Comment by sksamuel** [comment]
That creates a new schema for each ToRecord instance, but you only need a single ToRecord for any particular case class. Are you creating a new ToRecord each time? If so, try reusing it.

**Comment by ferhtaydn** [comment]
Thanks Sam, you are right, it is solved.

**Comment by sksamuel** [comment]
:+1:
