### ISSUE TITLE
Scala 2.12 Build

### ISSUE THREAD

**Issue by jon-hanson** [sksamuel/avro4s#83]
Hi,

What's the score with a Scala 2.12 build? The front page indicates that 1.6.2 has a 2.12 build, however I can only find 1.6.2 builds for M3 & M4 here:

http://search.maven.org/#search%7Cga%7C1%7Cavro4s-core_2.12

Thanks,
Jon

**Comment by sksamuel** [comment]
After upgrading to 2.12 final all the macros fail. I assume its a bug and
will be fixed in 2.12.1. I don't have the link handy in the bug tracker.

**Comment by jon-hanson** [comment]
Irksome. Ok, thanks, will ponder reverting to a 2.11 build while I await 2.12.1.

**Comment by sksamuel** [comment]
https://gist.github.com/alexandru/26400bfc6209d4884d9cc916ad48d196

**Comment by sksamuel** [comment]
https://groups.google.com/forum/?fromgroups#!topic/scala-internals/35uGsuIEnDQ

**Comment by sksamuel** [comment]
Released as 1.6.3
