### ISSUE TITLE
enums don't work in unions or arrays

### ISSUE THREAD

**Issue by retnuh** [sksamuel/avro4s#85]
Hi there.

This may be related to #60 but I'm not sure; thought I'd report it anyway.  It may also be two separate bugs; let me know if you'd like me to file it as two separate issues.

I can't seem to get an enum to work inside either a union or an array.

For the array case, I can create a wrapper record with one field that holds the array; I haven't tried the wrapper with the union.

I start with the avsc file and generate the Scala code.  The scala case classes look fine, but blow up when trying to serialize using the data codec.

**Comment by sksamuel** [comment]
Scala enums? If so, we'll just have to forget they exist. No way to get all the details needed at compile time, as you can see from #60. I'd just use a Java enum.
