### ISSUE TITLE
No implicit `FromRecord` when deserializing json encoded data

### ISSUE THREAD

**Issue by esthom** [sksamuel/avro4s#89]
I am trying to run a code sample from README, namely:

```
case class Composer(name: String, birthplace: String, compositions: Seq[String])

val json = "{\"name\":\"ennio morricone\",\"birthplace\":\"rome\",\"compositions\":[\"legend of 1900\",\"ecstasy of gold\"]}"
val in = new ByteInputStream(json.getBytes("UTF-8"), json.size)
val input = AvroInputStream.json[Composer](in)
val result = input.singleEntity
```

but I receive the following exception

```
could not find implicit value for evidence parameter of type com.sksamuel.avro4s.FromRecord[Composer]
[error]     val input = AvroInputStream.json[Composer](in)
[error]                                               ^
```

I actually think that `ByteInputStream` is misused in this case (what library?). Should it be `ByteArrayInputStream`? Although using `ByteArrayInputStream` throws the same exception.

**Comment by KimStebel** [comment]
Are you getting this error from your IDE/editor or from scalac?

**Comment by esthom** [comment]
@KimStebel it turned out I had to `clean compile` all modules in project and it works now.
