### ISSUE TITLE
Cannot serialize a container with an enum

### ISSUE THREAD

**Issue by YuvalItzchakov** [sksamuel/avro4s#91]
Given the following reproduce:

```scala
object Decs {

  object X extends Enumeration {
    type X = Value
    val Y, Z = Value
  }

  import X._
  case class Foo(x: X)

  def main(args: Array[String]): Unit = {
    println(AvroSchema[Foo])
  }
}
```

I get the following error:

> Error:(19, 23) not enough arguments for method apply: (implicit schemaFor: com.sksamuel.avro4s.SchemaFor[othertests.Decs.Foo])org.apache.avro.Schema in object AvroSchema.

> Unspecified value parameter schemaFor.
    println(AvroSchema[Foo])
Error:(19, 23) Could not find implicit SchemaFor[othertests.Decs.Foo]
    println(AvroSchema[Foo])

According to the README, an enum should be properly serialized. Am I missing something here?

**Comment by sksamuel** [comment]
Scala enums are not handled, I will update the readme. I'd recommend a Java enum.
