### ISSUE TITLE
Incorrect namespace for packages with uppercase characters

### ISSUE THREAD

**Issue by vlovgr** [sksamuel/avro4s#93]
With the following package and case class (notice sub-package `C` is uppercase):
```scala
package a.b.C

case class D(e: Int)
```

we generate a schema for `D` using:
```
import com.sksamuel.avro4s.SchemaFor

object Main extends App {
  println(SchemaFor[a.b.C.D]().toString(true))
}
```

and get the following result:
```scala
{
  "type" : "record",
  "name" : "D",
  "namespace" : "a.b",
  "fields" : [ {
    "name" : "e",
    "type" : "int"
  } ]
}
```

but we expect the namespace to be `a.b.C`. If we make sub-package `C` lowercase, it works as expected (namespace `a.b.c`).

I believe [this](https://github.com/sksamuel/avro4s/blob/15e12f00f7b94ca2d44d783566ba3abc7f2b6dba/avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala#L301) might be what's responsible for the described behaviour.

**Comment by sksamuel** [comment]
Uppercase package names is really odd. Goes against the style guides for both Java and Scala. Is there a genuine use case for it ?

**Comment by sksamuel** [comment]
I'm going to close this, as upper case package names goes against both the scala and java style guidelines. http://docs.scala-lang.org/style/naming-conventions.html#packages
