### ISSUE TITLE
Working with classes

### ISSUE THREAD

**Issue by muggin** [sksamuel/avro4s#96]
Hi, I'm new to Scala and to this library. I would like to know if it is possible to do binary (de)serialization on a standard Scala `class` instead of a `case class`.

I got my code to run with case classes, but when I try to use it with classes I get the following error during compilation 
`
Error:(75, 41) exception during macro expansion: 
java.lang.IllegalArgumentException: requirement failed: Require a case class but ir.PostingsList is not
	at scala.Predef$.require(Predef.scala:277)
	at com.sksamuel.avro4s.FromRecord$.applyImpl(FromRecord.scala:231)
    implicit val fromrecord = FromRecord[PostingsList]`

I tried adding implicit To/FromRecord values, it doesn't help. 
Thanks for the help in advance.

**Comment by sksamuel** [comment]
Unfortunately not. Case classes are easier to work with as they have a guaranteed constructor. Are you not able to change your domain to use case classes?

**Comment by muggin** [comment]
Thanks for the fast response. I am able to change my domain, but those classes carry mutable state and include some logic. AFAIK the "zen of Scala" says that classes should be immutable, I was trying to stick to that...

**Comment by muggin** [comment]
@sksamuel I redid my code and created `FrozenPostingsList` case classes that are actually immutable just for the purpose of serializing, BUT I encountered another problem. Serializing and De-serializing works fine if I just serialize the case class `FrozenPostingsList`. In the case when I want to use Avro for de/serializing `Map[String, FrozenPostingsList` serialization works fine but I get the same error as above when trying to deserialize. Any tips? From the README file I thought type `Map[String, T]` should work?

**Comment by muggin** [comment]
Resolved, thanks for your help again.
