### ISSUE TITLE
How to generate Scala source code from schema?

### ISSUE THREAD

**Issue by Renkai** [sksamuel/avro4s#98]
[This site](http://avro4s-ui.landoop.com) claims it is a web UI for avro4s, and it can convert avro schemas to scala class definitions. But I can't find such methods in the source code, where can I find them?

**Comment by lmlynik** [comment]
This is interesting as I was looking it up so, in 1.6.0 there was a module called avro4s-generator which had it. Since 1.6.1 its not anymore.

**Comment by Renkai** [comment]
@lmlynik seems migrated to https://github.com/sksamuel/sbt-avro4s

**Comment by sksamuel** [comment]
Yes use sbt-avro4s.
